### ISSUE TITLE
Diff Objects Graphs by Value

### ISSUE THREAD

**Issue by ovu** [javers/javers#1007]
Hi there,

public class Article {
String Id;
Int Height;
Int Width;
List<Price> prices;
List<Titles> titles;
}

javers.compare(article1, article2)

I am using javers to compare two objects (Articles, see above) created by different systems (Microservices). However I get in 
javers ListChange prices, ListChange titles, NewObject and ObjectRemoved. I am comparing two articles and I would like to compare prices and titles by Value, obviously the lists are different because they are different instances. Is there a way to achieve that? 

Thanks for your help.

**Comment by bartoszwalacik** [comment]
hi, questions should be asked at https://stackoverflow.com/questions/tagged/javers
