### ISSUE TITLE
Add JsonConverter object to DI container in javers-persistence-sql

### ISSUE THREAD

**Issue by pawelszymczyk** [javers/javers#101]

**Comment by pawelszymczyk** [comment]
And next remove setJsonConverter(...)  methods from *Repository.java and *Finder.java, JsonConverter should be provided by constructor

**Comment by bartoszwalacik** [comment]
nie mam pomysłu jak to poprawić bez komplikowania, w stylu
wprowadzenie dziedziczenia kontenerów Pico,
 dopóki te settery są ukryte przed użytkownikiem to nie ma dramatu, Wont FIX
