### ISSUE TITLE
Is there a way to force a commit?

### ISSUE THREAD

**Issue by sebastianhaberey** [javers/javers#1013]
**Is your feature request related to a problem? Please describe.**

We would like to force a JaVers commit for an entity that didn't change (we want to attach commit properties to it).

**Describe the solution you'd like**

The commit should be handled like any other commit (but with an empty change list).

**Describe alternatives you've considered**

We discussed adding some attribute to the entity in question and change it, or change an existing attribute, but that's not ideal.

**Comment by bartoszwalacik** [comment]
no, there is no such option
