### ISSUE TITLE
Shadow contains incorrect value for initialized boolean field

### ISSUE THREAD

**Issue by andreiamariei** [javers/javers#1014]
**Description**
If a Java class initializes a `boolean` field to `true`, the shadows found for this class will contain the initialized value even when the original object had the field set to `false` (value I expected in the shadows too).

It seems it behaves correctly for Groovy classes though.

**Steps To Reproduce**
I have a runnable test case which isolates the bug and allows Javers Core Team to easily reproduce it. I have pushed this test case to my fork of this repository:

https://github.com/andreiamariei/javers/blob/issue/shadow-of-class-with-boolean-field-initialized/javers-core/src/test/java/org/javers/core/cases/CaseShadowWithInitializedPrimitiveBooleanField.java#L16

**Javers' Version**
5.11.1

**Comment by bartoszwalacik** [comment]
fixed in 5.11.2

**Comment by andreiamariei** [comment]
Many thanks!
