### ISSUE TITLE
Query snapshots from UTC datetime

### ISSUE THREAD

**Issue by nickshoe** [javers/javers#1019]
I need to retrieve from the DB all the snapshots of a given class, starting from a given point in time. My application stores dates according to UTC, as it is much simpler to handle when it comes to i18n and i10n.

At the moment, its not possible to query for snapshot from a given UTC datetime, but only from a local datetime.

The only way of doing this is by "fooling" the query builder, by first converting an UTC datetime into a local datetime. I consider this rather an hack. 

Apparently, Javers already stores the UTC datetime `commit_date_instant` in the `jv_commit` table. 
(I don't know why, but the microseconds part sometimes differs between the two dates)
![image](https://user-images.githubusercontent.com/32668766/92883869-92a30500-f411-11ea-86cb-942ae0a1e582.png)

**Describe the solution you'd like**
An additional `fromUTC` or `fromInsant` or `from(Instant ...)` method that takes UTC datetime (`Instant`) would solve my problem.

**Additional context**
I'm taking advantage of JaVers for exposing a Data Synchronization API in my application. In this context, the third party system needs to ask all the changes that have occured since the latest commit read in the previous interaction. The majority of REST API uses ISO8601 UTC dates for serializing datetime in the JSON payload.

**Comment by nickshoe** [comment]
For the sake of data synchronization, it would be even better to have the possibility of querying snapshots from a given commit id (excluded) onwards.

**Comment by bartoszwalacik** [comment]
fromInsant() would be more natural, since `Commit` has `commitDateInstant` persisted. We will accept your PR.

**Comment by bartoszwalacik** [comment]
released in 5.12
