### ISSUE TITLE
N+1 problem in CdoSnapshotFinder

### ISSUE THREAD

**Issue by pawelszymczyk** [javers/javers#102]
Probably we should use one query instead of n+1 queries for download CdoSnapshots for given globalId.  

Here is link to loop that generates a problem:

https://github.com/javers/javers/blob/%2367_sql_repository/javers-persistence-sql/src/main/java/org/javers/repository/sql/finders/CdoSnapshotFinder.java#L72

**Comment by bartoszwalacik** [comment]
problem n+1 zapytań został zlikwidowany
