### ISSUE TITLE
[Proposal] Prepare issues for Hacktoberfest 2020 

### ISSUE THREAD

**Issue by tinesoft** [javers/javers#1023]
The [Hacktoberfest ](https://hacktoberfest.digitalocean.com/)2020 Edition, is starting this **October 1st**.
This yearly event, helps promote contributions to OSS projects, during the whole month of October.

What needs to be done, in order to "prepare" this project for this event is [quite simple](https://hacktoberfest.digitalocean.com/details#rules):
* identify/create issues that are suitable for [first-timers] contributions (issues currently labeled "help wanted", "good first issue", "hacktoctoberfest", are good candidates)
* [Update since  October 3rd]add "hacktoberfest" topic to the project to opt-in to the event and increase visibility from [Hacktoberfest Website](https://hacktoberfest.digitalocean.com)

I use and love Javers ❤️ !  So i'm planning to contribute myself during the event (and beyond). 
Adding the above steps, will help attract even more well-deserved attention/contributions to this great project!

**Comment by BhaveshSalunke** [comment]
Hey, @tinesoft any good first issue to work on?

**Comment by tinesoft** [comment]
Ping @bartoszwalacik?

**Comment by bartoszwalacik** [comment]
hi @tinesoft @BhaveshSalunke 
topic added, issues [tagged](https://github.com/javers/javers/issues?q=is%3Aissue+is%3Aopen+label%3AHacktoberfest)
you are welcome to contribute :)
