### ISSUE TITLE
Store actual data in a relational database and data changes in mongodb?

### ISSUE THREAD

**Issue by lucamaral** [javers/javers#1033]
Hi everyone!

I was wondering if using Javers I could store the actual data in a relational database and the data changes in mongodb, its possible?

**Comment by bartoszwalacik** [comment]
No, javers uses a single database and only for storing objects' snapshots. It's not a replacement for Spring Data or Hibernate.
btw. you should not open issues to ask a question, please do it on https://stackoverflow.com/questions/tagged/javers
