### ISSUE TITLE
Unable to provide author for reactive spring

### ISSUE THREAD

**Issue by NiamhAsura** [javers/javers#1047]
I am using Spring and am wanting to add the author when recording changes for audit purposes. I am using `JaversSpringDataAuditable` on my repository which is working. However I cannot seem to find a clear code example on how to do this using reactive spring. 

The `SpringSecurityAuthorProvider` gets the authentication like so:
`Authentication auth = SecurityContextHolder.getContext().getAuthentication();` 
This is null for reactive, so if I create my own `AuthorProvider`, I instead would like to use
`ReactiveSecurityContextHolder.getContext().map { it.authentication) }`
However this returns a Mono, which cannot be blocked, and is therefore unusable by the `AuthorProvider.provide()`.

I am still quite new to Spring, so I might be missing something obvious. Thanks!

**Javers' Version**
5.14.0

**Comment by bartoszwalacik** [comment]
cross-posted https://stackoverflow.com/questions/65492549/how-to-get-authentication-imperatively-in-reactive-spring
