### ISSUE TITLE
Similar annotation to ShallowReference that doesn't ignore properties in findShadow

### ISSUE THREAD

**Issue by mateusmento** [javers/javers#1048]
I need to use ShallowReference to my entities when auditing but I still need to get all ignored properties when calling findShadow.

I need this requirement because my team use shared entities in different microservice. We usually specialize one microservice for saving and deleting and allow others microservices only to fetch external entities. 

With that we use ShallowReference to all external entities in a microservice for auditing because no change will happen to them, we only change the reference to a different entity in a relation. 

Now each microservice has an endpoint for retrieving a list of restore versions of an entity. We need those external entities to come with all its properties. You can assume they were previously saved and audited.

Is there a way to do it with the current api? If not it would be great to have it as a new feature!

**Comment by bartoszwalacik** [comment]
I don't understand your story. Try to reword it but in the context of Javers features and not your endpoints.

**Comment by mateusmento** [comment]
I need to ShallowReference ignore some of my associations when auditing an entity but still be able to restore all ignored properties when calling findShadow for that entity. The entities ShallowReference ignored would've been previously audited and no changes would've been made to the associated entities when auditing the main entity.

To illustrate my problem, if I audit an entity such as this:

`
package company;
@TypeName("Company")
class Company {
	@Id
	private Integer id; 
	private String name;
	private String cnpj;
	@ManyToOne
	private CompanyGroup group;
}`

And then I audit an aggregate such as the following without any change to Company entity:

`
package user;
@TypeName("Company")
class Company {
	@Id
	private Integer id; 
	private String name;
}

class User {
	@Id
	private Integer id;
	private String name;
	@ManyToOne
	private Company company;
}`

When auditing User, Javers would audit a change for the Company entity because of the missing properties in Company from user package. To avoid that I use ShallowReference for the company assocation in User but then I'm not able to restore Company entirely when findShadow a User.

**Comment by bartoszwalacik** [comment]
If you have two different classes with the same javers TypeName -- "Company" -- it's a misuse. Javers doesn't support it
