### ISSUE TITLE
A way to restore properties of a entity, ignored by ShallowReference, on findShadow

### ISSUE THREAD

**Issue by mateusmento** [javers/javers#1049]
A way to restore properties of a entity, ignored by ShallowReference, on findShadow. A new annotation or flag in ShallowRerence would work.

```java
class A {
   private @Id Integer id;
   // All properties of class B should be restored when findShadow class A with scope DEEP_PLUS
   private @ShallowReference(ignoreOnCommitOnly=true) B b;
}

class B {
  private @Id Integer id;
  private int n;
}
```

Do you think this is good as new feature? If not, why?

**Comment by bartoszwalacik** [comment]
I don't understand you. If you use @ShallowReference on an object, it properties are not saved in JaversRepository. Where do you want to find them?

**Comment by mateusmento** [comment]
No, quite the contrary, I believe. If the object was separately audited and no changes are made to it when auditing an aggregate with that object, I believe findShadow DEEP_PLUS could restore that aggregate with the last version of the object before the aggregate's commit.

I've explain better the context and reasons for that feature in here https://github.com/javers/javers/issues/1048.
