### ISSUE TITLE
Hi Bro, i'm a newbie,

### ISSUE THREAD

**Issue by luongbaotin7777** [javers/javers#1050]
I'm new, your library is awesome. Can you show me how to customize diff.getChanges () return information?
There are many returns but I don't really need them,
I just returned something like:
User
{
    "typeChanges": "ChangeValue",
    "propertyChanges": "UserName",
    "OldValue: AdminSuper",
    "CurrentValue: NomalUser",
  "Role": {
                "typeChanges": "ChangeValue",
                "propertyChanges": "RoleName",
                "OldValue: admin",
                "CurrentValue: user",
            }
}

In the above example, User is the parent, Role is a child of User and is in User.

Is there a way for me to do that?
Sincerely thank

**Comment by bartoszwalacik** [comment]
Hi Bro, this is not the right place for questions about basics, ask at https://stackoverflow.com/questions/tagged/javers
