### ISSUE TITLE
Getting all snapshots for a nested entity id

### ISSUE THREAD

**Issue by NiamhAsura** [javers/javers#1052]
I have two example (simplified) entities:

    @Entity(name="contact") 
    class ContactEntity(
            @field:Id
            @field:GeneratedValue(strategy= GenerationType.IDENTITY)
            var id: Long = 0L,
    
            @ShallowReference
            @OneToMany(mappedBy = "startingContactEntity", fetch = FetchType.EAGER)
            var startingLinkedContacts: Set<ContactEntityLinks>

            @ShallowReference
            @OneToMany(mappedBy = "endingContactEntity", fetch = FetchType.EAGER)
            var endingLinkedContacts: Set<ContactEntityLinks>,
    ) 

    @Entity(name="contact_link") 
    class ContactLink(
            @field:Id
            @field:GeneratedValue(strategy= GenerationType.IDENTITY)
            var id: Long = 0L,
    
            @ShallowReference
            @ManyToOne
            @field:JoinColumn(name = "start_contact_entity", referencedColumnName = "id")
            var startingContactEntity: ContactEntity,
    
            @ShallowReference
            @ManyToOne
            @field:JoinColumn(name = "ending_contact_entity", referencedColumnName = "id")
            var endingContactEntity: ContactEntity,
    
            @field:Enumerated(EnumType.STRING)
            @field:Column(nullable = true, name="relationship")
            var linkRelationship: ContactLinkType,
    ) 

I would like to get all snapshots where a particular contact is involved (there are other entities a contact may be involved in, but for the sake of the question). If I have e.g. 5 snapshots (all INITIAL)
1) ContactEntity (id: 1)
2) ContactEntity (id: 2)
3) ContactEntity (id: 3)
4) ContactLink (id: 1, startingContactEntity: ContactEntity (id: 1), endingContactEntity: ContactEntity (id: 2))
5) ContactLink (id: 2, startingContactEntity: ContactEntity (id: 1), endingContactEntity: ContactEntity (id: 3))

I want to search for e.g. Contact with id 1, and get the snapshots 1, 4, 5 back. Or search for contact with id 2, and get snapshots 2 and 4 back. Is this possible with using JQL?

I have experimented with the different query filters, but could not see that they were able to do this.

Thanks

**Comment by bartoszwalacik** [comment]
@NiamhAsura we do not provide free consulting service here, try to ask at stackoverflow.
Here is the place where you can post a feature request or a bug report. This is not a feature request, it's just a peace of code taken from your project.
