### ISSUE TITLE
Composite @id only works with Annotations and not with newEntityDefinition

### ISSUE THREAD

**Issue by thaben** [javers/javers#1053]
I am currently using Javers version 5.11.1  and I noticed that composite IDs are supported but only with the annotation way . 
e.g. :
```
User{
@Id
String id;
@Id
String name;

```

When I declare a new EntityDefinition e.g. :

```
Javers javers = JaversBuilder.javers()
                                     .registerEntity(new EntityDefinition(User.class, "id")
                                     .build();
```

I can only declare one property "id". Could this be updated in order to support a List of strings like ignoreProperties work?

**Comment by bartoszwalacik** [comment]
@see EntityDefinitionBuilder

```
/**
 * Recipe for {@link EntityType}
 *
 * @see EntityDefinitionBuilder
 * @author bartosz walacik
 */
public class EntityDefinition  extends ClientsClassDefinition {
```
