### ISSUE TITLE
Shadow not found for nested property value change

### ISSUE THREAD

**Issue by lara0** [javers/javers#1056]
Hello,
I've been trying to get history of entity changes using something like this:
```
    List<Shadow<Receipt>> shadows =
    javers.findShadows(QueryBuilder.byInstanceId(1, Receipt.class).withScopeDeepPlus().build());

    if (shadows.size() > 1) {
        Diff diff = javers.compare(shadows.get(0).get(), shadows.get(1).get());
    }
```

Considering I have something like this as entity:
```
    @Entity
    public class Receipt {

        @Id
        private Long id;

        private LocalDate date;
              
        @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
        @JoinColumn(name = "receipt_id", foreignKey = @ForeignKey(name = "fk_receipt"), nullable = false)
        private List<Item> items;
    }
```

And Item class:
```
    @Entity
    public class Item {

        @Id
        private Long id;
              
        private String name;

        private BigDecimal price;
    }

```

Let's say I have one INITIAL commit of Receipt entity and I decide to update `date` field. By using the first snippet of the code above, two shadows will be found and `diff` will contain `date` as a changed value. Now, if I do the same, but change `name` from Item class, second shadow won't be found at all and therefore no changes will be found either. Is there any way I can get these changes too?

**Comment by bartoszwalacik** [comment]
Hi, we do not answer questions here, try to ask at stack, btw try to use javers.findChanges()
