### ISSUE TITLE
Add context information to global id table

### ISSUE THREAD

**Issue by edudant** [javers/javers#1060]
**Is your feature request related to a problem? Please describe.**
Example domain - entities: Customer -> Accounts -> Contacts. The relationship between contact, account and customer is not allowed to change.

I need to create a complete audit trail for everything related to the customer (in the form of changed property, old value, new value).

The only way to find all contact changes related to the customer, I need to search in jv_snapshot.state value which would be slow.

**Describe the solution you'd like**
Add new *context* column (columns) to jv_global_id. For my use case most straightforward and performing solution is to add customer_id and account_id columns, but I can imagine a more generic way.

**Describe alternatives you've considered**
* Change data type of jv_snapshot.state to JSONB datatype (postgres) and create an index for this field
* Move snapshot table from the database to elasticsearch
* Use envers and add indexes for required fields
* Custom implementation of audit trail

**Additional context**
We may help with the implementation if the solution is viable.

**Comment by bartoszwalacik** [comment]
Hi, I'm not sure by what you'd like to search. Forget about a DB for a moment and describe your feature request from a Javers API perspective, I mean the Javers class

**Comment by edudant** [comment]
Hi,

there are two options - either a more streightforward `Commit commit(String author, Object currentVersion, Map<String, String> context);` or a new annotation on the domain object  property `@JaversContext(name="customerId") Long customerId` (Account and Contact classes from the example domain).

Then I will search for all changes related to the customer with `javers.findChanges( QueryBuilder.anyDomainObject().withContext("customerId", 12345).build() )`.

From the API point of view it is similar to commit properties. However, I cannot use commit properties because two different customers may be modified in a single commit.

**Comment by bartoszwalacik** [comment]
I don't get it. You suggest to rename`commitProperties` to `context`. Sorry, but it doesn't have any purpose for me.

The existing API looks like this:

```
Commit commit(String author, Object currentVersion, Map<String, String> commitProperties);

QueryBuilder.anyDomainObject().withCommitProperty("customerId", "12345").build() ).
```

**Comment by edudant** [comment]
I wrongly assumed that commit is related to the actual transaction (similar to Envers revinfo) and that multiple entities (customers in my case) might be part of a commit. If one commit = one entity, then commit property is really the same as proposed context property. 

It is strange for me, that "commit" does not match the actual transaction behaviour, but I assume that this is your architectural decision. Thank you for your time anyway.

**Comment by bartoszwalacik** [comment]
Javers commit is similar to git commit and not to commit on relational database. Using javers is not limited to traditional SQL databases, for example Javers works with Mongo DB
