### ISSUE TITLE
Please consider adding a covering index for local_id and type_name in jv_global_id

### ISSUE THREAD

**Issue by a-mujthaba321** [javers/javers#1065]
I am using Javers in a medium enterprise application and I keep getting deadlocks on this particular query.

SELECT global_id_pk FROM jv_global_id WHERE local_id = ? AND type_name = ?

When I checked the execution plan it was reading all the rows in the jv_global_id  table. I added a covering index for local_id and type_name ( as suggested by SQL Server Management Studio), the number of rows read decreased significantly.

I ran the test on a database with 10853 rows in jv_global_id . Without index the query was reading all 10853 rows in the table. With index the query was reading only 34 rows, which is a 99% reduction in rows read. Now I know adding an index will impact the write queries but reading the whole table every time is a lot worse in my opinion. 

If this has been reported and it was rejected for some reason please let me know.

I am currently using Javers 3.11.2 but I checked with latest version and there was no index added for these fields.

**Comment by bartoszwalacik** [comment]
3.11.2 seems pretty old. In new versions, Javers *should* create index on `jv_global_id.local_id`. See `FixedSchemaFactory.globalIdTableSchema`. It works on mainstream databases like Postgres and MySQL.
We have a dockerized tests for SQL Server  (`MSSqlDockerIntegrationTest`) but I can't easily check if the index is created. 
Could you please check it for me using the latest Javers version?

**Comment by a-mujthaba321** [comment]
You're right. There is an index on local_id both in latest version and in version 3.11.2 and I checked it in SQL server. 

Correct me if I am wrong, but wouldn't it be better to have an index which included both local_id and type_name since these columns are queried a lot?

**Comment by bartoszwalacik** [comment]
well, hard to say, an index doesn't have to be unique. How it performs depends on you data structure. How many classes you have? Is local_Id alone selective enough? Bigger index (two fields) means slower writes, but possibly yes, faster reads.
