### ISSUE TITLE
JsonConverterDateTimeTest fails on some timezones

### ISSUE THREAD

**Issue by yagami26** [javers/javers#1068]
The JsonConversion test is incomplete if we only take into account the offset hours. In timezones such as Asia/Kolkata +5:30 this test is failing since minute offset isn't taken into consideration

**Steps To Reproduce**
Change the timezone on the system to Asia/Kolkata, and run this specific test again.

**Javers' Version**
5.**

**Additional context**
I have a updated version of test on my forked branch [here](https://github.com/yagami26/javers/commit/b8f1c8be5dbd6c8e985641cc11ad3da3b3d89b0f)  and would like to contribute :)

**Comment by bartoszwalacik** [comment]
fine, so go on and create a PR

**Comment by bartoszwalacik** [comment]
thanks, pro-tip: if you want your commit to be counted as yours (and to be listed as a javers contributor), bind the email address from this commit to your github account
