### ISSUE TITLE
Support for CosmosDB

### ISSUE THREAD

**Issue by pepe-escrich** [javers/javers#1086]
Are there any plans to include support for Azure Cosmos DB?

When I try to use Javers with Azure Cosmos DB using Spring Boot Mongo Starter get this error:

Command failed with error 115 (CommandNotSupported): 'Unique and compound indexes do not support nested paths.' on server valenciapiloto-westeurope.mongo.cosmos.azure.com:10255. The full response is {"ok": 0.0, "errmsg": "Unique and compound indexes do not support nested paths.", "code": 115, "codeName": "CommandNotSupported"}

I found a reference of this problem on stackoverflow -> https://stackoverflow.com/questions/60928892/compound-index-does-not-currently-support-nested-documents-or-arrays-in-azure-co

**Comment by bartoszwalacik** [comment]
I have no plans for Cosmos DB, if you need it, consider contributing a PR.

**Comment by xytrams** [comment]
Hi, I managed to configure javers for cosmos DB.
There (I believe error in cosmos db advised configuration, but after some hours of debugging I managed to configure it)
my yml: 

azure:
  cosmos:
    uri: mongodb://${COSMOS_HOST}:${COSMOS_KEY}@${COSMOS_HOST}.documents.azure.com:443/${COSMOS_DB}?ssl=true 
    key: ${COSMOS_KEY}
    database: ${COSMOS_DB}
    queryMetricsEnabled: false

javers:
  mongodb:
    uri: mongodb://${COSMOS_HOST}:${COSMOS_KEY}@${COSMOS_HOST}.documents.azure.com:10255/${COSMOS_DB}?ssl=true

**Comment by bartoszwalacik** [comment]
^ solved by the configuration ^
