### ISSUE TITLE
Unsupported major.minor version 51.0 (unable to load class org.javers.core.JaversBuilder)

### ISSUE THREAD

**Issue by juki** [javers/javers#109]
Hello, I am trying to use Javers on Java 6 but this is happening:

java.lang.UnsupportedClassVersionError : org/javers/core/JaversBuilder : Unsupported major.minor version 51.0 (unable to load class org.javers.core.JaversBuilder)

Is it possible to use Javers on Java 6 or only Java 7 and up?

Thank you!

**Comment by bgalek** [comment]
Sorry my friend, javers won't work with java6. I suggest you to move to
java7/8 world!
19 lut 2015 20:20 "juki" <notifications@github.com> napisał(a):

**Comment by juki** [comment]
I would love to move, stuck on bureaucracy. Will have to look for other solutions. Thanks anyway!
