### ISSUE TITLE
Query with like operator

### ISSUE THREAD

**Issue by lucas-prestes** [javers/javers#1096]
Hello everyone, I'm just getting started using JaVers, and wanted first of all to thank you all,  it is really easy to use and configure.
There is just one feature I miss though, and that is the ability to use the like operator with the Commit Metadata properties.
Currently I have a commit property I wish to use as filter,  the ideal scenario would be the user being able to  type any part of said property, eg: Let's say there is a commit property 'name' with the value John Doe, in the use case I was building both 'John' and 'Doe' or even 'John D' would return the same data.
For now I would probably end up filtering this after bringing  all the rows from the database, but I think it would be really cool( not to mention having way more performance) if this was part of the JQL spec.
From what I saw from the source code one way it could happen would be having a withCommitPropertyLike in the QueryBuilder class, that would render a 'LIKE %:property%' on the final SQL for the JaversSqlRepository, and it could translate to a simple String.contains for the In memory implementation.

**Comment by lucas-prestes** [comment]
Hi again, I was feeling motivated so I played a little with Javers code and implemented this feature using the WithCommitProperty method as an example, and all unit tests are passing, so if its ok  with you I can submit a PR

**Comment by bartoszwalacik** [comment]
Hi, ok, create a PR, I'd like to see the code

**Comment by bartoszwalacik** [comment]
released in 6.2.4
@lucas-prestes thanks for this high quality contribution
