### ISSUE TITLE
Decimal point truncation between persistent db data and javers snapshot data

### ISSUE THREAD

**Issue by azharakbar** [javers/javers#1105]
**Clear description of my expectations versus reality**
Hi JaVers,
I have integrated JaVers with my SpringBoot application

I am facing with the following issue
I have the following entityClass
```
@Data
@Entity
@NoArgsConstructor
@AllArgsConstructor
public class RepairDefaultInput extends BaseEntity {
    @Id
    @GeneratedValue(generator = "UUID")
    @GenericGenerator(name = "UUID", strategy = "uuid2")
    @Column(name = "Id", columnDefinition = "uniqueidentifier")
    private String id;

    @Column(name = "critical_repair_cost", nullable = false)
    private BigDecimal criticalRepairCost;
}
```

Here, the `criticalRepairCost` is a `BigDecimal` and the value I have in my persistent DB is **`1000.00`**

But in ``jv_snapshot`` table, the snapshot is saved as ``{ "criticalRepairCost" : "1000"}``
Here, the decimal places of **`.00`** is lost in the snapshot info

As a consequence,
when I do a ``javers.compare``, I get this field as a diff, which ideally should not?

Why is this issue ?

Thanks, in advance

**Javers' Version**
5.14.0

**Comment by bartoszwalacik** [comment]
can't reproduce, this [test](https://github.com/javers/javers/commit/2b9a5ad851d18d7152b34d319bb4ac629213b89f) shows that BigDecimals are stored properly .
could you write a minimal test case and reproduce this issue?

**Comment by azharakbar** [comment]
Hi @bartoszwalacik 
Is this tested in ``5.14.0`` ?

**Comment by bartoszwalacik** [comment]
no, it's the master

**Comment by azharakbar** [comment]
I am having this issue in 5.14.0 version
Please check in this version

**Comment by bartoszwalacik** [comment]
it doesn't work like that, start from upgrading to latest version of javers

**Comment by azharakbar** [comment]
Ok, got it
Our project is a starter.. We can easily upgrade

So, the latest version is 6.2.1 right
@bartoszwalacik

**Comment by azharakbar** [comment]
Hi @bartoszwalacik 
What are the above two commits for ?
Is there a bug for this ?
Thanks

**Comment by azharakbar** [comment]
@lucas-prestes
Hi,
The issue in javers#1105 is that javers.compare(..).hasChanges() has given true for 22 and 22.00, even though both have the same value

I think it would be better if you also simulate a test case in that way :-)
thank you

**Comment by bartoszwalacik** [comment]
@azharakbar it's not enought to say there is a bug, since I can't reproduce it, and if also you can't reproduce it on the latest version of Javers by pushing a failing test case - this issue will be closed

**Comment by bartoszwalacik** [comment]
@azharakbar feel free to reopen  when you come up with a failing test case
