### ISSUE TITLE
Not able to retrieve only left, right, propertyName from the Change class

### ISSUE THREAD

**Issue by azharakbar** [javers/javers#1112]
Hi,

I am using the following code to retreive the changes made to a version in my API response
```
List<Change> versionChanges = javers.findChanges(jqlQuery.build()).groupByCommit()get(0).get()
```
It gave me the following
![image](https://user-images.githubusercontent.com/10185101/122541249-0e884880-d047-11eb-8349-8ea51e799a06.png)

But I don't want this entire data to go as my API response
I just want to isolate `left`, `right`, `propertyName` in my response

I am not able to find an API on `Change.class` that can do me so ..

How can I achieve this

**Comment by bartoszwalacik** [comment]
sorry, but I don't understand you. you are asking me how to get values from a Java class?

**Comment by azharakbar** [comment]
@bartoszwalacik 
Raised it in stack-overflow 
https://stackoverflow.com/questions/68032929/retrieve-only-left-right-propertyname-from-the-javers-change-class

Thank you
