### ISSUE TITLE
[support] [spring-boot] :: Initalize JaVers manually

### ISSUE THREAD

**Issue by azharakbar** [javers/javers#1117]
Hi Team,

We have integrated JaVers to our spring boot application with ``@JaversSpringDataAuditable`` and it works like a charm!!

Now, whenever we start our app, JaVers initializes itself automatically. (Builds its own tables, sequences etc.)

But, we have a use case where we want to initialize JaVers manually so that we can control its initialization.

Is there a way to do this?

Thanks :-)

**Comment by bartoszwalacik** [comment]
What do you mean by initialize JaVers manually, creating DB tables?
If so, set the Javers `sqlSchemaManagementEnabled` property to false.

**Comment by azharakbar** [comment]
@bartoszwalacik 
Yea, have set it to false and have seen that tables are not getting created automatically.
Now, what is the function that have to be called to trigger the schema creations manually ?
Thanks

**Comment by azharakbar** [comment]
@bartoszwalacik 
Hi, please do help us with this ...

**Comment by bartoszwalacik** [comment]
table creation is done when a javers instance is created, if you want to disable it - you can, but you can't call it later
