### ISSUE TITLE
Diff for removed and then re-added list items doesn't work as expected

### ISSUE THREAD

**Issue by szymonkudzia** [javers/javers#1127]
**Bug description**
Diff for properties of type List of ValueObject doesn't work as expected. 
For items removed and then re-added with exactly the same values does not result in value changes in diff output.
For items removed and then re-added with some properties having different values then only those properties are available in diff output. 
As if re-added value was compared to value present before remove event.

**Steps To Reproduce**
https://github.com/szymonkudzia/javers/commit/3fa4827763bcba30fa4ef2c8e8ea3c2c73b4729e

**Javers' Version**
6.2.3

**Optional Feature Request**
Removal entry for list items doesn't include details meaning something opposite to addition entry where we get list of value changes per each item property from null to "actual value". I would expect to see list of value changes per each item property form "actual value" to null.

**Comment by bartoszwalacik** [comment]
thanks for reporting but this issue won't be analyzed if you don't provide a failing test case as a code on your branch - see https://github.com/javers/javers/blob/master/CONTRIBUTING.md#guidelines-for-bug-reporting

**Comment by szymonkudzia** [comment]
@bartoszwalacik forked and pushed the test
https://github.com/szymonkudzia/javers/commit/3fa4827763bcba30fa4ef2c8e8ea3c2c73b4729e

**Comment by bartoszwalacik** [comment]
Szymon, napisz prosze ten test poprawnie, tzn bez porównywania ogromnych bloków tekstu, bo nie rozumiem o co tu chodzi.

**Comment by bartoszwalacik** [comment]
Przykład dobrego testu: JaversDiffE2ETest

**Comment by szymonkudzia** [comment]
Sorry ale co mam porównywać? tworzyć ręcznie obiekty change?

Problem jest taki:
- mam entity z polem typu lista ValueObject
- jak dodaje item do listy i robię commit wszystko ok
- jak usuwam item z listy i robie commit wszystko ok
- jak dodaje dokładnie ten sam item który przed chwilą usunąłem i robie
commit *to jest nie ok* bo mam info że lista się zmieniał ale ale nie ma
szczegółów (że np name was null and now is "Adam")
- jak dodaje podobny item tzn taki który ma tylko niektóre pola różne to
wtedy dostaję szczegóły ale tylko dla tych pól które się różnią

w skrócie diff jest robiony pomiędzy eventem dodania nowego elementu a
ostatnim dodania/modyfikacji elementu na tej samej pozycji (even usunięcia
elementu z listy jest zignorowany)


czw., 12 sie 2021 o 12:20 Bartosz Walacik ***@***.***>
napisał(a):

**Comment by szymonkudzia** [comment]
Jesli odkomentujesz sobie druga assercje ktora powoduje ze test przechodzi do zobaczysz ze roznica jest tylko na 4 commit'cie

```
        Commit 4.00 done by author at 02 Aug 2021, 00:00:00 :
        * changes on org.javers.repository.sql.ListItemRemovalAndReadditionTest$Entity/1 :
          - 'values' collection changes :
             0. '...ListItemRemovalAndReadditionTest$Entity/1#values/0' added
```

to jest dokladnie taki sam event jak opisany przez Commit 2.00 dodanie pierwszego itemu do pustej kolekcji (roznica jest tylko taka ze poprzedza go even usuniecia itemu) wiec oczekiwalbym takiego samego podsumowania jak dla commitu 2.00

```
        Commit 2.00 done by author at 02 Aug 2021, 00:00:00 :
        * changes on org.javers.repository.sql.ListItemRemovalAndReadditionTest$Entity/1 :
          - 'values' collection changes :
             0. '...ListItemRemovalAndReadditionTest$Entity/1#values/0' added
          - 'values/0.name' = 'name'
```
zwroc uwage na druga zmiane w commit'cie `'values/0.name' = 'name'`

**Comment by bartoszwalacik** [comment]
zapinanie się na te bloki tekstu w asercjach jest o tyle słabe że ja nie wiem do czego Ty zgłaszasz błąd, a) do algorytmu diffa - wtedy w asercjach mają być tylko obiekty Change, czy b) do algorytmu pretty print

**Comment by szymonkudzia** [comment]
Chodzi o algorytm diff w kontekście commitow.
Diff jest robiony pomiędzy złymi commitami.

Ostatni commit (4.00) ma tylko jeden element w kolekcji changes a powinien
mieć dwa (dokładnie tak jak commit 2.00)

Nie ważne czy będę assertowal obiekty, tekst pretty print czy też zmiany
serializowane do json'a w każdym przypadku jest ten sam problem zmiana
która powinna być raportowana nie jest

czw., 12 sie 2021, 15:34 użytkownik Bartosz Walacik <
***@***.***> napisał:

**Comment by bartoszwalacik** [comment]
Szymon, kręcimy się w kółko, dalej nie rozumiem gdzie jest problem, jeśli nie jesteś w stanie napisać zwięzłego i czytelnego dla mnie testu który destyluje problem to nie pomogę Ci. Tak jak pisałem wcześniej, przykłądy jak powinny wyglądać dobre testy znajdziesz np w `JaversDiffE2ETest`

**Comment by szymonkudzia** [comment]
Updated test: https://github.com/szymonkudzia/javers/commit/99bc95c09003c636084273511294fb56d8a0f50f

**Comment by szymonkudzia** [comment]
@bartoszwalacik any updates on this?

**Comment by bartoszwalacik** [comment]
I still don't get your point. You did 4 commits

```
        javers.commit("author", entity);

        entity.values = [value]
        javers.commit("author", entity)

        entity.values = []
        javers.commit("author", entity)

        entity.values = [value]
        javers.commit("author", entity)
```

and the Javers change log is perfect:

```
[Commit 4.00 done by author at 30 sie 2021, 09:32:19 :
* changes on org.javers.repository.sql.ListItemRemovalAndReadditionTest$Entity/1 :
  - 'values' collection changes :
     0. '...ListItemRemovalAndReadditionTest$Entity/1#values/0' added
, Commit 3.00 done by author at 30 sie 2021, 09:32:18 :
* changes on org.javers.repository.sql.ListItemRemovalAndReadditionTest$Entity/1 :
  - 'values' collection changes :
     0. '...ListItemRemovalAndReadditionTest$Entity/1#values/0' removed
, Commit 2.00 done by author at 30 sie 2021, 09:32:18 :
* changes on org.javers.repository.sql.ListItemRemovalAndReadditionTest$Entity/1 :
  - 'values' collection changes :
     0. '...ListItemRemovalAndReadditionTest$Entity/1#values/0' added
  - 'values/0.name' = 'name'
, Commit 1.00 done by author at 30 sie 2021, 09:32:18 :
* new object: org.javers.repository.sql.ListItemRemovalAndReadditionTest$Entity/1
]
```

**Comment by bartoszwalacik** [comment]
I don't see any bug here

**Comment by szymonkudzia** [comment]
@bartoszwalacik no it's not fine
```
[Commit 4.00 done by author at 30 sie 2021, 09:32:19 :
* changes on org.javers.repository.sql.ListItemRemovalAndReadditionTest$Entity/1 :
  - 'values' collection changes :
     0. '...ListItemRemovalAndReadditionTest$Entity/1#values/0' added
```
you have info that something was added but what?

Look at the correct commit summary for commit 2:
```
Commit 2.00 done by author at 30 sie 2021, 09:32:18 :
* changes on org.javers.repository.sql.ListItemRemovalAndReadditionTest$Entity/1 :
  - 'values' collection changes :
     0. '...ListItemRemovalAndReadditionTest$Entity/1#values/0' added
  - 'values/0.name' = 'name'
```
there's info that something was added and details for this new item `- 'values/0.name' = 'name'`

**Comment by szymonkudzia** [comment]
@bartoszwalacik why this got closed?

**Comment by bartoszwalacik** [comment]
Szymon, dalej nie rozumiem o co Ci chodzi i to nie jest moja wina bo czytam ze zrozumieniem, nie widzę tu żadnego błędu więc zamknąłem task. Dodajesz elementy do listy i masz w change logu, że dodałeś element do listy.

**Comment by bartoszwalacik** [comment]
to `added` odnosi się do **Listy**, przyjżyj się **typom** zmian , w szczególności tu masz do czynienia ze zmianami typu **ValueAdded** i potencjalnie z **NewObject**

**Comment by szymonkudzia** [comment]
@bartoszwalacik in commit 2 and 4 I'm doing exactly the same thing, adding an item (the same item) to an empty list, then why I got two different summaries? 

what's more if instead of re-adding the same object to this list I would add Value(name = 'different name') then the summary would look something like this:
```
[Commit 4.00 done by author at 30 sie 2021, 09:32:19 :
* changes on org.javers.repository.sql.ListItemRemovalAndReadditionTest$Entity/1 :
  - 'values' collection changes :
     0. '...ListItemRemovalAndReadditionTest$Entity/1#values/0' added
  - 'values/0.name' = 'different name'
, Commit 3.00 done by author at 30 sie 2021, 09:32:18 :
* changes on org.javers.repository.sql.ListItemRemovalAndReadditionTest$Entity/1 :
  - 'values' collection changes :
     0. '...ListItemRemovalAndReadditionTest$Entity/1#values/0' removed
, Commit 2.00 done by author at 30 sie 2021, 09:32:18 :
* changes on org.javers.repository.sql.ListItemRemovalAndReadditionTest$Entity/1 :
  - 'values' collection changes :
     0. '...ListItemRemovalAndReadditionTest$Entity/1#values/0' added
  - 'values/0.name' = 'name'
, Commit 1.00 done by author at 30 sie 2021, 09:32:18 :
* new object: org.javers.repository.sql.ListItemRemovalAndReadditionTest$Entity/1
]
```

Look at the commit 4, now it has: `- 'values/0.name' = 'different name'`, why? because `different name` is different from `name` that was added in commit 2, why commit 2 matters here? because javers incorrectly picks commits for making the diff for the nested properties...

**Comment by bartoszwalacik** [comment]
nie, nie robisz tego samego w commicie 2 i 4. Wydaje mi się nie łapiesz czym są zmiany typu NewObject w kontekście JaversRepository. W commicie 2 dodałeś nowy ValueObject do JaversRepository, stąd info w logu `- 'values/0.name' = 'name'`. **temat jest zamknięty**, nie ma tu błędu, jeśli masz pytania do tego jak działa Javers, to kieruj je na stackoverflow

**Comment by bartoszwalacik** [comment]
This issue is closed, there is no bug here

**Comment by szymonkudzia** [comment]
@bartoszwalacik so are you trying to tell me that in commit 4 I'm modifying **existing item in empty collection** therefore change NewObject is not being applied here?
