### ISSUE TITLE
Changes in affectedCdo from version 6.0.0

### ISSUE THREAD

**Issue by velinovskav** [javers/javers#1130]
Hello,

I am using Javers 5.15.0 version on production environment and want to do updade to 6.2.3 version. 
During the update I noticed that there was a change in the affectedCdo (commit: https://github.com/javers/javers/commit/5d508a9205cb95575c987dc167b4187fb243f76f#)
![image](https://user-images.githubusercontent.com/10004140/129907795-be790e1f-1625-4111-8d35-5cdbb65c9b3e.png)

Is there any reason why affectedCdo was changed from right to left (first) because I haven't find any description about this change in release notes / commit message?

Thanks

**Comment by bartoszwalacik** [comment]
fixed in 6.2.5
