### ISSUE TITLE
Class not found org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer with hibernate 5.6.0.X

### ISSUE THREAD

**Issue by pethers** [javers/javers#1134]
**Clear description of my expectations versus reality**
Latest release https://in.relation.to/2021/08/27/hibernate-orm-560-beta1-release/ have dropped class org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer used in https://github.com/javers/javers/blob/master/javers-spring-jpa/src/main/java/org/javers/hibernate/integration/HibernateUnproxyObjectAccessHook.java

**Steps To Reproduce**
Update hibernate to 5.6.0.beta1 using spring jpa with hibernate.

**Javers' Version**
6.2.4

**Additional context**
Hibernate from 5.6.0+ only supports bytebuddy for class enhancements.

**Comment by pethers** [comment]
Think https://github.com/hibernate/hibernate-orm/blob/5.6.0.Beta1/hibernate-core/src/main/java/org/hibernate/proxy/pojo/ProxyFactoryHelper.java can be used.

**Comment by pethers** [comment]
Problem, proxyFactoryHelper only available from 5.3.x (https://github.com/hibernate/hibernate-orm/blob/5.3/hibernate-core/src/main/java/org/hibernate/proxy/pojo/ProxyFactoryHelper.java) . 

So changing https://github.com/javers/javers/blob/master/javers-spring-jpa/src/main/java/org/javers/hibernate/integration/HibernateUnproxyObjectAccessHook.java to use above will drop hibernate support for anything below 5.3. Would this be acceptable ?

**Comment by bartoszwalacik** [comment]
thanks for the report, I will check it

**Comment by bartoszwalacik** [comment]
Hibernate 5.3 was released in 2018 so dropping support for it seems fine

**Comment by bartoszwalacik** [comment]
luckily, dependency to `org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer` can be simply removed, see https://github.com/javers/javers/pull/1140/files

**Comment by pethers** [comment]
Thanks for fixing this, works with 6.2.5 now.

**Comment by bartoszwalacik** [comment]
fixed in 6.2.5
