### ISSUE TITLE
Javers not participate in mongodb transaction

### ISSUE THREAD

**Issue by twchiam** [javers/javers#1137]
Hi, 
Mongodb supports multiple documents transaction of multiple collections starting version 4.0, I have tested the mongodb transaction myself by persisting multiple documents from different collections with spring boot in a method that annotated with transactional annotation and it rollback all changes when exception was thrown. However, javers still able to commit it own revision changes to mongodb. Please refers to the links below for mongodb transaction and spring mongodb transaction:
https://docs.mongodb.com/manual/core/transactions/
https://www.baeldung.com/spring-data-mongodb-transactions

**Comment by bartoszwalacik** [comment]
Fixed in 6.5.1
see https://javers.org/documentation/spring-integration/#mongo-transactions
