### ISSUE TITLE
Mongo collections are not initialized

### ISSUE THREAD

**Issue by szwowo** [javers/javers#1178]
Javers version: 6.5.3

Hi,
I am using Javers with MongoDB with transactions. When I am trying to commit changes in Javers I have got an error:
```
Cannot create namespace jv_snapshots in multi-document transaction
```

To fix it I have to manually create `jv_snapshots` and `jv_head_id` collections in my database, but I am loosing all the indexes and stuff from Javers `MongoSchemaManager`

I was trying to add `@EnableMongoRepositories({"org.javers.spring.repository"})` in config file as shown in documentation but it does not work.

How to force Javers to create collections on start up?

Thank you

**Comment by bartoszwalacik** [comment]
Hi @szwowo , we do not answer questions here, try to follow the docs https://javers.org/documentation/spring-integration/#mongo-transactions or ask at Stack
