### ISSUE TITLE
API to get change history for a given property

### ISSUE THREAD

**Issue by mantithetical** [javers/javers#118]
It would be nice to provide a method to get change history of an instance id for a given property.

**Comment by bartoszwalacik** [comment]
JQL is released in javers 1.2.0
take a look at new query API and examples
http://javers.org/documentation/jql-examples/

**Comment by mantithetical** [comment]
Terrific! I will check it out.

**Comment by bartoszwalacik** [comment]
if you are using SQL DB, there is a schema migration script
