### ISSUE TITLE
Possible issue with skip value check

### ISSUE THREAD

**Issue by moussetc** [javers/javers#1183]
While reading the code, I found this snippet on`master`:
https://github.com/javers/javers/blob/f49b0aea4c371b90ada54144843e3e1eae81fe65/javers-core/src/main/java/org/javers/repository/api/QueryParamsBuilder.java#L111
```
public QueryParamsBuilder skip(int skip) {
        Validate.argumentCheck(limit >= 0, "Skip is not a non-negative number.");
        this.skip = skip;
        return this;
    }
```

Shouldn't it be `        Validate.argumentCheck(skip >= 0, "Skip is not a non-negative number.");` ?

**Comment by bartoszwalacik** [comment]
You are right,  feel free to contribute a PR with the fix
