### ISSUE TITLE
@JaversAuditable method ENTITY_INSTANCE_WITH_NULL_ID exception

### ISSUE THREAD

**Issue by afal007** [javers/javers#1185]
Calling @JaversAuditable annotated method in which object creation takes place leads to ENTITY_INSTANCE_WITH_NULL_ID exception

**Steps To Reproduce**

```
    @JaversAuditable
    public @NotNull BusinessObject save(@NotNull BusinessObject businessObject) {
        Entity toSave = mapper.map(businessObject);
        return mapper.map(dao.save(toSave));
    }
```

**Javers' Version**
6.5.3, 6.6.2

**Additional context**
```
    @JaversAuditable
    public @NotNull BusinessObject save(@NotNull BusinessObject businessObject) {
        Entity toSave = mapper.map(businessObject);
        Entity saved = dao.save(toSave);
        businessObject.setId(saved.getId());
        return mapper.map(saved);
    }
```
Works like this, but looks like wrong logic to audit the object from parameters and not return value

**Comment by bartoszwalacik** [comment]
@JaversAuditable persists method's args **after** the method is executed. Does your arg  - `BusinessObject businessObject` has an Id set? Looks like it doesn't because you are persisting another object. In that case it would be better to call javers.commit() explicitly.
