### ISSUE TITLE
Incorrect auditing data on distributed environment with Spring Boot, Javers, MongoDB

### ISSUE THREAD

**Issue by abhinavDCT** [javers/javers#1187]
**Clear description of my expectations versus reality**
Incorrect auditing data gets generated when the same database object is updated from different servers. 

Example - We update a particular database object from server 1 (Request 1) and update the same from server 2 (Request 2) and then again from server 1 (Request 3).

We expect the last generated audit data to be the diff between the resulting document after Request 3 and Request 2 but the last audit data generated is diff between the resulting document after Request 1 and Request 2.

We are using Javers with our Spring Boot application and MongoDB with the default configuration. We have two instances of the Spring Boot application.

**Steps To Reproduce**
I did not write any runnable test cases as I am not aware of how to write Javers test cases for distributed environments (any pointers would be helpful here).

The issue is easy to recreate and I think it is because of inconsistent cache. Here are two scenarios that create inconsistent auditing data. 

Let's assume we are updating a MongDB document - UserDocument, which is also used for Authentication and is audited by Javers.

1. Scenario 1
- Request 1: Update the document by sending a request to the first server.
- Request 2: Update the same document by sending a request on the second server.
- Request 3: Update the same document again by sending a request on the first server.
- Result: The last audit data generated will be the diff of data updated after request 1 and request 3, whereas the expected behavior is the diff of data updated after request 2 and request 3.

2. Scenario 2 - when using the default Javers implementation of getting author with Spring Security
- Request 1: Update the document by sending a request to the first server.
- Request 2: Update the same document by sending a request on the second server.
- Request 3: Send a login request to the first server which fetches the document updated in the above requests.
- Result: The last audit data generated will have **anonymous** as the author of the changes and the auditing data will be the same as generated after request 2.

**Javers' Version**
6.0.5*

**Additional context**
Currently, I am using **javers.snapshotsCacheSize**: 0 as a temporary fix.
I can create a minimal Spring Boot Application that could be used to recreate this issue in a distributed environment if required.

Thanks

**Comment by bartoszwalacik** [comment]
Hi, this issue looks like a duplicate to https://stackoverflow.com/questions/71110093/how-to-keep-javers-cache-consistent-in-distributed-environment

You are right about that local caches could lead to consistency problems in a distributed env.  Setting `javers.snapshotsCacheSize: 0 is a good workaround`. If you are eager to contribute a PR to javers with distributed cache integration (like memcache) - we can talk about [here](https://github.com/javers/javers/discussions). I doubt if memcache would really speed things up. First we have to measure the performance impact with and without memcache and proof this feature is worth being implemented.
