### ISSUE TITLE
MongoDB indexes are not created when used via Spring Boot

### ISSUE THREAD

**Issue by Cimballi** [javers/javers#1192]
**Clear description of my expectations versus reality**

MongoDB indexes are not created when used via Spring Boot. If I configure JaVers manually then the MongoDB indexes are created.

**Steps To Reproduce**

Configure JaVers with MongoDB via Spring Boot, start the project, indexes are not created (only the _id index is created in fact).

**Javers' Version**

Tested with version 6.6.2 and Spring Boot 2.6.3

**Additional context**

**Comment by stephanecottin** [comment]
same here

**Comment by bartoszwalacik** [comment]
thanks for reporting, seems like this bug was introduced in 6.5.1

**Comment by bartoszwalacik** [comment]
fixed in 6.6.4

**Comment by stephanecottin** [comment]
> fixed in 6.6.4

Thanks !
