### ISSUE TITLE
Is it possible to add the Javers annotation dynamically

### ISSUE THREAD

**Issue by mensunm** [javers/javers#1194]
Instead of hardcoded the annotation JaversSpringDataAuditable & @JaversAuditable in a class level, is it possible to  add the annotations dynamically either read from db config or properties configurations. 
How to dynamically add the @Diffignore dynamically read from the database or properties. Appreciate if any examples.

Thanks in advance.

**Comment by bartoszwalacik** [comment]
There is no such option and I dont plan to add it. Btw what is yous use case? Why you dont want to use annotations?

**Comment by mensunm** [comment]
Thanks for your reply.
Instead of hardcoding annotations at class level would like to use the annotations dynamically.
Use case - The auditing should be using a dynamic configuration, so that entities are audited or specific fields in an entity are audited read from that db configuration and add the annotations dynamically.  The entities/fields which needs to be audited are stored in the DB.

**Comment by bartoszwalacik** [comment]
I disagree, auditing config (Javers' annotations) should be close to audited Entities and Repositories. Thanks to that both things are aligned and easy to manage.
