### ISSUE TITLE
Comparing objects which have nested objects as properties leads to wrong results

### ISSUE THREAD

**Issue by eternalconcert** [javers/javers#1216]
When having two objects of which one has a child object, JaVers is not able to recognize the difference,
    when the properties of the child object have the same values as the corresponding default value in
    org.javers.common.collections.Defaults
    The first test ends successful, because the child Item has the value property `1`, which differs from the default
    in Defaults (0).
    The second test fails, because the child Item has the value property `0`, which is the same as the default in
    Defaults (0).
    In both tests the itemParentA, which has a child Item is compared to the itemParentB, which has no child Item.
    Please ensure, that removed nested objects are removed properly. I think the Problem is the FakeNode which uses the
    defaults from Defaults in the methods getDehydratedPropertyValue and getPropertyValue.
    The behaviour can be reproduced with other data types.
...

**Steps To Reproduce**
I have a **runnable test case ** which isolates the bug and allows Javers Core Team to easily reproduce it. I have pushed this test case to my fork of this repository:

https://github.com/postadress/javers/commit/4cd68a13a1137fdb9dbf0d5daa3f7a80ed805f7c

I also created a pull request.

**Javers' Version**
6.6.5

**Additional context**
...

**Comment by bartoszwalacik** [comment]
https://github.com/javers/javers/pull/1215

**Comment by eternalconcert** [comment]
I updated my fork with a new config parameter, to address this issue. Please review and merge my pull request.

**Comment by bartoszwalacik** [comment]
fixed in 6.7.0
