### ISSUE TITLE
Partial and case-insensitive search for Author and Commit Property

### ISSUE THREAD

**Issue by krisztaa0404** [javers/javers#1223]
**Is your feature request related to a problem? Please describe.**
Currently there is no option to search for an author by only providing a part of the username. The correct result set will be only returned if the exact username is provided. Commit property offers partial search, but it's sensitive for lowercase and uppercase letters.

**Describe the solution you'd like**
I would like to implement partial and case insensitive search for both author and commit property value fields.
eg. `byAuthorLikeIgnoreCase`, `byCommitPropertyLikeIgnoreCase`

**Describe alternatives you've considered**
None

**Additional context**
 I would like to contribute by creating a pull request, let me know what you think about the request.

**Comment by bartoszwalacik** [comment]
Hi @krisztaa0404 , that's a good idea, feel free to contribute a PR

**Comment by krisztaa0404** [comment]
#1224 Pull request created for issue

**Comment by bartoszwalacik** [comment]
released in 6.8.0, thanks @krisztaa0404  👍
