### ISSUE TITLE
Container changes have little to no information when an element changes

### ISSUE THREAD

**Issue by derklaro** [javers/javers#1226]
**Is your feature request related to a problem? Please describe.**
At the moment when creating a diff between two objects and a change in a collection/array was made, there is no way to get proper information about the changed list nor the changed element. While the change information contains info about the index, the affected object and the property, it is very fiddly to extract both lists from the original and new object, get the changed index and create a diff between those two.
This makes it very hard for me to pretty print a change (for example to ask if the old or new version of the element should be used). 

**Describe the solution you'd like**
The best solution would be to be actually able to access the changed objects or a diff between the objects (although if the objects are present it would be easy to create the diff myself). Currently I can only get object ids from the change which contain no usable information.

**Describe alternatives you've considered**
As mentioned above, I could fiddle around with the original and changed object, extract the property, get the index of both collections and create a diff between those.

**Additional context**
I didn't check if changes to maps have the same issue, if so it would be nice to get the same sort of accessibility to that change as well :)

**Comment by bartoszwalacik** [comment]
sorry, but your complain is too generic, both version of a list are available explicitly in ContainerChange :

```
    /**
     * Right (or new) Collection or array
     */
    @Override
    public T getRight() {
        return right;
    }

    /**
     * Left (or old) Collection or array
     */
    @Override
    public T getLeft() {
        return left;
    }
    ```

**Comment by derklaro** [comment]
So I just double checked if I made a mistake, but for me the collections are not available from the container change. The getRight/getLeft methods only return a collection with object ids, not with the actual collection that changed:
![image](https://user-images.githubusercontent.com/40468651/196389110-3d1a6b78-6d9e-4623-bfb0-34270e8306b6.png)

Maybe there is a way to convert the ValueObjectId back to the object it came from, but I found no such way yet.
