### ISSUE TITLE
HELP - Custom property save

### ISSUE THREAD

**Issue by mandeerson** [javers/javers#1227]
I have an object like this.

```
public class User {
    private Integer id;
    private String name;
    private Custom custom;

    public class Custom {
        private Integer id;
        private String name;

        @Override
        public String toString() {
            return name;
        }
    }
}
```

I need to save the property **custom** as to string to only store the actual name of Custom class. 

Is it possible? 

I tried to save as ShallowReference, but the result is not as I expected.

**Comment by bartoszwalacik** [comment]
see https://javers.org/documentation/repository-configuration/#custom-json-serialization

**Comment by mandeerson** [comment]
Tks.

But if I use the typeadapter like this.

```
    @Bean
    public JaversBuilderPlugin customizeJavers() {
        return javersBuilder -> javersBuilder.registerValueTypeAdapter(new CustomAuditAdapter());
    }
```

The entity **Custom** in this example is an instance of `HibernateProxy` and the Javers proxy `HibernateUnproxyObjectAccessHookis`  not load entity and throws the exception:

`Attempted to serialize java.lang.Class: org.hibernate.proxy.HibernateProxy. Forgot to register a type adapter?`
