### ISSUE TITLE
No qualifying bean of type 'org.javers.core.Javers' available: expected at least 1 bean which qualifies as autowire candidate

### ISSUE THREAD

**Issue by ajay185** [javers/javers#1239]
I have updated my Springboot version to 3.0.0. After upgrading, I'm seeing an error:- No qualifying bean of type 'org.javers.core.Javers' available: expected at least 1 bean which qualifies as autowire candidate.

with version 2.7.6 its working fine.

I have created a auditService where Javer has been introduced like:

@Autowired
  private final Javers javers;

**Comment by bartoszwalacik** [comment]
duplicate to 
https://github.com/javers/javers/issues/1238
