### ISSUE TITLE
Spring Boot override auto configuration with JaversBuilderPlugin causes StackOverflowError

### ISSUE THREAD

**Issue by steghio** [javers/javers#1245]
Hello and thank you for this project,

we are trying to move of of Envers to Javers and we have an old data model which is not 100% following DDD style where some child entities are explicitly declared with their own ID in their own table, rather than leaving it up to Hibernate persistence to handle automagically.

I have an entity `PostalAddress` which has a field defined as list of `AddressComponent`, which in turn has a field `AddressComponentDefinition`. All those classes are annotated with `@Entity` in our model.

If I let Javers auto determine the Javers types for those classes, it will treat all of them as entities:

```
EntityType{ baseType: 'class app.model.PostalAddress', id: '['recordId']' }
EntityType{ baseType: 'class app.model.AddressComponent', id: '['id']' }
EntityType{ baseType: 'class app.model.AddressComponentDefinition', id: '['id']' }
```

This means that the query for changes:

`QueryBuilder.byInstanceId(address.getRecordId(), PostalAddress.class).withChildValueObjects()`

will not include those child entities.

If I annotate instead the two child classes as `@ValueObject`, I will see them in the list of changes. However, their structure is complex and the diff should be done following some specific logic and not simply by comparing properties. I created a custom property comparator `AddressComponentComparator` which should implement such logic and need to register it.

I am using Spring Boot starter, so everything is autoconfigured for me, if I create the Javers bean with the `JaversBuilder`:

```
JaversBuilder.javers()
                .registerEntities(PostalAddress.class)
                .registerCustomType(AddressComponent.class, new AddressComponentComparator())
                .registerValueObjects(AddressComponentDefinition.class)
                .build();
```

I will not be able to retrieve any change since all the autoconfiguration is lost. I then tried to override the autoconfiguration using `JaversBuilderPlugin` to register my custom comparator only:

```
@Bean
    JaversBuilderPlugin customizeJavers() {
        return javersBuilder -> javersBuilder.registerCustomType(AddressComponent.class, new AddressComponentComparator());
    }
```

And this is when I get StackOverflowError when Javers bean is created for the first time:

```
java.lang.StackOverflowError
	at com.google.gson.internal.LinkedTreeMap$Node.<init>(LinkedTreeMap.java:459)
	at com.google.gson.internal.LinkedTreeMap.find(LinkedTreeMap.java:169)
	at com.google.gson.internal.LinkedTreeMap.put(LinkedTreeMap.java:97)
	at com.google.gson.JsonObject.add(JsonObject.java:57)
	at com.google.gson.internal.bind.JsonTreeWriter.put(JsonTreeWriter.java:79)
	at com.google.gson.internal.bind.JsonTreeWriter.beginArray(JsonTreeWriter.java:96)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:95)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:157)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:287)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:157)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:287)
	at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:1153)
```

Of course I could just get the shadows of this entity and do the diff myself, but if possible I'd like to use Javers directly since for other simple fields it's actually providing the correct diff already.

**Steps To Reproduce**

You can run the `JaversTest.javersDiff()` test case which will show the exception. If you comment out the bean creation in class `JaversConfiguration` you will see it working correctly (but not using my custom comparator)

I provide Java code, we are using Java 11, you can find the sample project and test here: https://github.com/steghio/javerserror we build with Maven

**Javers' Version**
6.8.1

Thank you in advance and happy holidays

**Comment by bartoszwalacik** [comment]
Hi @steghio , thanks for reporting, definitely JaversBuilder should not throw `StackOverflowError`. To make our work here easier please try to follow https://github.com/javers/javers/blob/master/CONTRIBUTING.md#guidelines-for-bug-reporting
and come up with a failing test case. You can push it to your fork of this repo.

**Comment by steghio** [comment]
Hello and thanks for the quick reply,

any chance we can use the java repo I provided? There is everything setup there including the test. It will take quite some time to reproduce the whole setup in your groovy project and this issue is coming from using Spring Boot autoconfiguration as well which is not used in yours

Thanks and cheers

**Comment by steghio** [comment]
Ok I didn't see the edit, I will try in the SQL module, thank you

**Comment by bartoszwalacik** [comment]
Please take a look at existing tests, shouldn't be hard to add a new one.
You can use your project to identify the bug, once it's done, the new test case must be created in this repo alongside the fix. 
This is OSS project , so if you want it fixed you are supposed to contribute :)

**Comment by steghio** [comment]
If entities have circular references, Javers would normally handle them properly when allowed to infer types from annotations, however the customization of the builder will somehow break this and generate the exception.

Solution is to annotate one direction of the reference with `@DiffIgnore` (in any case for auditing you would only consider one tree structure rather than a graph)

**Comment by bartoszwalacik** [comment]
thanks @steghio
