### ISSUE TITLE
Map numeric data value in Object type to proper data type instead of GSON's default double data type

### ISSUE THREAD

**Issue by madhavjha-git** [javers/javers#1252]
**Is your feature request related to a problem? Please describe.**
GSON by default maps any numeric value defined in Object type to Double. 
Same problem is inherited by Javers as it uses GSON under the hood. 

GSON provided the solution for it long back. Javers should adopt it for better results with shadow api. 
https://github.com/google/gson/pull/1290
 
Example:
```
class TypeValue{
    Integer id;
    Object value;
}
```

> Json: 
>         var jsonStr="{\n" +
>                 "    \"id\":1,\n" +
>                 "        \"value\":9999999999\n" +
>                 "        }";

_**Result without setObjectToNumberStrategy(ToNumberPolicy.LONG_OR_DOUBLE)**_
```
        Gson gson= new GsonBuilder()
               // .setObjectToNumberStrategy(ToNumberPolicy.LONG_OR_DOUBLE)
                .create();
        var json=gson.fromJson(jsonStr,TypeValue.class);
```

_{
    "id": 1,
    "value": 9.999999999E9
}_		

_**Result with setObjectToNumberStrategy(ToNumberPolicy.LONG_OR_DOUBLE)**_
```
        Gson gson= new GsonBuilder()
                .setObjectToNumberStrategy(ToNumberPolicy.LONG_OR_DOUBLE)
                .create();
      var json=gson.fromJson(jsonStr,TypeValue.class);
```
_{
    "id": 1,
    "value": 9999999999
}_	

**Describe the solution you'd like**
Adding this should solve it. 

    public JsonConverterBuilder() {
        this.gsonBuilder = new GsonBuilder();
        this.gsonBuilder.setExclusionStrategies(new SkipFieldExclusionStrategy());
  

>       this.gsonBuilder.setObjectToNumberStrategy(ToNumberPolicy.LONG_OR_DOUBLE);

        registerBuiltInAdapters(Java8TypeAdapters.adapters());
        registerBuiltInAdapters((List)UtilTypeCoreAdapters.adapters());
        registerJsonAdvancedTypeAdapter(new OptionalTypeAdapter());
    }

**Describe alternatives you've considered**

**Additional context**

**Comment by bartoszwalacik** [comment]
Hi @madhavjha-git, feel free to contribute a PR

**Comment by madhavjha-git** [comment]
Hi @bartoszwalacik  raised PR https://github.com/javers/javers/pull/1280 for the same.

**Comment by bartoszwalacik** [comment]
release in 6.13.0, @madhavjha-git thanks for your high quality contribution
