### ISSUE TITLE
Feature: HEAD collection name should be configurable

### ISSUE THREAD

**Issue by egasimov** [javers/javers#1254]
**Is your feature request related to a problem? Please describe.**
There is no option to configure the collection name of the jv_head_id. So if multiple microservices are writing in multiple collections in that database all services are using the same jv_head_id.

**Describe the solution you'd like**
Make it configurable which collection name should be used

**Describe alternatives you've considered**
none

**Additional context**
There was an similar ticket but with making SNAPSHOT COLLECTION configurable, https://github.com/javers/javers/issues/1169, and already merged.

P:S I would like to contribute by creating an pull request.

**Comment by egasimov** [comment]
Hey @bartoszwalacik! I have just made PR for issue described above, could you please review and share your thoughts, whenever have time?

**Comment by mmushfiq** [comment]
I would also appreciate having this feature available. After that, we can use it.

**Comment by bartoszwalacik** [comment]
released in 6.9.1
