### ISSUE TITLE
Feature: Enable schema management check via config for JaversMongoRepositories

### ISSUE THREAD

**Issue by egasimov** [javers/javers#1260]
**Is your feature request related to a problem? Please describe.**
When using Javers in projects backend by MongoDB, javers-mongo-repository module trying to create indexes on the collection. (via calling [ensureSchema()](https://github.com/javers/javers/blob/db143447f202677f00e8c9109018a477a78a4ea5/javers-persistence-mongo/src/main/java/org/javers/repository/mongo/MongoSchemaManager.java#L50)). In our projects, the app-user usually do not have such permissions(create index) on database.
These internal used collections and indexes are considered to be created by Ops team. 

**Describe the solution you'd like**
I would like to javers-mongo-repository module having option to configure schema management like javers-sql-repository module did

**Describe alternatives you've considered**
An alternative to create CustomMongoSchemaManager that extends [MongoSchemaManager](https://github.com/javers/javers/blob/db143447f202677f00e8c9109018a477a78a4ea5/javers-persistence-mongo/src/main/java/org/javers/repository/mongo/MongoSchemaManager.java) inject it into where used in library via reflection. But it is no so good option to consider.

**Additional context**
There is option to configure "enable schema management" in Javers SQL Repository module (see [SqlRepositoryConfiguration.java](https://github.com/javers/javers/blob/master/javers-persistence-sql/src/main/java/org/javers/repository/sql/SqlRepositoryConfiguration.java#L28)).

**Comment by mmushfiq** [comment]
We also faced the same situation. Let's wait response)

**Comment by egasimov** [comment]
Hey @bartoszwalacik,
I have just created [PR](https://github.com/javers/javers/pull/1261) for addressing above feature and would also like to get feedback from you. Thanks!

**Comment by bartoszwalacik** [comment]
thanks @egasimov , see my comment on the PR

**Comment by egasimov** [comment]
@bartoszwalacik Sure. I've made [few changes](https://github.com/javers/javers/pull/1261),  Could you please re-review it again ?

Thank you for your time.

**Comment by mehdiyevcs** [comment]
Faced same issue, while integrating. Would appreciate having ability to control behavior via config file

**Comment by bartoszwalacik** [comment]
released in 6.10.0
