### ISSUE TITLE
Problem with inheritance?

### ISSUE THREAD

**Issue by bfeater** [javers/javers#127]
I tried out JaVers (version 1.1.0), but encountered a problem. Comparing a property with a value of different subclasses leads to an IllegalArgumentException. Is this intended behaviour?

Example to reproduce the exception:

```java
   class Example {
      class Holder {
         A a;
      }

      class A {}

      class B0 extends A {
         String b0 = "asdf";
      }

      class B1 extends A {
         String b1 = "qwer";
      }

      public void doesNotWork() {
         Javers javers = JaversBuilder.javers().build();

         Holder first = new Holder();
         first.a = new B0();
         Holder second = new Holder();
         second.a = new B1();

         Diff diff = javers.compare(first, second);
      }
   }
```

**Comment by bartoszwalacik** [comment]
Looks like a bug, will check it out

**Comment by bartoszwalacik** [comment]
There is no bug here, but indeed, error message is misleading. It will be fixed in the next release to TYPE_MISMATCH error

What you are doing here is comparing objects with different types.
You cannot compare B0 instance with B1 instance because they have different fields.

Field `String b0` is not connected to `String b1` despite the same type (`String`).
It will work only if you abstract the field definition to A class

**Comment by bfeater** [comment]
Do you really mean that? Perhaps another example will make the problem clear


class Store {
  List<Bicycle> bicycles;
}

class Bicycle {
  int speed;
}

class Mountenbike {
  int seatHeight;
}

...
Store store0 = new Store();
store0.bicycles = new ArrayList<>();
store0.bicycles.add(new Bicycle());

Store store1 = new Store();
store1.bicycles = new ArrayList<>();
store0.bicycles.add(new Mountenbike());


Comparing store0 with store1, I would expect a ListChange with a removal
of a Bicycle and an addition of a Mountenbike. But in the current
implementation of JaVers I get an exception.



Am 20.03.2015 um 23:08 schrieb Bartosz Walacik:
> There is no bug here, but indeed, error message is misleading. It will be fixed in the next release to TYPE_MISMATCH error
> 
> What you are doing here is comparing objects with different types.
> You cannot compare B0 instance with B1 instance because they have different fields.
> 
> Field `String b0` is not connected to `String b1` despite the same type (`String`).
> It will work only if you abstract the field definition to A class
> 
> 
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/javers/javers/issues/127#issuecomment-84166723
> 


-- 
Sebastian Gebhardt
Email: sebastian.gebhardt@bfeater.de
PGP-Public Key: http://www.bfeater.de/bfeater_pubkey.asc

**Comment by bartoszwalacik** [comment]
Could you please push a mini-project to github  with a failing test?

**Comment by bfeater** [comment]
I have created a small example. In the test I have added a comment with my expected result.

https://github.com/bfeater/javers_inheritance_test

**Comment by bartoszwalacik** [comment]
ok, will take a look

**Comment by bartoszwalacik** [comment]
in the 1.1.2-SNAPSHOT, you will get better exception desc:

`JaversException: TYPE_MISMATCH JaVers runtime error - Looks like you are comparing two objects with different types. There is no property 'seatHeight' in type 'Bicycle'.`

the clue is the same, we don't know how to compare Bicycle with Mountainbike.
If the number of gears (common field) is different, that is clear that objects are different.
But what if the number of gears would be equal? Does it mean that objects are equal? Not sure ...

**Comment by bartoszwalacik** [comment]
In fact, when you start adding fields to a subclass, it's not possible to write valid equals(), without breaking Liskov Principle. Try to write a valid equals() for both classes (Bicycle with Mountainbike), I mean reflexive, symmetric, transitive and consistent. Imho it's not possible.

**Comment by bartoszwalacik** [comment]
I can think about simple solution, when comparing two ValueObjects, Javers would say *not equals* if these two objects have different number of fields. What do you think about that? Would it solve your issue?

**Comment by bfeater** [comment]
In my opionion both equals() methods (Bicycle and Mountainbike) are correct. When the objects are not of the same class, equals() returns false. And I think Javers should behave in the same way. Objects of different classes - also they have equals global ids - cannot be equals.

**Comment by bartoszwalacik** [comment]
In fact, JaVers doesn't use users' equals() methods for ValueObjects. JaVers compares ValueObjects field-by-field. Personally I prefer using `instanceof` instead of getClass(), as it does less harm to Liskov Principle. But it does realy matter here

I can change ValueObject comparing algorithm in that way, that it would retrun false when both object have different set of properties. This would solve your case as Bicycle and Mountainbike have different fields. What do you think about it?

**Comment by bfeater** [comment]
Sure, this would solve my problem.

But in case someone wants to compare two objects having different
classes but same set of properties, he would ran into the same problem.
So I would really suggest to compare the classes of two value objects.
When the classes are equal, it's guaranteed that both objects have the
same set of properties.

**Comment by bartoszwalacik** [comment]
dont worry, new impl would be type-safe

concrete class should not matter, think of a simple example:
`new ArrayList().equals( Collections.emptyList() )`
gives true, despite that both object have different classes

**Comment by bgalek** [comment]
our plan:

1) chcek if both objcets are from the same hierarchy (instance of) 
2) check if field count is equal - then it's a valid comparison in other case - return false

**Comment by bartoszwalacik** [comment]
https://github.com/javers/javers/pull/153

**Comment by bartoszwalacik** [comment]
done & released, see v 1.2.1

**Comment by heroInCommunity** [comment]
@bgalek please tell, if second option will work when field count is different, however \@DiffIgnore was used?
See my question https://stackoverflow.com/questions/50527145/compare-objects-of-child-and-parent-classes-in-javers .

**Comment by bgalek** [comment]
@bartoszwalacik will know the implementation details ;)

**Comment by bartoszwalacik** [comment]
I will answer this question at stack
