### ISSUE TITLE
MongoDB transactions when using a second database to store changes

### ISSUE THREAD

**Issue by Trokoz** [javers/javers#1273]
I am using Javers Spring Boot Starter in my project. When using one database to store data and changes, everything works correctly. But if you specify a separate database for storing changes in the Javers Spring Boot Starter settings, an error occurs. As I understand it, it is connected with the fact that one MongoTransactionManager is used, and a separate one must be created for the database that stores the changes. I have tried to have the Javers use a different MongoTransactionManager, however, in this case, the transactions are unrelated.
Is there any plan to add some kind of mechanism (like Atomikos) that allows transactions while using a separate database to store changes?

**Comment by bartoszwalacik** [comment]
Hi , you mean a technology like two phase commit for distributed transactions? Not in our backlog. You can research how complex would it be , maybe there is some support in Spring for it? I guess it won't be easy. Closing the issue for now, feel free to reopen if you are eager to do the research and  contribute a PR
