### ISSUE TITLE
Using deprecated '-debug' fallback for parameter name resolution

### ISSUE THREAD

**Issue by halexiev-hedgeserv** [javers/javers#1279]
**Is your feature request related to a problem? Please describe.**
Javers code is currently compiled with the old '-debug' compiler flag which leads to following warning at runtime with spring:

Using deprecated '-debug' fallback for parameter name resolution. Compile the affected code with '-parameters' instead or avoid its introspection: org.javers.spring.auditable.aspect.JaversAuditableAspect

**Describe the solution you'd like**
As the warning suggests the code should be compiled with the newer '-parameters' flag.

**Describe alternatives you've considered**
This is warning currently, but in future versions of Spring this will error as the parameter name discoverer class (org.springframework.core.LocalVariableTableParameterNameDiscoverer) parsing the '-debug' compiled code will be removed.

**Comment by bartoszwalacik** [comment]
sorry but where exactly this flag is switched on in our build process?

**Comment by halexiev-hedgeserv** [comment]
Good question. I looked around a bit and could not find it in the code, but I assume it's something that you get by default. Maybe it's worth trying setting explicitly the '-parameters' flag which should in theory replace the '-debug'.

**Comment by halexiev-hedgeserv** [comment]
From logs at runtime :)

**Comment by bartoszwalacik** [comment]
Are you going to contribute a PR?

**Comment by loowps** [comment]
@bartoszwalacik according to https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Versions 6.1 will be released this november where the deprecated LocalVariableTableParameterNameDiscoverer will be deleted.

**Comment by bartoszwalacik** [comment]
fix will be available tomorrow in 7.3.5
