### ISSUE TITLE
Changes of a set of entities

### ISSUE THREAD

**Issue by igler** [javers/javers#128]
Currently I get the changes (limited by 10) of a certain entity (location) by calling...
<pre><code>javers.getChangeHistory(InstanceIdDTO.instanceId(location.getId(), Location.class), 10);
</code></pre>

Is there a way to get all changes of all locations (also with limit and maybe ordered by date)?

**Comment by pawelszymczyk** [comment]
Currently Javers hasn't suitable method in api, i think this issue is corresponded with: #36

**Comment by bartoszwalacik** [comment]
JQL is released in javers 1.2.0
take a look at new query API and examples
http://javers.org/documentation/jql-examples/

**Comment by bartoszwalacik** [comment]
if you are using SQL DB, there is a schema migration script
