### ISSUE TITLE
Moving properties from one to another Entity - java.lang.IllegalArgumentException: argument should not be null

### ISSUE THREAD

**Issue by gladkate** [javers/javers#1286]
Hello,
I have been using Javers for 2 years in the project. Currently, I have a requirement to move a couple of fields from Entity X and Entity Y to the newly created Entity. Entity X and Y have @TypeName annotation and they are tracked by using @JaversSpringDataAuditable annotation on the repositories' level. Some of the properties that I moved from Entity Y had @PropertyName annotation. In the code I am using findChanges query, where I build query by classes - I use there Entity X, Y, and other related classes, but adding entity X causes the issue that the argument should not be null. I guess this is because I deleted some properties from that entity.

Maybe this is not a common requirement, but it happens that we need to extract the data from the too big Entity. 

What can I do now? I do not want to lose previous tracks.

I am using the 6.2.5 version, but I tried the newest (6.12.0) and it did not change anything.

**Comment by bartoszwalacik** [comment]
sorry but I don't fully understand your question , what does it mean to extract the data from the too big Entity? btw issues are for bug reports and feature requests, see https://github.com/javers/javers/blob/master/CONTRIBUTING.md#issues

**Comment by gladkate** [comment]
to extract the data from the too big Entity means that I have an entity X:

@Entity
@Typename("X")
public class X {
private String a;
@PropertyName("b")
private String b;
//some other fields 
}

And I have an entity Y: 


@Entity
@Typename("Y")
public class Y {
private String c;
@PropertyName("d")
private String d;
//some other fields 
}


And now I moved fields (columns) a,b,c and d to a new table (Entity) and I deleted them from an entity X and Y:

@Entity
@Typename("Z")
public class Z {
private String a;
@PropertyName("b")
private String b;
private String c;
@PropertyName("d")
private String d;
}

then I am looking for changes in these classes for specified commit ids:

Changes changes =
        javers.findChanges(
            QueryBuilder.byClass(
                   X.class, 
                   Y.class, 
                   Z.class)
                .withChildValueObjects()
                .withCommitIds(commitIds)
                .build());

Class X causes the error (this is a parent class for the others): argument should not be null
Sorry, but I am not sure yet if this is a bug or a feature - from my perspective, it is a bug because as I checked other issues it should be possible to delete properties from the entity, and finding changes should still work. And apparently, this is a problem that I deleted some fields from an entity and they are still in Javers' tables
