### ISSUE TITLE
@DiffIgnoreProperties prevents @ValueObject and other type annotations from being detected

### ISSUE THREAD

**Issue by kirmerzlikin** [javers/javers#1287]
**Clear description of my expectations versus reality**
*Expectation:* having annotation `@DiffIgnoreProperties` on your class does not affect the JaversType resolution for said class.
*Reality:* with `@DiffIgnoreProperties` on your class, no type annotations (e.g. `@ValueObject`, `@Entity`) will be recognized, which may affect JaversType resolution (in case the deduced type differs from the one declared via the type annotation).

**Steps To Reproduce**
I have a runnable test case which isolates the bug and allows Javers Core Team to easily reproduce it. I have pushed this test case to my fork of this repository:

https://github.com/kirmerzlikin/javers/tree/diff-ignore-properties-bug/javers-core/src/test/groovy/org/javers/core/cases/Case1287ValueObjectWithIgnoredProperties.groovy

**Javers' Version**
7.0.0

**Additional context**
This bug is caused by the change made in scope of PR #1267 that introduced the annotation `@DiffIgnoreProperties` (initially called `@DiffIgnoreFields`) to JaVers. In that PR this annotation [was added](https://github.com/javers/javers/pull/1267/files#diff-fa0df27bd3d8db480b04c6f40ee2c9b3b2893188c8004a084df31c451aa10e26) to the list of annotations detected by `ClassAnnotationsScanner` which are supposed to declare a class as a certain JaversType. Since only first of the found annotations from that list is used, and since `@DiffIgnoreProperties` appears early in that list, it prevents other annotations from being recognized. The problem here is that `@DiffIgnoreProperties` shouldn't be in that list at all, since it's not meant to be an indicator of a JaversType.

I have [a fix](https://github.com/javers/javers/commit/df0815059da166f8f47ec803099412f6018d40d6) for this bug in the branch [`diff-ignore-properties-fix`](https://github.com/kirmerzlikin/javers/tree/diff-ignore-properties-fix) of my fork and will be happy to submit a PR here.

**Comment by bartoszwalacik** [comment]
hi @kirmerzlikin , thanks for a high quality bug report and a possible fix, could you please create a PR?

**Comment by kirmerzlikin** [comment]
hi @bartoszwalacik, did you have a chance to take a look at [the PR](https://github.com/javers/javers/pull/1289)?

**Comment by bartoszwalacik** [comment]
Hi @kirmerzlikin , sorry for the delay, I will take a look at this in this week
