### ISSUE TITLE
Introduce BOM for managing Javers version in a unified way

### ISSUE THREAD

**Issue by orange-guo** [javers/javers#1291]
as the title, Introduce a BOM (Bill of Materials) to manage javers version, to ensure that all modules in the project use the same Javers version, thus avoiding build and deployment issues caused by conflicts between different versions. This can also simplify the management and upgrading process of project dependencies.

**Comment by bartoszwalacik** [comment]
never heard about BOM, could you please link to that tool an explain which concrete problem does it solve? Where are these conflicts? Please reopen then
