### ISSUE TITLE
Support spring TypeAlias annotation for MongoDB documents

### ISSUE THREAD

**Issue by Tobisaninfo** [javers/javers#1296]
Hi,

When using javers with mongodb and spring boot, it is amazingly easy to integrate auditing. I have seen in the MongoDB jv_snapshots in fields like globalId_key it uses the complete package and class name to identify the objects. In cases of refactoring, the information is corrupted. 

In spring is the opportunity to define an alternative name with the @TypeAlias("customName")  at the class level of the document class, that replaces the default package name and class name for identification. As far as I can see, javers does not evaluate this annotation. Is there any option to replace the default package and class name with some custom name to be robust for refactoring?

Here is an example using the annotation:

```java
@TypeAlias("address")
public class Address {
    ...
}
```

This results in the MongoDB to the following document:

```json
{
   "_id": "...",
    ...
   "_class": "address"
}
```

Thank you for your time

**Comment by egasimov** [comment]
Hey @Tobisaninfo , 
If I understood correctly, decorating the entities with the following annotation will resolve the issue.

`@org.javers.core.metamodel.annotation.TypeName(value = "customName")`

**Comment by Tobisaninfo** [comment]
Hi @egasimov

that is exactly I was looking for. Thank you very much for your fast response.
