### ISSUE TITLE
Javers cannot authenticate in Mongo after updating to Spring Boot 3.1

### ISSUE THREAD

**Issue by RaGreen** [javers/javers#1300]
**Clear description of my expectations versus reality**
After updating Spring Boot 3.0.7 to 3.1.0 Javers for Mongo stopped working - all the time autorization is failed. Problem must be in Javers Mongo Support, because downgrade fixes the problem.

Only thing in Spring changelogs that may be connected to it is deprecting "MongoPropertiesClientSettingsBuilderCustomizer" or updating to Spring Data Bom 2023.0.0 (part of update is updating MongoDB (org.mongodb:mongodb-driver-core) to 4.9.1)

**Steps To Reproduce**
1. Have app working with Javers for Mongo in Spring Boot 3.0.7
2. Update Spring Boot to 3.1.0
3. Javers cannot authenticate in Mongo

**Javers' Version**
7.0.1

**Additional context**
- Spring Boot version: 3.0.7 vs 3.1.0
- It's working when I'm using `spring.data.mongodb.uri` instead of configuring each property individually.

**Comment by bartoszwalacik** [comment]
Hi @RaGreen , you are right, the latest version of Javers is not compatible with the latest version of spring-mongo. I will take a look at it

**Comment by bartoszwalacik** [comment]
Fixed in 7.1.0
