### ISSUE TITLE
Javers Enhancements

### ISSUE THREAD

**Issue by eladh** [javers/javers#131]
Hi :-) 

is there any chance Javers look for Entity @Id  at method level and not just at field level ?

also - is there any way to retrieve the original object from taken as a snapshot from the History 

as far as i got is  :
javers.getStateHistory(InstanceIdDTO.instanceId("21959", EntityConn.class),10).get(0).getGlobalId().getCdoClass().getProperties()

is there any way to convert the CDO back the original class, in this example is EntityConn class ?

thanks :-)
elad.

**Comment by pawelszymczyk** [comment]
Hi

It is possible to place annotations at method level. Javers has property named [MappingStyle](https://github.com/javers/javers/blob/b523a05b64b86631ab9fd01da4616f6518590087/javers-core/src/main/java/org/javers/core/MappingStyle.java) , there are two options: MappingStyle.FIELD and MappingStyle.BEAN, when using BEAN style, JaVers accesses object state by calling getters. MappingStyle.FIELD is used by default so you have to explicitly register MappingStyle.BEAN, as follow:

```java
Javers javers = JaversBuilder
               .javers()
               .withMappingStyle(MappingStyle.BEAN)
               .build();
```

look at documentation: http://javers.org/documentation/domain-configuration/#entity-id-property

**Comment by pawelszymczyk** [comment]
For the second question: currently there is no possiblity to retrive original object or converte it from CDO. We considered about this feature, it is very interesting and usefull but not trivial. Can you create independent issue for it or even better try to provide some implementation?

**Comment by bartoszwalacik** [comment]
sugested issue title 'Restore orginal domain object from persisted snapshot'

**Comment by bartoszwalacik** [comment]
moved to https://github.com/javers/javers/issues/133
