### ISSUE TITLE
@DiffIgnore inside a nested field not respected when the field is an Object class

### ISSUE THREAD

**Issue by ls-rein-martha** [javers/javers#1318]
**@DiffIgnore should be respected even though the field is an Object class**

**Steps To Reproduce**
I have a **runnable test case ** which isolates the bug and allows Javers Core Team to easily reproduce it. I have pushed this test case to my fork of this repository:

https://github.com/ls-rein-martha/javer-test-object-class/blob/main/src/test/java/com/javertest/diffignoredemo/JaverTest.java

It only does not work when `Object` class used, if it is another super class then it work.

And what even weirder is it actually also mark that it hasChanges when all the value is the same at the above test.  (Try to change the addressLine to "Somewhere". But for some reason on my actual project, it doesn't mark hasChanges even though it has a very similar setup. I believe it is because of the `equal` method used at `Object` instead of deep compare?

Is there any work around for this?

**Javers' Version**
6.14.0 
I need it for Java 8 project

**Additional context**
This is to be used on comparing some Class that is inside a library, we are trying to do some migration and want to do a dryrun. Some properties at the lib class use `Object` as their field. The object pass in is our class, I want to ignore one of the field but does not seem to be possible.

**Comment by bartoszwalacik** [comment]
hi @ls-rein-martha , thanks for reporting but we do not support the old versions of Javers, meaning we accept only bug reports to the latest version of Javers. Could you please check if this bug is present in the latest version of Javers (the master branch)?

**Comment by bartoszwalacik** [comment]
okay, I have checked, so this issue is also present in the latest version of Javers, but it's not a bug, it's a feature :)

Javers mapping is static, so if you you have a property with type Object -- it will be mapped to ValueType statically, and a runtime type of this property value doesn't matter, see:

```
System.out.println( JAVERS.getTypeMapping(Address.class).prettyPrint() );
```

```
ValueObjectType{
  baseType: class org.javers.core.cases.Case1318DiffIgnoreWithObjectType$Student
  typeName: org.javers.core.cases.Case1318DiffIgnoreWithObjectType$Student
  managedProperties:
    Field address Object, javersType: ValueType, declared in: Student
}
```

Since all ValueTypes are compared using equals(), and not property-by-property, Address.equals() is called in your case. You can implement Address.equals() to ignore certain props

**Comment by ls-rein-martha** [comment]
Hi @bartoszwalacik I see, that is unfortunate 😢.

Override `equals` is not really possible since I want to use the field at the equal (let's say for HashSet) I just don't want it to be compared by `Javers` since I use it for dry run and that field value will be changed.

Anyway, it is fine, I will do some workaround on this by extending the lib class since this is not a bug.

Thank you for the response.

**Comment by bartoszwalacik** [comment]
so in this case, the only way is to declare address as Address and not Object
