### ISSUE TITLE
Javers multi audit data collection in mongodb

### ISSUE THREAD

**Issue by richardwesley69** [javers/javers#1323]
Hello, Everyone!!!.
I have implemented javers in my Spring boot application with MongoDB. i can able to see jv_head_id  and jv_snapshots collection in mongo database. now i have an two entity/collection classes (eg: Customer and Student), here i want to create jv_head_id  and jv_snapshots collection spererately like(**customer want separate jv_head_id  and jv_snapshots  audit collection table and  Student wants 
separate jv_head_id  and jv_snapshots  audit collection table** ) totally i want two **jv_head_id**  and two **jv_snapshots** as per my scenario. how can i achieve this requirements .

find out my app config for example
 =================   
javers:    
  documentDbCompatibilityEnabled: false
  objectAccessHook: org.javers.spring.mongodb.DBRefUnproxyObjectAccessHook
  snapshotsCacheSize: 5000
  snapshotCollectionName: "jv_snapshots"
  headCollectionName: "jv_head_id"
  schemaManagementEnabled: true
  mappingStyle: FIELD
  algorithm: SIMPLE
  commitIdGenerator: synchronized_sequence
  prettyPrint: true
  typeSafeValues: false
  initialChanges: true
  terminalChanges: true
  packagesToScan: 
  auditableAspectEnabled: true
  springDataAuditableRepositoryAspectEnabled: true
  
  customerAuditing:
    snapshotCollectionName: "customer_snapshots"
    headCollectionName: "customer_head_id"
    packagesToScan: "com.corporate.credit.entity"

  studentAuditing:
    snapshotCollectionName: "student_snapshots"
    headCollectionName: "student_head_id"
    packagesToScan: "com.corporate.credit.entity"
======================================

**Comment by bartoszwalacik** [comment]
questions should be asked on stackoverflow, here you can post bug reports or feature request, see https://github.com/javers/javers/blob/master/CONTRIBUTING.md

**Comment by richardwesley69** [comment]
what iam asking is a feature ,when will you solve the below problem 
i want separate collection(audited collection not the actual object collection) for my two objects 
Otherwise many services share the same collection to store versioned objects - can lead to the collection getting very large, and scaling strategies (sharding, for example) could differ from one domain object to another domain object.

For example, If i have a PersonService and a CarService, I might want to have collections jv_snapshots_persons and jv_snapshots_cars to keep the two domains separate and allow me to employ different sharding strategies for the collections.

**Comment by Sivaprakasam10d** [comment]
Yes here. i have an two repositories so i need to separate audit data collection in the MongoDB based on repository. 
like (repository 1 details should be placed one audit data collection another repository details should be another audit collection)

**Comment by richardwesley69** [comment]
Apologies for the confusion !. i have an separate repositories i just need audit collection/table in mongoDB( i need to store audit data's separate collection **eg: 1. customer audit data should seperate jv_snapshot & jv_headid and 2. Student audit data should separate jv_snapshot & jv_headid** ) 
is there any possible way ?

**Comment by richardwesley69** [comment]
and another issue also while using spring Sts the author name is saved correctly but while using intellij the author name is stored as a  random-integer why is this happening

**Comment by bartoszwalacik** [comment]
As I said before , the only way to have different names of Javers tables/collections is to create more Javers instances with different config. You can have as many Javers instances as you want.
