### ISSUE TITLE
Illegal Access Reflection for java,time.YearMonth, MonthDay, OffsetTime

### ISSUE THREAD

**Issue by josh-luker** [javers/javers#1341]
**Clear description of my expectations versus reality**
JaVers doesn't work on Java 16 with classes YearMonth, MonthDay, and OffsetTime.
This issue is similar to #1091 and #1200.

**Steps To Reproduce**
I have a **runnable test case** which isolates the bug and allows Javers Core Team to easily reproduce it. I have pushed this test case to my fork of this repository:

https://github.com/josh-luker/javers/blob/java-time-types/javers-core/src/test/groovy/org/javers/core/cases/CaseWithJavaTimeFields.groovy

**Javers' Version**
7.3.3

**Comment by josh-luker** [comment]
#1342

**Comment by bartoszwalacik** [comment]
Thanks @josh-luker , I will merge your PR today

**Comment by bartoszwalacik** [comment]
fixed in 7.3.6

**Comment by josh-luker** [comment]
Thanks @bartoszwalacik for the quick response!
