### ISSUE TITLE
Javers not catching change when a field is changed for an item in a list

### ISSUE THREAD

**Issue by Lakshay-agarwal** [javers/javers#1364]
I have a list of employees. When any item inside this list is edited and any field is changed for that item then javers is not detecting the change.

class Company {
String companyName;
List<employee> employees;
...
}

class employee {
String name;
int age;
}

I'm trying to build by jqlQuery in the following way - 

jqlQuery = QueryBuilder.byInstanceId(id, Company.class).withShadowScope(ShadowScope.DEEP_PLUS)
                    .withChangedPropertyIn(Arrays.stream(fields).map(Field::getName).toArray(String[]::new)).build();
List<Shadow<Company>> shadows = javers.findShadows(jqlQuery);

where,
fields is an array which contains the List<employee> as an element.

What should be modified so that if I change the age of suppose any one employee inside the list of employees, then javers can catch this change?

**Comment by pravinvignesh** [comment]
Hi @Lakshay-agarwal , Inorder to track your changes of employee, you need to register Employee class as valueobject in Javersbuilder
