### ISSUE TITLE
Javers does not close its ResultSet

### ISSUE THREAD

**Issue by apzpn** [javers/javers#1366]
**Javers should close correctly its resources including ResultSet (SQL)**
...

**Steps To Reproduce**
We have no noticed that ResultSet opened by Javers code (see attached documents) are not closed at the end.

**Javers' Version**
6.6.3

![screenshot-source-code](https://github.com/javers/javers/assets/114907238/2202d58c-d942-4e11-9366-bf89471b4f96)
[stacktrace.txt](https://github.com/javers/javers/files/14559459/stacktrace.txt)

**Comment by bartoszwalacik** [comment]
thanks for reporting @apzpn , feel free to contribute a fix

**Comment by bartoszwalacik** [comment]
👀

**Comment by bartoszwalacik** [comment]
thanks @apzpn , your PR is merged from here https://github.com/javers/javers/pull/1410

**Comment by bartoszwalacik** [comment]
fixed in 7.6.2
