### ISSUE TITLE
org.picocontainer.MutablePicoContainer compatibility

### ISSUE THREAD

**Issue by tokazio** [javers/javers#1374]
Javers 7.4.2

Calling
`JaversBuilder.javers().build()`

Throws
```
'org.picocontainer.MutablePicoContainer org.picocontainer.MutablePicoContainer.addAdapter(org.picocontainer.ComponentAdapter)'
java.lang.NoSuchMethodError: 'org.picocontainer.MutablePicoContainer org.picocontainer.MutablePicoContainer.addAdapter(org.picocontainer.ComponentAdapter)'
	at org.javers.core.pico.InstantiatingModule.instantiateAndBindComponents(InstantiatingModule.java:32)
	at org.javers.core.AbstractContainerBuilder.addModule(AbstractContainerBuilder.java:31)
	at org.javers.core.JaversBuilder.<init>(JaversBuilder.java:128)
	at org.javers.core.JaversBuilder.javers(JaversBuilder.java:107)
```

using
org.picocontainer:picocontainer:2.15

In debug mode i see

in org.javers.core.pico.InstantiatingModule

```
public final void instantiateAndBindComponents(){
        for (Class<?> implementation : getImplementations()){
            ConstructorInjector constructorInjector = new ConstructorInjector(implementation);
            container.addAdapter(constructorInjector);
        }

        for (Object bean : getBeans()) {
            container.addComponent(bean);
        }
    }
```

that

`ConstructorInjector constructorInjector = new ConstructorInjector(implementation);`

constructorInjector is throwing

Method threw 'java.lang.NoSuchMethodError' exception. Cannot evaluate org.javers.core.pico.InstantiatingModule$ConstructorInjector.toString()

**Comment by bartoszwalacik** [comment]
Hi @tokazio , Javers uses pico 2.15 from a very long time, I don't know how you stumbled upon such a critical issue, but without an repro, I can't help you

Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/javers/javers/blob/99ffd560f8cbca94fa0136ad9c252883f29a5552/CONTRIBUTING.md).

Please reopen if you provide a full test case with a repro.
