### ISSUE TITLE
db connection leak detected

### ISSUE THREAD

**Issue by hongv** [javers/javers#1375]
in ConnectionProvider implement，use datasource to get connection, call several times，the thread is hang up.

**Steps To Reproduce**
`public ConnectionProvider sqlConnectionProvider(DataSource dataSource) {
            return () -> dataSource.getConnection();
        }`

**Javers' Version**
7.4.2

**Additional context**
manual release the connection, all is ok.

**Comment by bartoszwalacik** [comment]
Sorry but I don't understand the issue you described. 
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/javers/javers/blob/b5a1b9adfb6ccc2f2f1350a4d7b19bcafc2e106f/CONTRIBUTING.md).
