### ISSUE TITLE
Instances of java.nio.file.Path default to ValueObject

### ISSUE THREAD

**Issue by Endeavourl** [javers/javers#138]
Instances of java.nio.file.Path are treated as *ValueObjects* by default. I believe this is wrong and they should default to *Values*.

I discovered this when using Path as a key for a Map. That caused
`Exception in thread "main" JaversException: VALUE_OBJECT_IS_NOT_SUPPORTED_AS_MAP_KEY JaVers runtime error - found ValueObject on KEY position in Map property 'MapType(type:java.util.Map<java.nio.file.Path, java.util.List<DomainClass>>)'. Please change the key class mapping to Value or Entity`

**Comment by bartoszwalacik** [comment]
assigned to JQL (1.2) release

**Comment by bartoszwalacik** [comment]
will also add URI and URL

**Comment by bartoszwalacik** [comment]
fixed in 1.1.2-SNAPSHOT
https://oss.sonatype.org/content/repositories/snapshots/
will be released soon in 1.2 JQL release

**Comment by bartoszwalacik** [comment]
please check fresh snapshot, does it solve your problem?
(give us a stargazers if you like Javers)

**Comment by Endeavourl** [comment]
Yep, no exceptions for Maps with Paths now.
