### ISSUE TITLE
Add a fromVersion and a toVersion option in a JaVers Query

### ISSUE THREAD

**Issue by AnthonyInMath** [javers/javers#1395]
**Describe the solution you'd like**
As a master's student currently working on a project, I am using JaVers. One feature that would be highly appreciated, as the title suggests, is the ability to filter queries from or up to a specific version (ideally with the "up to" version being exclusive).

**Describe alternatives you've considered**
An alternative solution would be to query the database for all versioned entities and filter them manually. However, this approach significantly lacks performance, especially when dealing with databases containing thousands of entries.

**Comment by bartoszwalacik** [comment]
sounds reasonable, I will review your PR

**Comment by bartoszwalacik** [comment]
thanks @AnthonyInMath , released in 7.6
