### ISSUE TITLE
@DiffIgnore add option to ignore diff only but still save whole entity

### ISSUE THREAD

**Issue by abccbaandy** [javers/javers#1397]
**Is your feature request related to a problem? Please describe.**
Currently, `@DiffIgnore` will ignore the property completely.
But we want to use shadow as our old copy of the entity, whole entity fields are need, we just don't care some field changed or not (like modify time).

**Describe the solution you'd like**
Add new option in `@DiffIgnore`, like `ignoreDiffOnly`.

**Describe alternatives you've considered**
Current just don't use `@DiffIgnore`, but the change will contain those field we don't care.

**Comment by bartoszwalacik** [comment]
Hi, could you please clarify your case, Shadows are your class instances, so all fields are there but empty, if you @DiffIgnore them

**Comment by bartoszwalacik** [comment]
sorry, but it doesn't make any sens in terms of Javers data model. If a field is ignored it's not persisted into Javers Repositorty so it's value can't be loaded in a Shadow

**Comment by bartoszwalacik** [comment]
You mean to have 2 separate annotations for diff (`javers.compare()`) and for repository (`javers.commit()`)?

**Comment by bartoszwalacik** [comment]
For now all you can do is to create 2 javers instances with different domain mapping config (you can do it without annotations using JaversBuilder)
