### ISSUE TITLE
I have 20 to 30 lakhs in audit  tracking  records so need get records based on filters

### ISSUE THREAD

**Issue by Mahendhar9652** [javers/javers#1399]
In audit tracking i have 20 to 30 lakhs records 

so i need retrive data based on filter conditions how ?

**Comment by bartoszwalacik** [comment]
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/javers/javers/blob/a59bccec97bde525d09b7dd35c9b6e399b88a0cc/CONTRIBUTING.md).
