### ISSUE TITLE
Possible bug when ignoring fields of a super class

### ISSUE THREAD

**Issue by Endeavourl** [javers/javers#140]
New issue based on https://github.com/javers/javers/issues/94#issuecomment-92263408

I found this weird behavior, possibly a bug, when ignoring properties of a super class.
```java
class abstract A {
    private final String irrelevantString;
    private final String string;
}
class B extends A {
    private final String irrelevantString;
}
```
Ignoring as
```java
new ValueObjectDefinition(B.class, Arrays.asList("irrelevantString"))
```
works as expected, ignoring the property in the derived class.
However
```java
new ValueObjectDefinition(A.class, Arrays.asList("irrelevantString"))
```
doesn't work at all.

Another thing, and this is more annoying, is that when there isn't such name conflict between super and derived classes you still cannot ignore super class property.
Instead you have to ignore it for every derived class like this
```java
new ValueObjectDefinition(B.class, Arrays.asList("irrelevantString"))
new ValueObjectDefinition(C.class, Arrays.asList("irrelevantString"))
new ValueObjectDefinition(D.class, Arrays.asList("irrelevantString"))
// etc
// none of B, C or D contain irrelevantString property
// yet using A.class doesn't work
```

**Comment by bartoszwalacik** [comment]
sure, will take care about this

**Comment by bgalek** [comment]
you could help us providing a complete test for this issue?

**Comment by bartoszwalacik** [comment]
@Endeavourl  are You aware that in your example, in the subclass, you have 2 properties `String irrelevantString`?

```
ValueObjectType(type:class org.javers.core.cases.ConcreteClass)
properties {
  Field class java.lang.String irrelevantString; //declaring class:org.javers.core.cases.B
  Field class java.lang.String irrelevantString; //declaring class:org.javers.core.cases.A
  Field class java.lang.String string; //declaring class:org.javers.core.cases.A
}
```
so you should ignore both or simply try fixing your model and remove one of them.
In Java, If a field is private, it doesnt mean that it isnt inherited to a subclass, it is but it isnt accessible
