### ISSUE TITLE
Why can't I use javers.compare() with a Value?

### ISSUE THREAD

**Issue by gustavocesario-as** [javers/javers#1408]
**Is your feature request related to a problem? Please describe.**
I have an entity with a quite complex structure, so I'm having to figure out the best way to find the changes. One of the properties of this Entity is a list of objects and I want to track the changes made to each of these objects. So for example, if I change the property "foo" of the object with id "123" I want to be able to return in my request that the object "123" of my parent entity had the field "foo" changed. At the moment I annotated this class as a `@Value`, because it could accurately return to me which objects where changed when I updated my parent entity and its fields.

**Describe the solution you'd like**
As I annotated the class as `@Value`, the change for my parent entity is returned as a `ListChange`, and each of these changes are `ElementValueChange`. Therefore, `.leftValue()` and `.rightValue()` return the entire object that was used in the comparison. However, I still want to find exactly which fields of these objects were changed, so the only solution that I could think was to use `javers.compare()` between the left and right value. However, this threw the exception `COMPARING_TOP_LEVEL_VALUES_NOT_SUPPORTED`. Reading through the code I found where this exception is thrown:

```java
        JaversType jType = typeMapper.getJaversType(handle.getClass());
        if (jType instanceof ValueType || jType instanceof PrimitiveType){
            throw new JaversException(JaversExceptionCode.COMPARING_TOP_LEVEL_VALUES_NOT_SUPPORTED,
                    jType.getClass().getSimpleName(), handle.getClass().getSimpleName());
        }
```

I get that it makes sense for primitives, but why can't I compare different Values as they are still objects?

**Describe alternatives you've considered**
I also tried to annotate my class as `@ValueObject`, but it lacks some information that I need. When fetching the changes, Javers only informs me that the value of the property "foo" was changed, but I still need to know what is the ID of the object that was changed. 

**Additional context**
I want to track all the changes made to the parent and its child entities/value objects/values by calling `.getChanges()` on the parent. I don't know if this is a bad practice but I will receive only the parent id in my API request, so that is the only way that I could think to get the changes. I believe this is why I couldn't get it working when I annotated my entity as `@Entity` too.

**Comment by bartoszwalacik** [comment]
Hi @gustavocesario-as , if these objects have identity, you can map them as `@Entity`, then you will be able the get both left/right values and an object Id directly from `PropertyChange`
