### ISSUE TITLE
Issue with GSON builder  throwing "NaN is not a valid double value as per JSON specification."

### ISSUE THREAD

**Issue by BrakefieldMN** [javers/javers#1415]
**Clear description of my expectations versus reality**
An object with a double value set as Double.NaN should be persisted. In reality, javers' gson builder throws an error because it does not leverage "serializeSpecialFloatingPointValues". 

**Steps To Reproduce**
I have a **runnable test case ** which isolates the bug and allows Javers Core Team to easily reproduce it. I have pushed this test case to my fork of this repository:

https://github.com/BrakefieldMN/javers/blob/master/javers-spring-boot-starter-mongo/src/test/groovy/org/javers/spring/boot/mongo/JaversMongoStarterNullDoubleTest.groovy

**Javers' Version**
7.6.2

**Additional context**
This issue was identified a few years ago. 
https://stackoverflow.com/questions/54573968/issue-in-infinity-is-not-a-valid-double-value-as-per-json-specification-with-flo 

I also intend to open a PR to make the adjustment in the gson builder.

**Comment by bartoszwalacik** [comment]
Hi @BrakefieldMN , thanks for the bug report. We are happy to see your pull request with a fix

**Comment by BrakefieldMN** [comment]
I tried following the documentation for the process. Please let me know if I missed or need to change anything! Thank you for your response.

**Comment by bartoszwalacik** [comment]
thanks , I will take a look at your PR in a few days

**Comment by bartoszwalacik** [comment]
the fix is released in 7.6.3
