### ISSUE TITLE
question : is there something that deal with bi-directional relationships ?

### ISSUE THREAD

**Issue by erikgollot** [javers/javers#143]
Do you analyze jpa annotations for collection and particularly the mappedBy attribute ?

**Comment by bartoszwalacik** [comment]
no, it is not necessary, Javers detects all relationships using Reflection API.
All you have to do is to map your types to Entities, ValueObjects

**Comment by bgalek** [comment]
hope everything is all right  :)

**Comment by erikgollot** [comment]
In fact i understand that it's not necessary for the diff. But i would like to use the diff for merging. And when you want to merge, you need the relationship that exists semantically between the collection of children in the 'parent' and the parent attribute in the child.
So it could be interested to have this information on both side when a diff exists

**Comment by bartoszwalacik** [comment]
still, your issue is not clear for me, javers diff suports bi-directional relatipnships (parent-child). For example if you change a parent for some child you got 3 changes: child add, child remove and parent change.
What is your use case?

**Comment by erikgollot** [comment]
My case is just to be able to know which attribute on the child represents the reference to the parent. 

If we've the 3 changes you mention it's ok but not enough.

Is it more clear ?

Envoyé depuis Yahoo Mail pour Android

De:"Bartosz Walacik" <notifications@github.com>
Date:Dim j Mai AM à 9:19
Objet:Re: [javers] question : is there something that deal with bi-directional relationships ? (#143)

still, your issue is not clear for me, javers diff suports bi-directional relatipnships (parent-child). For example if you change a parent for some child you got 3 changes: child add, child remove and parent change.
What is your use case?

**Comment by bartoszwalacik** [comment]
In Change you have a property name , so you can easily map it to whatever you want. Why move your domain logic to external lib?

**Comment by bartoszwalacik** [comment]
in fact, you can use type of Change to infer which relation is affected. If it is ReferenceChange - *toOne, otherwise OneToMany.

**Comment by erikgollot** [comment]
Ok but i think it would be better to detect the semantic relationship between the collection of children and the reference to the parent in the child, in case of a onetomany relation for example.  And 'help' the api user instead of let him re-analyze the structure of the class.

My objective is to be able to make a consistent merge using the diff.


Don't you think it can help ?

Envoyé depuis Yahoo Mail pour Android

De:"Bartosz Walacik" <notifications@github.com>
Date:Dim j Mai PM à 16:25
Objet:Re: [javers] question : is there something that deal with bi-directional relationships ? (#143)

in fact, you can use type of Change to infer which relation is affected. If it is ReferenceChange - *toOne, otherwise OneToMany.

**Comment by bartoszwalacik** [comment]
lets assume that you would be able to put more info about your relationships (parent, child, and so on) to javers. What exactly you want javers to do with this data?

**Comment by erikgollot** [comment]
Javers nothing

But my merge process will be able to manage the consistency. If the user choose to accept that the child is a new child of the parent, accepting the 'collection change' my merge process will disallow to change the parent of the child to another parent.

Its really a problem you address when merging not when you do a diff. 

Envoyé depuis Yahoo Mail pour Android

De:"Bartosz Walacik" <notifications@github.com>
Date:Dim j Mai PM à 17:01
Objet:Re: [javers] question : is there something that deal with bi-directional relationships ? (#143)

lets assume that you would be able to put more info about your relationships (parent, child, and so on) to javers. What exactly you want javers to do with this data?

**Comment by bartoszwalacik** [comment]
simply I cannot agree to put some data or logic to javers-core
in order to do nothing with it :)
it doesnt make sense, maybe I could help in other way, when you explain why Merge cannot be done using Changes that are already available

**Comment by erikgollot** [comment]
No problem i'm currently writing my own diff-merge library that can use jpa annotations or specific ones and that embed more semantic to be able to simplify a merge.

I was just trying to share my point of view with you.  If you're not convinced, no problem. 

Thanks because javers gives me some ideas and it's already interested for my work

Envoyé depuis Yahoo Mail pour Android

De:"Bartosz Walacik" <notifications@github.com>
Date:Dim j Mai PM à 19:29
Objet:Re: [javers] question : is there something that deal with bi-directional relationships ? (#143)

simply I cannot agree to put some data or logic to javers-core
in order to do nothing with it :)
it doesnt make sense, maybe I could help in other way, when you explain why Merge cannot be done using Changes that are already available
