### ISSUE TITLE
 Entity related to proxy

### ISSUE THREAD

**Issue by phelypp** [javers/javers#144]
Good afternoon people
Javers works with persistence related entity in the state of proxy?
ENTITY_INSTANCE_WITH_NULL_ID this error occurs, you need loads before?
thank you

**Comment by bartoszwalacik** [comment]
You mean hibernate proxy for lazy-loading?

**Comment by phelypp** [comment]
yes

**Comment by bartoszwalacik** [comment]
we have open issue for that
https://github.com/javers/javers/issues/91
comment there to be notified about status

**Comment by phelypp** [comment]
That's right, Ja has a solution ??

this occurring

JaversException: ENTITY_INSTANCE_WITH_NULL_ID Javers runtime error - Found Entity instance of class'

thank you

**Comment by bartoszwalacik** [comment]
not sure if I understand you, if you have a problem with Hibernate proxies, you have to wait on https://github.com/javers/javers/issues/91

**Comment by phelypp** [comment]
Yes I am with this problem

What is the prediction # 91?

thank you

**Comment by bartoszwalacik** [comment]
well, we are working on it, think end of May
