### ISSUE TITLE
Test jar in javers-core is missing

### ISSUE THREAD

**Issue by Dieler** [javers/javers#147]
I've started implementing a javers repository for Elasticsearch. I'm restricted to use Maven as build system because of the constraints enforced by the project the repository implementation is intended for. I wanted to use the repository e2e test coming with javers-core to test my implementation but that is not possible since the test classes are no longer part of the distribution.

**Comment by bartoszwalacik** [comment]
Ok, we can do it, btw we like Elastic, did you think about contributing your new repository to Javers project?

**Comment by Dieler** [comment]
Basically, contributing the repository impl should be possible, but I'll have to check with my boss first. Right now, we're using spring-data-elasticsearch. I think an implementation without that dependency would be better. So once I'm done with my project I could port the result to a version based on pure elasticsearch, probably in my spare time.

**Comment by bartoszwalacik** [comment]
Hi,
sounds like a good idea, 
JaversElasticRepository would be better without dependency to spring-data-elasticsearch.

Here is the test jars, 
https://oss.sonatype.org/content/repositories/releases/org/javers/javers-core/1.2.0/
in few hours it will be available in Maven Central

**Comment by bartoszwalacik** [comment]
Give us a notice when you'll be eager to contribution. Think we can work together on puting your code to Javers project.

**Comment by ssozonoff** [comment]
Did this project ever happen ? An ES repo would be amazing.

**Comment by bartoszwalacik** [comment]
well, I'd love to have Elastic repository in JaVers but we need contributors support for that
