### ISSUE TITLE
v1.3 release date

### ISSUE THREAD

**Issue by vcvetkovik** [javers/javers#148]
I would like to persist the audit data in Oracle DB. I saw that this is scheduled for v1.3 but I was not able to find the release plan. When you expect to have the final 1.3 version?

**Comment by bartoszwalacik** [comment]
good question, we'll do some planning tomorrow and let you know.
But in fact, I need to find someone who want to contribute in developing Oracle and MySQL support.
Maybe You would like?

**Comment by bartoszwalacik** [comment]
1.3 should be released in the beginnig of June

**Comment by bartoszwalacik** [comment]
1.3 with Oracle and MsSQL support is released
