### ISSUE TITLE
got an exception when trying to test JaversSqlRepositoryE2ETest

### ISSUE THREAD

**Issue by yong86** [javers/javers#149]
I got this exception when trying to run JaversSqlRepositoryE2ETest:
"groovy.lang.MissingMethodException: No signature of method: org.javers.repository.sql.JaversSqlRepositoryE2ETest.javers() is applicable for argument types: () values: []"
could anyone help me out?

**Comment by bartoszwalacik** [comment]
maybe you are violating package private scope?
what are you doing? you don't need to run javers test (Travis CI is doing it) unless you are implementing JaversRepository interface
