### ISSUE TITLE
 auto-audit feature outside of spring Container

### ISSUE THREAD

**Issue by yong86** [javers/javers#152]
I'm using spring jpa repositories outside spring container(OSGi env.) and for now,I succeeded to make javers creates the four tables in sql DB.but still don't know how to enable aspect support(@EnableAspectJAutoProxy in spring like behaviour )  for  auto-audit.
could anyone help me with that?

**Comment by bartoszwalacik** [comment]
You should tkink about pure AspectJ approach. We are not going to implement it but we can accept a well written contribution from you.
