### ISSUE TITLE
Change log with ValueObject changes

### ISSUE THREAD

**Issue by vmaubert** [javers/javers#154]
Hi,

I would like to list all changes for an entity by commit. But I don't have ValueObject changes in the changelog.

Example : 

 ```
   @Test
   public void shoudPrintTextChangeLog() {
        // given:
        Javers javers = JaversBuilder.javers().build();
        Employee bob = new Employee("Bob", 9_000, "Scrum master" );
        bob.setPrimaryAddress(new Address("New-York", "5th Avenue"));
        javers.commit("me", bob);

        //Change its salary
        bob.setSalary(11_000);
        javers.commit("me", bob);

        //Change its primary address
        bob.getPrimaryAddress().setStreet("6th Avenue");
        javers.commit("me", bob);

        // when:
        List<Change> changes = javers.findChanges(
                QueryBuilder.byClass(Employee.class).build());
        String changeLog = javers.processChangeList(changes, new SimpleTextChangeLog());

        // then:
        System.out.println(changeLog);
   }
```

The output : 
 ```
commit 2.0, author: me, 19 mai 2015 13:58:46
  changed object: org.javers.core.examples.model.Employee/Bob
    value changed on 'salary' property: '9000' -> '11000'
 ```

I don't have the primary address change :-/ How can I do that ?

Thanks!

**Comment by bartoszwalacik** [comment]
see http://javers.org/documentation/jql-examples/#by-value-object-query
you need to query for ValueObject (Address), not Entity (Employee )

```
QueryBuilder.byValueObject(Employee.class,"primaryAddress")
```

**Comment by bartoszwalacik** [comment]
I mean, for now, you cant query for both things (Entity changes and VO changes) using single query

**Comment by vmaubert** [comment]
Ok ok, thx for your answer :-/

I need the complete change log of an entity for my application. Can I 'merge' by commit the results of the two queries (Entity and VO) properly ?

**Comment by bartoszwalacik** [comment]
Why not, try to join both change List and pass them into javers.processChangeList()
Maybe an easier solution would be new JQL query type in javers. We are quite busy at the moment but if you are eager to contribute, we could help to make it happen

**Comment by bartoszwalacik** [comment]
closed due to lack of activity
