### ISSUE TITLE
Javers + Spring data + Spring DI + Mongo DB example

### ISSUE THREAD

**Issue by swarooprath** [javers/javers#161]
Hi 

 Do we have an example using Javers + Spring data + Mongo DB to store audit history of objects. I saw a half baked unit test case using Fongo and a configuration example but an end2end example would be very helpful.

 Where and how is the audit history saved ? Am more interested in a working auto-audit example with Mongo.

- Swaroop

**Comment by bartoszwalacik** [comment]
Hi, did you looked at http://javers.org/documentation/spring-integration/#auto-audit-example ?

**Comment by bartoszwalacik** [comment]
closed due to lack of activity
