### ISSUE TITLE
ENTITY_INSTANCE_WITH_NULL_ID

### ISSUE THREAD

**Issue by docfirefly** [javers/javers#165]
Within my data there are a few entities with null id and I am receiving this message:

Caused by: JaversException: ENTITY_INSTANCE_WITH_NULL_ID JaVers runtime error - Found Entity instance of class '....' with null id

How can I handle this? Can this be ignored somehow or can I somehow state that null id == null id = no diff?

Thanks

**Comment by bartoszwalacik** [comment]
If you have missing

**Comment by bartoszwalacik** [comment]
Missing Ids maybe you should map your class as ValueObject? Comparing null to null looks strange to me, is it true or false?

**Comment by docfirefly** [comment]
Thanks for your fast reply. I will try to map it as ValueObjects. But how is the null ID treated then?
Comparing null to null in my opinion would be like this: if the value was null before and is null in the new version then it didnt change, but yes...its strange.

**Comment by bartoszwalacik** [comment]
nulls are handled properly when occurs on normal properties.
Entity.ID is the only exception, it cannot be null, the whole diff algorithm is built on this assumption and I dont want to change it.
Catch us on gitter https://gitter.im/javers/javers if you need more help

**Comment by Sarvesh-D** [comment]
@bartoszwalacik I am using hibernate interceptor and javers for auditing purpose and i want to audit when a new entity is saved to db. Obviously the entity id at time of insertion will be null, so when i try to pass a blank new instance to javers.compare, it gives me entity id null error.

```
Object old = entity.getClass().newInstance();
Diff diff = javers.compare(old, entity);
```

P.S: entity is the new entity being inserted into db, hibernate interceptor passes this during callback to onSave()

**Comment by bartoszwalacik** [comment]
Why dont you commit to javers after Hibernate assignes id?

**Comment by Sarvesh-D** [comment]
The interceptor triggers before the id has been generated. Besides i am only using javers Diff feature for comparing two objects. Is there a way to compare object with null key, maybe something we can ignore using javers configuration?

**Comment by bartoszwalacik** [comment]
Of course, just map them as ValueObjects in JaversBuilder.registere()
