### ISSUE TITLE
EclipseLink  Support

### ISSUE THREAD

**Issue by yong86** [javers/javers#166]
I tried to implement EclipseLink Support:

    public class JpaEclipseLinkConnectionProvider implements ConnectionProvider{

    @PersistenceContext
    private EntityManager entityManager;

    @Override
    public Connection getConnection() {
        entityManager.getTransaction().begin();
       Connection connection = this.getEntityManager().unwrap(java.sql.Connection.class);
       return connection;
     }
when should I commit the transaction?

**Comment by bartoszwalacik** [comment]
well, i don't know much about EclipseLink but if it implements JPA (EntityManager), then you shouldn't call commit. EntityManager does it.

**Comment by yong86** [comment]
@bartoszwalacik  thanks for your reply. Actually,I tried it when creating the three tables and the sequences and I must commit the transaction manually.I don't know where should i commit the transaction after saving or delete data?

**Comment by bartoszwalacik** [comment]
If you are using JPA and EntityManager you do not commit manually.  Take a look at our impl for JPA & Hibernate and do it the same way.

**Comment by yong86** [comment]
I don't able to get to work. As mentioned here: https://wiki.eclipse.org/EclipseLink/Examples/JPA/EMAPI
after getting the connection in eclipse link ,i should commit the transaction manually.

**Comment by bartoszwalacik** [comment]
well, simply, calling commit() is on your side.
We explains ideas behind connection-provider  here:
http://javers.org/documentation/repository-configuration/#connection-provider

I'am not sure what you are asking about. We do not offer EclipseLink integration but you can do it 
on your own by implementing ConnectionProvider interface.

All you have to do is to provide for JaVers your open JDBC connection. What is uncler here?

**Comment by yong86** [comment]
OK,thanks.I did it
