### ISSUE TITLE
ElementValueChange not using @Id annotation in Levenstein

### ISSUE THREAD

**Issue by tchegito** [javers/javers#167]
Hi people,

not sure that's an issue, maybe an enhancement, but I'm surprised of a different behavior between simple method and Levenshtein method for comparing.

I isolate it in a very simple usecase, which I resume here with words instead of code.
Consider two class A and B with each one an @Id declared on a field. Class A contains a field which is a list of object B.
We create two instances A1 and A2 of A with same value I1 for Id. We create two instances B1 and B2 of B with same value I2 for Id. We assign a singleton list of B1 to object A1. And the same for A2 with a singleton list of B2.

Now, let's compare.

Simple method returns no differences at all.
And Levenshtein returns one difference of type ElementValueChange. I check the code, and that's because of this method calls 'equals' method which I haven't defined. Okay. But why this method can't compare fields defined with @Id ?

Thanks for help. And by the way, this is a great library !

**Comment by bartoszwalacik** [comment]
thanks @tchegito, well, both list comparing algorithms should produce similar results.
If you have a list of objects with @Id - you have the list of Entities.
In this case, entities should be compared only by Id.

There could be a bug in Levenshtein. Could you help us and isolate this case to the new, failing test, pushed to your forked JaVers github repository?

**Comment by tchegito** [comment]
Hi Bartosz

Yes I can do that ! I'll try today, but you will see, this is very simple.
I hope my report isn't confused by my whole process (this may be), so I'll
make it simplest as possible.

Thank you for quick answer

**Comment by bartoszwalacik** [comment]
ok, I am waiting for the isolated test

**Comment by tchegito** [comment]
Hi Bartosz

I just pushed unit test in my forked repo here:
https://github.com/tchegito/javers

**Comment by bartoszwalacik** [comment]
ok, I'll come back to it after weekend

**Comment by tchegito** [comment]
Hi Bartosz,

first of all, sorry to reuse this mail about another question, but I don't
have other one.

Using Javers, my main goal was to :
1) analyse diff between 2 objects
 ==> it's ok
2) propagate these diff from the first object
 ==> I get trouble there

The main problem I encounter is: how reflect the changes detected on the
first element ? I tried many approaches:
-change your source code to store a reference to the original node,
(because you only provide "right" node) in each kind of Change (this is
huge, and I don't really like fork your work, that suggests I'm using it
the wrong way)
-commit changes on subpart of the graph and retrieve toplevel by the method
you provided there : https://github.com/javers/javers/issues/133

And my last idea was to iterate over the graph, looking for an object with
given GlobalId: Class and Id. But I'm sure there have to be a way, using
your code to do that. I would rather avoid to reinvent the wheel, starting
with BeanUtils.


Not sure this is really clear, but your help would be really appreciated !

Thank you

**Comment by bartoszwalacik** [comment]
Hi,
what do you mean by propagate? Your goal is to synchronize both objects by aplying changes calculated by diff to one of those objects (left I guess)?

**Comment by tchegito** [comment]
Yes you're right !

The goal is to synchronize graph objects between two databases.

**Comment by bartoszwalacik** [comment]
So having the left reference would solve your issue? 
What about this 'apply changes' feature? It could be useful. For now I don't have time to write it but I can accept PR.
Using javers-core engine (Cdo abstraction) it shouldn't be very hard to implement.

**Comment by bartoszwalacik** [comment]
fixed in 1.2.10

**Comment by tchegito** [comment]
Thanks Bartosz !
