### ISSUE TITLE
List comparison differs according to the container

### ISSUE THREAD

**Issue by tchegito** [javers/javers#176]
Hi people,

I noticed a difference comparing two lists in 2 cases:
- direct: compare(List\<A> list1, List\<A> list2)
- with container: compare (new ListContainer(list1), new ListContainer(list2))

(ListContainer is just a basic object with only a single member List\<A>)

In first case, an element removal isn't detected. I only have ElementValueChanged. But in the second case, removal are well detected.

First of all, is it normal ? Maybe my approach is wrong. But the need I have now, is to check differences inside many different lists. The only option I found for the moment, is to create an object containing the 70 lists I want to check. But this is kind of boring.

If you want me to go further, I can provide a unit test, but I would like to know if my concerns are right.

Thank you

**Comment by bartoszwalacik** [comment]
looks like a bug, could you isolate this case to the failing test and push it to github on forked javers repo?

**Comment by tchegito** [comment]
Thanks for the quick answer. I'll do that this evening.

But please note that the first behavior is in accordance with your
documentation here ( http://javers.org/documentation/diff-configuration/ in
the "Simple vs Levenshtein algorithm" section).
There we can read:
"

javers.compare(['a','b','c','d'],
               ['a','g','e','i'])
(Levensthein)
(1). 'b'>>'g'
(2). 'c'>>'e'
(3). 'd'>>'i'

"The 'e' element is not marked as "removed", although if the list is
inside an object, we got an "ObjectRemoved" change in the results.

But I'll illustrate that in the unit test.

**Comment by tchegito** [comment]
I just pushed on my repo here:
https://github.com/tchegito/javers/commit/f7bb1d0e027bef7f2ca4a209c8b92a33934fa151

**Comment by bartoszwalacik** [comment]
ok, I'll take a look at this

**Comment by bartoszwalacik** [comment]
when running TestListChanges, we have the following results:
```
diffDirect: Diff:
1. ListChange{globalId:'org.javers.core.graph.LiveGraphFactory$ListWrapper/', property:'list', containerChanges:[(1).'ID2/Value2'>>'ID2/Value3', (2).removed:'ID3/Value3']}

diffWithContainer: Diff:
1. ObjectRemoved{globalId:'org.javers.core.examples.listalgorithm.CodeLabel/ID3'}
2. ListChange{globalId:'org.javers.core.examples.listalgorithm.ListContainer/', property:'myList', containerChanges:[(2).removed:'org.javers.core.examples.listalgorithm.CodeLabel/ID3']}
3. ValueChange{globalId:'org.javers.core.examples.listalgorithm.CodeLabel/ID2', property:'label', oldVal:'Value2', newVal:'Value3'}
```

regardless of the list comparing algorithm... 
The second result (diffWithContainer) looks like valid

**Comment by bartoszwalacik** [comment]
so the problem is with diffDirect

**Comment by bartoszwalacik** [comment]
The reason is ListWrapper, when you pass a raw List to the diff, JaVers packs it in a 'artifitial' ValueObject:

```
ValueObjectType{
  baseType: class org.javers.core.graph.LiveGraphFactory$ListWrapper
  managedProperties:
    Field List<Object> list; //declared in: ListWrapper
}
```

Unfortunately, given list is then treated as generic List (List of ValueObjects), and not as a List of Entities (CodeLabel in your case)

**Comment by tchegito** [comment]
Yes, that's right ! I've figured it out, with a debugging session. But I
couldn't determine if it was the right thing to do or not. Like I said
earlier, this behavior is the one you provided on your documentation. But
maybe the difference is about the way data are treated, as you guessed :
ValueObject or Entities ?

Is it a bug or a feature ); ?

**Comment by bartoszwalacik** [comment]
I wouldn't say it's a bug. It's a undocumented feature :)
I've just added more javadoc to compare() function, in order to explain this ambiguity:

https://github.com/javers/javers/blob/master/javers-core/src/main/java/org/javers/core/Javers.java

Could you please read it and give me some feedback if it is understandable?

**Comment by tchegito** [comment]
I read it but I don't understand very well why Javers can't determine
content type of list. You could get it with reflection like this:
http://stackoverflow.com/questions/1942644/get-generic-type-of-java-util-list
This could be great, to use generics revealed at runtime.
I think a lot about this feature of comparing lists, and the need we had in
our application has been adressed another way: calling Javers comparison
from a super container, with an ArrayList for all possible types. This
isn't very reusable (to say the least !) and that component class is more a
workaround than a real graph section. Runtime generics would have done the
trick, but maybe I overlooked something about this: you wrote it's
"impossible to determine type of raw collections". Maybe I missed something.

Anyway, I thought it worked that way when I read this sentence in your
documentation: "JaVers needs to know the JaversType
<http://javers.org/javadoc_1.2.0/index.html?org/javers/core/metamodel/type/JaversType.html>
for each of your classes *spotted in runtime*", not at compilation.

**Comment by bartoszwalacik** [comment]
@ tchegito, i know how Java Reflections works :) Even in this stack answer, you can read 'If those are actually fields of a certian class'. There are no field when you are passing List reference directly to the compare() function. 

In Java, Generics exists only in compile time, in runtime, they are erased to raw types, it's caled Type Erasure.

So if you are passing List<Sth> reference as an Object reference to the compare() function, all we can do is to call getClass() and see that it is a raw List. That's why we need a container with a field which could be typed as List<Sth>. Field and method types are not erasured, so we can use reflection to access type parameter (<Sth>)

**Comment by tchegito** [comment]
Yes, you're right, I was pretty sure I missed something ! As you have only
an instance, you can't determine the generic type.

But what about a specific method "compareCollections" where a third
parameter could identify the type by its class ? Ah, that may be ugly. If
that was my own library, I'd think "that will deface my code !"
Or you can simply get the first element of any collection (left or right,
as long as there's at least 1 element) and call getClass() on it ? And
consider that is the content type of all elements.

I don't know, and sorry for your time loss in these rough reflections.
We'll use our workaround here so problem is solved in our application.

Thanks Bartosz, and the javadoc is fine, by the way.

**Comment by bartoszwalacik** [comment]
Specific method `compareCollections(Object left, Object right, Class itemType)` looks like not so bad idea. But i don't want to look at the type of first element. JaVers is strongly typed, just like Java. What if user's collection is heterogenous? It would lead to non-deterministic results.

So now when we got the diagnosis maybe you could close this issue and create new issue (feature request) for `compareCollections(Object left, Object right, Class itemType)` method?

**Comment by tchegito** [comment]
Ok, I'll open a new issue about that.
