### ISSUE TITLE
Pagination for .findSnapshots / .findChanges

### ISSUE THREAD

**Issue by fynnfeldpausch** [javers/javers#179]
Is there any way to use a pagination filter when searching snapshots? The QueryBuilder provides a .limit() functionality but I am not able to find any .skip() feature. Both methods are needed to implement a proper pagination for searching snapshots.

**Comment by bartoszwalacik** [comment]
hi, there is no pagination yet, agreed that it could be useful. If you want to have it quickly, think about contribution

**Comment by mwesolowski** [comment]
Hi, I will add skip functionality to QueryBuilder when PR #282 is accepted and merged. Cheers.

**Comment by bartoszwalacik** [comment]
PR in review https://github.com/javers/javers/pull/285

**Comment by bartoszwalacik** [comment]
released in 1.4.3
see http://javers.org/documentation/jql-examples/#commit-date-filter
