### ISSUE TITLE
Unable to introduce Javers into an already working system

### ISSUE THREAD

**Issue by gzsombor** [javers/javers#180]
We have a system - fairly standard, JPA/Hibernate/Spring/SQL -  which already has entities. I've tried to follow the documentation to configure javers - and it seems to be working for new entities. But unfortunately, for modifying already existing entities, or creating an entity with reference to an already  existing - and not yet audited - entity fails with a foreign key violation.
 How can I configure Javers to work in this situation? I can imagine 2 solutions, either I need a way to  create snapshots for every entities, or somehow force Javers to create lazily snapshots for the referenced entities. Is  any of it possible ?

**Comment by bartoszwalacik** [comment]
Hi, what do you mean by: entity fails with a fk violation? Please give a
concrete example.

**Comment by gzsombor** [comment]
Yes, foreign key violations with MySQL:
```
[ERROR] org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.polyjdbc.core.exception.QueryExecutionException: [INSERT_ERROR] Failed to run insert query:
INSERT INTO jv_global_id(cdo_class_fk, local_id, global_id_pk) VALUES(:cdo_class_fk, :local_id, :global_id_pk)(cdo_class_fk, local_id, global_id_) VALUES(:cdo_class_fk, :local_id, :global_id_)] with root cause
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`testapp`.`jv_global_id`, CONSTRAINT `jv_global_id_cdo_class_fk` FOREIGN KEY (`cdo_class_fk`) REFERENCES `jv_cdo_class` (`cdo_class_pk`))
```

**Comment by bartoszwalacik** [comment]
looks like a bug in JaversSqlRepository, but I need a failing test which distiles this case, 
could you provide this test? (preferably in forked javers repository)

**Comment by gzsombor** [comment]
Sorry, I cannot reproduce it anymore. I've added/removed the @DiffIgnore annotation in a couple of places, probably that caused some problems inside Javers.
