### ISSUE TITLE
Multilevel comparation

### ISSUE THREAD

**Issue by bojanv55** [javers/javers#184]
I assume this should find diffs, since objects are different with same key?

    import org.javers.core.Javers;
	import org.javers.core.JaversBuilder;
	import org.javers.core.diff.Diff;
	import org.javers.core.diff.ListCompareAlgorithm;
	import org.javers.core.metamodel.clazz.EntityDefinition;
	import org.junit.Test;
	
	import java.util.HashMap;
	import java.util.HashSet;
	import java.util.Map;
	import java.util.Set;
	
	public class MultiLevelMapTest {
	
	
		class Key {
			private int value;
	
			public int getValue() {
				return value;
			}
	
			public void setValue(int value) {
				this.value = value;
			}
	
			@Override
			public boolean equals(Object o) {
				if (this == o)
					return true;
				if (o == null || getClass() != o.getClass())
					return false;
	
				Key key = (Key)o;
	
				if (value != key.value)
					return false;
	
				return true;
			}
	
			@Override
			public int hashCode() {
				return value;
			}
		}
	
	
		class Container{
			private Key key;
			private String a;
			private int b;
	
			public String getA() {
				return a;
			}
	
			public void setA(String a) {
				this.a = a;
			}
	
			public int getB() {
				return b;
			}
	
			public void setB(int b) {
				this.b = b;
			}
	
			public Key getKey() {
				return key;
			}
	
			public void setKey(Key key) {
				this.key = key;
			}
	
			@Override
			public boolean equals(Object o) {
				if (this == o)
					return true;
				if (o == null || getClass() != o.getClass())
					return false;
	
				Container container = (Container)o;
	
				if (!key.equals(container.key))
					return false;
	
				return true;
			}
	
			@Override
			public int hashCode() {
				return key.hashCode();
			}
		}
	
	
	
		@Test
		public void shouldNotFail(){
	
			Javers javers = JaversBuilder.javers()
					.registerEntity(new EntityDefinition(Container.class, "key"))
					.withListCompareAlgorithm(ListCompareAlgorithm.LEVENSHTEIN_DISTANCE)
					.build();
	
	
			Map<Long, Map<Integer, Set<Container>>> map1 = new HashMap<Long, Map<Integer, Set<Container>>>();
			Map<Long, Map<Integer, Set<Container>>> map2 = new HashMap<Long, Map<Integer, Set<Container>>>();
	
			Key k1 = new Key();
			k1.setValue(1);
			Container c1 = new Container();
			c1.setKey(k1);
			c1.setA("c1");
			c1.setB(1);
	
			Container c2 = new Container();
			c2.setKey(k1);
			c2.setA("c2");
			c2.setB(2);
	
			Map<Integer, Set<Container>> firstGet = map1.getOrDefault(1L, new HashMap<Integer, Set<Container>>());
			map1.putIfAbsent(1L, firstGet);
			Set<Container> secondGet = firstGet.getOrDefault(c1.getKey().getValue(), new HashSet<Container>());
			firstGet.putIfAbsent(c1.getKey().getValue(), secondGet);
			secondGet.add(c1);
	
			Map<Integer, Set<Container>> firstGet1 = map2.getOrDefault(1L, new HashMap<Integer, Set<Container>>());
			map2.putIfAbsent(1L, firstGet1);
			Set<Container> secondGet1 = firstGet1.getOrDefault(c2.getKey().getValue(), new HashSet<Container>());
			firstGet1.putIfAbsent(c2.getKey().getValue(), secondGet1);
			secondGet1.add(c2);
	
			Diff diff = javers.compare(map1, map2); //0 diffs - NOT OK

			Diff diff2 = javers.compare(map1.get(1L), map2.get(1L)); //0 diffs - NOT OK

			Diff diff3 = javers.compare(map1.get(1L).get(1), map2.get(1L).get(1)); //0 diffs - NOT OK

			Diff diff4 = javers.compare(map1.get(1L).get(1).iterator().next(), map2.get(1L).get(1).iterator().next());	//this is OK
	
			int breakpoint = 0;
	
		}
	
	
	}

**Comment by bartoszwalacik** [comment]
well, could you please come up with a failing test which reproduces the issue ? You can write it on Javers fork. 

And could you change the title of this issue to sth more meaningful? Is it a bug report or feature request?

**Comment by bojanv55** [comment]
Well, in code you have a test. In case that I compare 2 different objects (last line = diff4) - it can find that those 2 objects are different. But as soon as I put those objects (different objects) in a HashSet (diff3) - javers is treating two sets as identical ones -- i suppose this should not be the case?

**Comment by bartoszwalacik** [comment]
'Map<Long, Map<Integer, Set<Container>>>' ???
Javers supports nested generics to some extent but not sth like this...

Javers is a tool for **domain objects** versioning
And never wont' support all fancy structures that can be coded in Java

**Comment by bartoszwalacik** [comment]
@iurylira please don't comment on closed task, btw is your comment connected somehow to this task? it was closed in 2015
