### ISSUE TITLE
Audit of the first level entities generic form

### ISSUE THREAD

**Issue by phelypp** [javers/javers#189]
Good morning friends,

I have a doubt.

It is possible only audit the first level of the entity. Currently implementing this recursively. Entity attributes are the main entity audit only the key.

I needed to make generic form. I would not want to set up one by one entity

example

@Entity
@Table(name = "USUARIO")
public class Usuario {

	@Id
	@SequenceGenerator(name = "USUARIO_SEQ", sequenceName = "USUARIO_SEQ", initialValue = 1, allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "USUARIO_SEQ")
	@Column(name = "CDUSUARIO", nullable = false)
	private Long codigo;
	

    @Column(name = "DELOGIN", nullable = false, length = Usuario.TAMANHO_MAXIMO_LOGIN)
	private String login;

	@Index(name = "IDX_USU_DESENHA")
	@Column(name = "DESENHA", length = Usuario.TAMANHO_MAXIMO_SENHA)
	private String senha;

	@Column(name = "CDGRUPO")
	private Grupo grupo;
}

@Entity
@Table(name = "GRUPO")
public class Grupo  {

	@Id
	@SequenceGenerator(name = "GRUPO_SEQ", sequenceName = "GRUPO_SEQ", initialValue = 1, allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GRUPO_SEQ")
	@Column(name = "CDGRUPO", nullable = false)
	private Long codigo;
	
	@Index(name = "IDX_GRUPO_NMGRUPO")
	@Column(name = "NMGRUPO", nullable = false, length = Grupo.TAMANHO_MAXIMO_NOME_GRUPO)
	private String nome;

	@Column(name = "FLADMIN", nullable = false, length = 1)
	@Type(type = SimNaoType.NOME_TIPO)
	private boolean admin = Boolean.FALSE;

	@Column(name = "CDUSUARIO")
	private Usuario usuario;
		
}

**Comment by bartoszwalacik** [comment]
Hi @phelypp, if you dont want to audit some field , simply put javers @DiffIgnore annotation on it

**Comment by phelypp** [comment]
Ok, I get it, but our system and very complex and has many hibernate entities mapped with nested entities as well.
We would like to do something generic, audit only the first level, the fields of the entities
nested can be disregarded in the audit. This is very important for our system, it is possible to implement this setting?

Thank you

**Comment by bartoszwalacik** [comment]
We could implement feature which allows you to limit graph depth in object graph building algorithm.
But, honestly, this feature isn't very high in our backlog.

**Comment by bartoszwalacik** [comment]
see new @ShallowReference and @DiffIgnore class-level annotations,
released in JaVars 1.4.11
http://javers.org/documentation/domain-configuration/#class-level-annotations
maybe it could help
