### ISSUE TITLE
Do not compare child entities between different parents?

### ISSUE THREAD

**Issue by vcvetkovik** [javers/javers#194]
I have a parent entity which contains a list of child entities. This is a specific case where I cannot use the primary key of the child entity as an entity id. I need to use one of the other fields which is unique for the parent but, entity with same field value can exists into other parent nodes. What should I do to compare the children elements as an entities (added, changed, removed) but avoid comparison with children from other parents? For example, if following two versions are given:

![image](https://cloud.githubusercontent.com/assets/9682562/9536294/6961dc18-4d2a-11e5-9bd8-de5e544dda01.png)

instead of reporting a value change on child1 I would like to receive that 1) child1 is removed from the firstParent and 2) child1 is added to the secondParent.

**Comment by bartoszwalacik** [comment]
so you have non-unique id?
think you have to build coposite (and then unique) id from two fields

currently Javers doesnot support composite field Id but you can uset bean-style mapping and getters, i.e.

```
@Id
String getUniqueId(){
   return localId+ parentId;
}

**Comment by vcvetkovik** [comment]
Yes, that is one of the solutions that I have been thinking of. Now when I know that I'm not missing something will try this. 
Thank you!
