### ISSUE TITLE
EmbeddedId

### ISSUE THREAD

**Issue by mdf123** [javers/javers#195]
The entities in my project all have @EmbeddedId (compount primary key) no @Id.
When I try to use javers on them I get Class '<>' mapped as Entity has no Id property.
Is it somehow possible to to use javers with @EmbeddedId? If yes, how?

**Comment by bartoszwalacik** [comment]
What is a type of these id objects. Is it some kind of value objects like
 ```
Person {
  String name;
  Sting login;
}
```
?

**Comment by mdf123** [comment]
Hello,

it is this class

@Embeddable
public class EntityPK implements Serializable {

    @Column(columnDefinition = "NUMBER(14)")
    private Long id;
    @Column(columnDefinition = "NUMBER(4)")
    private Integer dienststellenNr;


Used like this

@EmbeddedId
private EntityPK id;


Regards,

Hans M. Rupp

 

 

 

-----Ursprüngliche Mitteilung----- 
Von: Bartosz Walacik <notifications@github.com>
An: javers/javers <javers@noreply.github.com>
Cc: mdf123 <hansrupp@aol.com>
Verschickt: Do, 3 Sept 2015 7:06 pm
Betreff: Re: [javers] EmbeddedId (#195)


 
What is a type of these id objects. Is it some kind of value objects like
  
Person {
  String name;
  Sting login;
}

  
?

**Comment by bartoszwalacik** [comment]
Makes sense, i will add support for EmbeddedId

**Comment by bartoszwalacik** [comment]
fixed in release 1.3.5
