### ISSUE TITLE
Is it possible to exclude globalId from Json? Thanks

### ISSUE THREAD

**Issue by jefferyyuan** [javers/javers#196]
Hi, Dear Javers Devs:

I am trying to use javers, call javers.getJsonConverter().toJson(diff) to get the diff as json string and store it  in db and show it to user.
I am wondering whether we can exclude the globalId property from json string.

Thanks very much for your help.

    {
      "changeType": "ValueChange",
      "globalId": {
        "valueObject": "Person"
      },
      "property": "login",
      "left": "tommy",
      "right": "tommy1"
    },

**Comment by bartoszwalacik** [comment]
Hi jeffery, you can serialize diffs to JSON and store them it in a DB on your own, but it's not recommended approach. We recommend using `javers.commit()` function, which stores your diffs in your database using `JaversRepository` abstraction.

Then you can use JQL (see http://javers.org/documentation/jql-examples/) to query for changes and snapshots.

**Comment by bartoszwalacik** [comment]
also, take a look at http://javers.org/documentation/repository-examples/#change-log
for Change list processing/formatting

**Comment by bartoszwalacik** [comment]
if you still need some help, catch us on https://gitter.im/javers/javers chatroom
