### ISSUE TITLE
javers compare is throwing exception when comparing two String arrays

### ISSUE THREAD

**Issue by dmmiller612** [javers/javers#199]
Javers javers = JaversBuilder.javers().build();
        javers.compare(new String[]{"a", "b"}, new String[]{"a", "b"});

Currently the above code is throwing this exception:
 CLASS_NOT_MANAGED JaVers runtime error - given javaClass '[Ljava.lang.String;' is mapped to ArrayType, ManagedType expected .

I am currently using version 1.3.4.

**Comment by dmmiller612** [comment]
Looks like this may be by design, which is completely fine since you can make a direct equal comparison. I just wanted to make sure.

**Comment by bgalek** [comment]
I think you should compare entities (managed classes) here, exactly as exception says :)

**Comment by bartoszwalacik** [comment]
Will check it , pretty  sure that works for lists

**Comment by bartoszwalacik** [comment]
okay, so we have a feature for wrapping top level containers into Entities. It works for collections but not yet for Arrays.

If you would like to contribute a Pull Request, this issue is easy to solve in LiveGraphFactory.wrapTopLevelContainer()

**Comment by dmmiller612** [comment]
sure I'll check it out.

**Comment by bartoszwalacik** [comment]
released in v 1.3.8
