### ISSUE TITLE
Add support for retrieving whole array in a change of type ArrayChange

### ISSUE THREAD

**Issue by tomazic89** [javers/javers#202]
Where ArrayChange is detected the change should offer methods: 'getLeftArray()' and 'getRightArray()' which return the whole array of old/new entity.

**Comment by bartoszwalacik** [comment]
think we could do it also for ListChange, SetChange and MapChange

**Comment by akrystian** [comment]
ArrayChange currently store only changes (not exact arrays). Implementing your proposition require change in model (and changes can affect in performance). It looks like a corner case.

**Comment by SHxKM** [comment]
This would actually be a quite a useful feature for use cases where individual changes **within** the array need to be identified. Right now the output of `ListChange` is:

```
ListChange{ 'yyy/generationKinds.xxx' collection changes :
  0. 'x2.s' changed to 'x3.s'
  1. 'x2.m' changed to 'x3.m'
  2. 'x3.s' removed
  3. 'x3.m' removed }
```

Unless I'm missing something and there's a way to check each list item's value, or for example its size.

**Comment by bartoszwalacik** [comment]
@SHxKM this issue is closed, you can open a new , clean issue if you want
