### ISSUE TITLE
JaVers objects should be Jackson friendly

### ISSUE THREAD

**Issue by igler** [javers/javers#205]
Serialize JaVers changes <code>List&lt;Change></code> through Jackson. Snapshots <code>List&lt;CdoSnapshot></code>already work.

**Comment by bartoszwalacik** [comment]
today I'll release javers 1.3.9, int this version
exception `AFFECTED_CDO_IS_NOT_AVAILABLE JaVers runtime error` when serializing Changes to JSON using Jackson is fixed.

Still, JSON output created by Jackson will be very verbose as it simply uses Jackson defaults.
Neat nad consice JSON serialization of JaVers objects can be easily done using JaVers internal JSON mapping engine (based on Gson) - `javers.getJsonConverter().toJson(...)`

**Comment by igler** [comment]
Sounds good. I'll stay tuned and let you know how things go.

**Comment by bartoszwalacik** [comment]
check fresh 1.3.9 release

**Comment by bartoszwalacik** [comment]
check fresh 1.3.9 release

**Comment by bartoszwalacik** [comment]
check fresh 1.3.9 release

**Comment by igler** [comment]
Works perfect! Using the following code JSON-output is nice and smooth:
<pre><code>@RequestMapping(value = "/{id:[0-9]+}" + ChangeLinks.CHANGES, method = RequestMethod.GET)
public ResponseEntity&lt;List&lt;Change>> getChangesOfLocation(@PathVariable("id") Location location) {
		
    List<Change> changeList = javers
        .findChanges(QueryBuilder.byInstanceId(location.getId(), PublicLocation.class).build());
</code></pre>

BTW, how can I influence how changes on references are rendered in "left" and "right" properties? Does it eventually work with Spring  data-projections?

**Comment by bartoszwalacik** [comment]
well, since you are not using JaVavers to build JSON, it's rather a question to spring-mcv or jackson,
so it's on your side.

That's why I recommend using Javers to building JSON. JaVers creates neat, concise and customizable JSON.

In Spring controller you can do it quite easily:

```
@RequestMapping(...)
@ResponseBody
public String getChanges() {
    List changeList = javers.findChanges(...);
    return javers.getJsonConverter().toJson(changeList);
}
```

**Comment by igler** [comment]
What I meant was adjusting the following output through e.g. a <code>CustomPropertyComparator</code> (http://javers.org/documentation/diff-configuration/):

<pre><code>"left": {
      "cdoId": 2,
      "cdoClass": {
        "clientsClass": "....LocationNetwork",
        "idProperty": {
          "name": "id",
          "type": "java.lang.Long",
          "genericType": "java.lang.Long",
          "hasTransientAnn": false
        }
        ...
   ...
</code></pre>

Is it possible to retrieve the name of the LocationNetwork object and place it inside the "left"-property as a string?

**Comment by igler** [comment]
... did the following:
<pre><code>public class LocationNetworkComparator implements CustomPropertyComparator&lt;LocationNetwork, ValueChange> {

	@Override
	public ValueChange compare(LocationNetwork leftNetwork, LocationNetwork rightNetwork, GlobalId globalId, Property property) {

		String leftNetworkName = leftNetwork.getName();
		String rightNetworkName = rightNetwork.getName();

		return new ValueChange(globalId, property, leftNetworkName, rightNetworkName);
	}
}</code></pre>

But unfortunately <code>leftNetwork</code> and <code>rightNetwork</code> are both <code>null</code>. Tried it with <code>.withObjectAccessHook(new HibernateUnproxyObjectAccessHook())</code> but not better.

**Comment by igler** [comment]
OK, got it now. It is important that the comparator code is written the following way when the third situation occurs:
<pre><code>public class LocationNetworkComparator implements CustomPropertyComparator<LocationNetwork, ValueChange> {

	@Override
	public ValueChange compare(LocationNetwork leftNetwork, LocationNetwork rightNetwork, GlobalId globalId, Property property) {

		String leftNetworkName = null;
		String rightNetworkName = null;

		if(leftNetwork != null)
			leftNetworkName = leftNetwork.getName();

		if(rightNetwork != null)
			rightNetworkName = rightNetwork.getName();

		return new ValueChange(globalId, property, leftNetworkName, rightNetworkName);
	}
}</code></pre>

**Comment by bartoszwalacik** [comment]
Ok, good to hear that CustomComparators works for you

**Comment by igler** [comment]
You can close this issue if you want to.
