### ISSUE TITLE
QueryBuilder can take abstract class

### ISSUE THREAD

**Issue by igler** [javers/javers#209]
Currently only non-abstract classes work for the following resolution of changes: 
<pre><code>javers.findChanges(QueryBuilder.byClass(NotAnAbstractEntity.class).build());</code></pre> If I try <code>byClass</code> with an abstract class nothing is returned. It would be nice if all subclasses are queried and changes on all of them are returned.

**Comment by bartoszwalacik** [comment]
Agreed that it would be nice, but I cant see obvious way of effective implementation of this query (without running table full scans)...

**Comment by bartoszwalacik** [comment]
In Java , there is no easy way to find all subclasses af a given class using Reflection API

**Comment by igler** [comment]
Maybe helpful: https://github.com/ronmamo/reflections

**Comment by bartoszwalacik** [comment]
Yeah , there  are some libs for that but I really  want to keep JaVers lightweight.

**Comment by igler** [comment]
BTW, how can I get all changes of all entities, ideally with Paging support?

**Comment by bartoszwalacik** [comment]
for now you cant, but it can be easily implemented, also we have a task about paging https://github.com/javers/javers/issues/179, ideal for contribution

**Comment by bartoszwalacik** [comment]
let me know if uou would like to contribute these two things

**Comment by igler** [comment]
I think extending
<pre><code>public static QueryBuilder byClass(Class requiredClass)</code></pre>
to
<pre><code>public static QueryBuilder byClass(Class... requiredClasses)
</code></pre>
could help so I can submit a list of classes and do reflections on my side?

**Comment by bartoszwalacik** [comment]
looks like a good idea

**Comment by igler** [comment]
See https://github.com/javers/javers/pull/246

**Comment by bartoszwalacik** [comment]
ok, but there is no implementation and no tests in this PR ...

**Comment by igler** [comment]
Method in line 38 of https://github.com/igler/javers/blob/b66bae9c7bd4add9269f023ba403ed25326398d6/javers-core/src/main/java/org/javers/repository/jql/QueryBuilder.java is additional.

**Comment by bartoszwalacik** [comment]
I've seen this method, but this is only a query.
you should write a test for this feature (in JaversRepositoryE2ETest),
second thing, looks like implementation for this Query in QueryRunner is missing

**Comment by bartoszwalacik** [comment]
fixed in release 2.6.0
see http://javers.org/release-notes/
