### ISSUE TITLE
commitMetadata with author and commitDate in Change object

### ISSUE THREAD

**Issue by igler** [javers/javers#210]
<code>CdoSnapshot</code> has rendering of author and commitDate. It would be nice if a <code>Change</code> object has them too in its <code>commitMetadata</code> property when you do not use the <code>javers.getJsonConverter().toJson(...)</code>

**Comment by bartoszwalacik** [comment]
as far as i know, it has it, e.g.
```
  {
    "changeType": "NewObject",
    "globalId": {
      "entity": "org.javers.core.cases.Case208$SimpleTypes",
      "cdoId": "1"
    },
    "commitMetadata": {
      "author": "anonymous",
      "commitDate": "2015-09-30T21:43:55",
      "id": 1.00
    }
  }
```

**Comment by bartoszwalacik** [comment]
I mean it is present in JSON when this json is produced by javers, if you are using jackson or sth else, maybe it is a configuration issue of your serializer?

**Comment by igler** [comment]
Well it works when exporting a snapshot. The difference when exporting a change is, that author etc. are wrapped inside a "reference" (see screenshots).

Change:
![metadata_change](https://cloud.githubusercontent.com/assets/313565/10263370/ad6c9144-69ec-11e5-904e-52402f039acc.png)

Snapshot:
![metadata_snapshot](https://cloud.githubusercontent.com/assets/313565/10263371/b06c1982-69ec-11e5-8e0c-4406db949c25.png)

**Comment by bartoszwalacik** [comment]
yes, this is by design:
```public abstract class Change {
  private Optional<CommitMetadata> commitMetadata;
...
```
CommitMetadata only exists when you are fetching changes from JaversRepository.
When changes are calculated by `javers.compare()`, commitMetadata is empty.

Agreed that this `Optional` could be cleared in JSON output

**Comment by igler** [comment]
Using the <code>jackson-datatype-jdk8</code> module does not help as <code>Optional</code> in JaVers has its own implementation. Any suggestions how I can overcome this problem so metadata of <code>Change</code> is serialized?

**Comment by bartoszwalacik** [comment]
yes, thats because, many users still did'n upgraded to Java8

think you need to write Custom Deserializer for Jackson, see http://www.baeldung.com/jackson-deserialization
For now, I dont have plans to add Jackson support in Javers, but I'm eager to accept PR with such feature

**Comment by igler** [comment]
Writing a custom serializer for <code>Optional&lt;CommitMetadata></code> and manually register it in <code>Jackson2ObjectMapperBuilder</code> solved the problems. Thanks for you help, you can close the issue if you want to.
