### ISSUE TITLE
Complex objects issue

### ISSUE THREAD

**Issue by niclarcipretti** [javers/javers#211]
Hi,

I'm experiencing major performance issues when trying to audit complex objects with Javers. 
The main problem is that Javers gets the whole object with all its dependencies, and if those dependencies has other dependencies, it falls into an endless recursion that takes a lot of time. I was wondering if is there any way to make Javers record just the FK values for the dependencies instead of the whole nested object?

I'll try to clear that with an example:

Entity User
-Long id
-String login
-Person person

Entity Person
-Long id
-String name
-User registerUser

The tables would be like this:

User
-id PK
-login
-personId FK

Person
-id PK
-name
-userId FK

If I audit User, Javers will try to fetch the whole person, which has another user, that has another person, and this will go on and on untill the end of the recursion. Combine that with hibernate's lazy initialization of those dependencies, and we will have a bottleneck in the transaction. 
What I need is: if try to audit User, Javers get the User object, with its person having only the id attribute filled, ignoring the rest of the object, that, for User auditing, it's useless information.

What you guys think about this?

Cheers

Nick

**Comment by bartoszwalacik** [comment]
Quick answer : use @DiffIgnore on those properties you dont want to audit and Javers wont follw them

**Comment by niclarcipretti** [comment]
Hi @bartoszwalacik,

I can't do that, cause I need to know if the relation has changed (e.g the User's Person has changed).

What do you suggest? In your opinion, is this a weird use case?

Cheers

Nick

**Comment by bartoszwalacik** [comment]
take a look at https://github.com/javers/javers/issues/189
would it solve your problem?

**Comment by niclarcipretti** [comment]
Not really.  I don't need depth control. I need no depth at all. I think the best solution would be something like: @DiffIgnore(logId = true) where it would ignore the object and just log the id. So, when I retrieve it from Mongo, I just have to lazy initialize the object fetching it by its id. 
Too confusing? What is your opinion? 

Cheers 

Nick

**Comment by bartoszwalacik** [comment]
well, it could be done, think better name for this kind of annotation would be @ShallowReference

So JaVers would only log reference changes for this property but would stop building object graph from it. This ann could also work on class level.

Looks like it's not very hard to implement, maybe you could think about some contribution? I'm quite busy now with older isues waiting in the backlog ...

**Comment by floresek** [comment]
@Bartosz - additional property for @ShallowReference could be usefull - persistIfNotExists

If true, javers should persist the referenced object (so the whole referenced object should be passed)

if false - only referenced object id. If the object does not exists in javers DB, the exception should be thrown (only @Id of referenced object should be passed).

**Comment by bartoszwalacik** [comment]
so maybe you take look at javers codebase and consider contributing this feature? it shouldn't be very hard, and I can help if you approach some difficulties...

**Comment by bartoszwalacik** [comment]
see new @ShallowReference ann, released in JaVars 1.4.11

http://javers.org/documentation/domain-configuration/#class-level-annotations
