### ISSUE TITLE
Auditing native query events

### ISSUE THREAD

**Issue by niclarcipretti** [javers/javers#212]
Hi,

Is it possible to audit hibernate's native inserts and updates querys (using query.executeUpdate()) with Javers? 

Cheers 

Nick

**Comment by bartoszwalacik** [comment]
I dont know, maybe  with  some hibernate plugin... Currently javers does not know much about Hibernate

**Comment by niclarcipretti** [comment]
Hi @bartoszwalacik,

Once Javers knows hibernate's annotations, I thought someone already managed to do such thing. In fact, I'm using Javers with Hibernate/JPA and it works just fine. But I can't figure how to intercept this kind of event and treat it, it looks really complex.

If you come up with some good idea, please let me know. Meanwhile, I'll do my best here.

Cheers

Nick

**Comment by bartoszwalacik** [comment]
in fact, Javers understands JPA annotations :)
JaVers strives to be technology agnostic, and we dont want it to be thightly integrated with Hibernate or any other lib (maybe except Spring).

Think about biulding it using JaVers, Hibernate or your SQL driver should have some hooks.
