### ISSUE TITLE
Random ClassCastExceptions

### ISSUE THREAD

**Issue by peda** [javers/javers#218]
Hello,

I do have a structure of nested entity objects (similar to the large depth employee sample). Even if I re-run the application multiple times with the same data set the exception does not occur at every run - at some runs no exceptions happens, at some runs the exceptions occurs just once even though I'm comparing dozens of objects with nearly the same values (just some primitives do have different values) and at some runs nearly every diff throws the exception.

```
 java.lang.ClassCastException: com.XXX.XXX.domain.MyObject cannot be cast to org.javers.core.metamodel.object.GlobalId
	at org.javers.core.graph.ObjectNode.getReference(ObjectNode.java:75)
	at org.javers.core.diff.RealNodePair.getRightGlobalId(RealNodePair.java:61)
	at org.javers.core.diff.appenders.ReferenceChangeAppender.calculateChanges(ReferenceChangeAppender.java:25)
	at org.javers.core.diff.appenders.ReferenceChangeAppender.calculateChanges(ReferenceChangeAppender.java:15)
	at org.javers.core.diff.DiffFactory.appendChanges(DiffFactory.java:142)
	at org.javers.core.diff.DiffFactory.appendPropertyChanges(DiffFactory.java:132)
	at org.javers.core.diff.DiffFactory.createAndAppendChanges(DiffFactory.java:114)
	at org.javers.core.diff.DiffFactory.create(DiffFactory.java:65)
	at org.javers.core.diff.DiffFactory.compare(DiffFactory.java:58)
	at org.javers.core.JaversCore.compare(JaversCore.java:94)
	at com.XXX.XXX.util.audit.AuditLogEntry.createFromRecord(AuditLogEntry.java:139)
```

**Comment by bartoszwalacik** [comment]
how can I reproduce it?

**Comment by peda** [comment]
that's the tricky question ;-) any suggestions?

**Comment by bartoszwalacik** [comment]
I need more data to solve this, stack trace is not enought in this case.
Especially, i need to know how your domain objects look like.

Failing test would be nice.

**Comment by peda** [comment]
I'll try to reproduce it in a test project - but I will definitely need a few days for that because I'm really busy at the moment and need to extract that test case from a larger project.

**Comment by peda** [comment]
quick question: is javers.compare(oldObj, newObj) thread-safe? I figured out that it might happen that the same javers instance was used by multiple threads at the same time

**Comment by bartoszwalacik** [comment]
ok, no hurry, 
javers.compare() is designed to be thread-safe, but in fact, the case you are describing looks like some concurrency issue...

**Comment by peda** [comment]
I managed to isolate the issue in a smaller project - but as it does still contain some business logic I've sent you the test project as email to javers@javers.org - I hope that works for you, if it doesn't please let me know. Thanks :-)

**Comment by bartoszwalacik** [comment]
Ok , will do

**Comment by bartoszwalacik** [comment]
ok, exception reproduced on my laptop, when running your test

**Comment by peda** [comment]
thanks, that's great to know :-)

**Comment by bartoszwalacik** [comment]
lombok :( 
you need a special plugin even just to compile it

**Comment by peda** [comment]
yes, but therefore you don't have to write any getters and setters on your own ;-)

**Comment by bartoszwalacik** [comment]
yes, I know what it is, but I really dont like it, 
nevermind, think i found some issue in javers-core, we need to improve thread-safety in TypeMapper

**Comment by bartoszwalacik** [comment]
fix is ready, now I need some time for Maven Central sync, stay tuned

**Comment by peda** [comment]
Thank you so much - your dedication for this open source project is amazing. I'll give it a try as soon as it is available on maven central.

**Comment by bartoszwalacik** [comment]
Thanks! release 1.3.14 is now available in Maven Central. Check it out and don't forget to give as a stargazers https://github.com/javers/javers/stargazers if you like JaVers project :)

**Comment by peda** [comment]
Thanks I just tried it and it's working fine for me - I gave you a stargazer

Just one more thing I've noticed 1.3.14 does not run on JDK 7 any more as it's missing java.util.function.Function - is that a deiberate change? (Anyway I'm fine with it as I changed my project a few days ago to run with JDK 8)

**Comment by bartoszwalacik** [comment]
No its a mistake, i will fix it, thats because im trying to support java8 types and still beeing runnable on jvm7.
