### ISSUE TITLE
Find changes/snapshots by commit id

### ISSUE THREAD

**Issue by floresek** [javers/javers#219]
Hi,

In usual business case user often browses detailed changes done during an individual commit.

From performance point of view new QueryBuilder function would be useful:
startingFrom(CommitId commitId)
or (if it is hard to implement because of CommitId nature - string major.minor)
startingFrom(LocalDateTime date)

I current version to find changes done in a commit all changes have to be read from repository and than have to be filtered to the requested commit. 

The same API would be useful for finding snapshots.

Cheers
Mariusz

**Comment by bartoszwalacik** [comment]
make sense, looks like a good issue to start contributing to JaVers :)

**Comment by bartoszwalacik** [comment]
@florsek, rozwijam JaVersa praktycznie jednoosobowo w czasie wolnym, spójż na backlog https://github.com/javers/javers/issues 
W kolejce czeka masa sensownych tasków do zrobienia ale sam nie mam szans tego ogarnąć w tym roku. Fakty są takie, ze JaVers potrzebuje więcej commiterów, jeśli ma się rozwijać. Widzę, że Ty już nieźle się wgryzłeś w kod Javersa, znalazłeś kilka błędów, masz pomysły na nowe ficzery. Pomyśl czy nie chcesz zaangażować się też w development, społeczność OSS i JaVers zyskają na tym :)

**Comment by floresek** [comment]
Jak znajdę wolne moce przerobowe i będę w stanie coś sensownego zrobić, to postaram się przyłączyć.
A co do wgryzania, to nadal operuję przy powierzchni ;)

**Comment by mwesolowski** [comment]
cześć,

Javersa poznaję dopiero od wczoraj więc z góry przepraszam jeżeli napiszę jakieś głupoty. 
Chciałbym dodać możliwość filtrowania wyników zapytań po zakresie dat. Czy moglibyście mi pomóc w dwóch tematch? 

1. Do filtrowania po zakresie dat potrzebne jest rozszerzenie API __JaversRepository__. Zakładam, że publiczne API musi być wstecznie kompatybilne i zmiana istniejących sygnatur nie wchodzi w grę. Widzę kilka możliwości takiego rozszerzenia:
  * _bardzo słabe_ Dodam 3 kopie istniejących operacji __get\*StateHistory__:
    * pierwszą z dodatkowym parametrem __LocalDateTime to__
    * drugą z dodatkowym parametrem __LocalDateTime from__
    * trzecią z dodatkowym parametrami __LocalDateTime from__ i __LocalDateTime to__
  * _słabe_ Dodam kopię istniejących operacji __get\*StateHistory__ rozszerzoną o parametry __LocalDateTime from__ i __LocalDateTime to__. Jeżeli klient będzie chciał przekazać tylko jeden z nich, to w drugim będzie musiał ustawić _nulla_
  * _akceptowalne?_ Wprowadzę nowy byt __QueryParams__ (pewnie wraz z towarzyszącym mu __QueryParamsBuilderem__), który początkowo będzie przechowywał rzeczy takie jak limit ilości wyników i zakres dat. Filtrowanie po identyfikatorze/typie obiektu zostawiłbym jak jest. Dodam kopię istniejących operacji __get\*StateHistory__, w której parametr __int limit__ zostanie zastąpiony parametrem __QueryParams queryParams__.
2. Zastanawiam się jak nalepiej podejść do tematu obsługi daty początkowej w operacjach __get\*ChangeHistory__ z __JaversExtendedRepository__. Jeżeli po prostu przekażę tę datę dalej do analogicznej funkcji __get\*StateHistory__, to wynik będzie niepełny (gdy _newObjects == false_) lub wręcz nieprawdziwy (gdy _newObjects == true_). Na razie skłaniam się do pobrania listy snapshotów bez ograniczenia dolnego i przefiltrowania wników w __JaversExtendedRepository__.

pozdrawiam,
Michał

**Comment by bartoszwalacik** [comment]
Hej,
dobry pomysł!
Jest nawet ticket na to, który czeka na kontrybucję
https://github.com/javers/javers/issues/243
w tym tickecie zaproponowałem rozbudowanie JQL API o coś takiego:
QueryBuilder.byInstanceId(Object localId, Class
entityClass).from(Date).to(Date)

Nie myślałem jeszcze jak to przełożyć na API JaversRepository, nie
dodawałbym nowych metod.
Rozwiązanie, które proponujesz, czyli zastąpienie int limit, przez nowy
ValueObject (QueryParams) wydaje się sensowne.

Temat jak zaimplementować niżej SQL i query do Monogo, wydaje się dość
prosty,
fetch wszystkich rekordów będzie mało wydajny. Zaimplementowałbym to
podobnie jak limit, czyli używając po prostu between na commit.date.
Dlaczego wynik miałby być nieprawdziwy gdy *newObjects == true*?


pisz do mnie ba bwalacik@gmail.com

pozdr Bartek


W dniu 23 grudnia 2015 15:58 użytkownik Michał Wesołowski <
notifications@github.com> napisał:

**Comment by pawelszymczyk** [comment]
Hej, 

@mwesolowski na branchu 243-timeframe jest przygotowany fake-date provider który zapewne przyda Ci się do testów, jak na razie tylko tyle zrobiłem w tym temacie ;)

Jeżeli będziesz potrzebował pomocy to możesz pisać na pawel.szymczyk90@gmail.com.

pozdr Paweł

**Comment by bartoszwalacik** [comment]
see http://javers.org/documentation/jql-examples/#commit-date-filter
see http://javers.org/documentation/jql-examples/#skip-filter

Issue for query by CommitId is moved here: https://github.com/javers/javers/issues/309
