### ISSUE TITLE
ValueObject changes would be reported when quering for entity changes

### ISSUE THREAD

**Issue by floresek** [javers/javers#220]
Hi,

In current version when calling:
```java
javers.findChanges(
                QueryBuilder.byValueObjectId(entityId, entityClass, path)
                        .withNewObjectChanges(true)
                        .build());
```
ValueObject changes are reported in shallow level:
* VO reference change
* VO collection changed
Unfortunately changes done in VO properties are not reported.

If an entity has got many Value Objects (by references, in collections) to get all changes done on the entity VO properties many additional complex logic and queries have to be done, to resolve Value Objects changes (starting from resolving VO properties, via resolving what happen to them, even resolving current size of collections, to query if VO from collection was changed etc.)

Because of Value Objects nature (there are parts of entity) it would be VERY USEFUL to be able to query form VO changes as following:
```java
javers.findChanges(
                QueryBuilder.byValueObjectId(entityId, entityClass, path)
                        .withNewObjectChanges(true)
                        .withValueObjectChanges(true)
                        .build());
```
Cheers
Mariusz

**Comment by bartoszwalacik** [comment]
Maybe API should simply looks like that:
```
javers.findChanges(
                QueryBuilder.byValueObjectId(entityId, entityClass, "*")
                        .build());
```

and that would give you changes done on all VO embedded in given entity

**Comment by palto** [comment]
I would seriously like this implemented. I already managed to add javers into my application but had to remove it since I can't use it to generate "last modified" time for a given entity because it has ValueObjects.

**Comment by palto** [comment]
If anyone else was wrestling with the same problem as me, I figured out that you can detect changes when calling `javers.commit(author, entity).getChanges().isEmpty()`. This however means that you can't use the auto proxying of repositories feature.

**Comment by bartoszwalacik** [comment]
OK, I'am moving this issue higher in our backlog

**Comment by bartoszwalacik** [comment]
new filter is added in release 2.1.0
see http://javers.org/documentation/jql-examples/#child-value-objects-filter
