### ISSUE TITLE
Cannot compare an object with an Optional<List<*>> field

### ISSUE THREAD

**Issue by asaf-romano** [javers/javers#225]
When trying to compare an object that has an Optional<List<String>> field, I got the following exception:
``
Caused by: org.javers.common.exception.JaversException: UNSUPPORTED_OPTIONAL_CONTENT_TYPE JaVers runtime error - ListType{baseType:'java.util.List<java.lang.String>'} is not supported as Optional<> content type
``

**Comment by bartoszwalacik** [comment]
it juts says that Optional of List is not supported, i dont think Javers it would be. Optional of List looks like too complex model, why dont you just use empty list instead of Optional.empty()?

**Comment by asaf-romano** [comment]
It's a view over Other People's Model, in which there's actually a difference between the two cases. :)

**Comment by bartoszwalacik** [comment]
Sorry, i cant help you, it looks like a corner case
