### ISSUE TITLE
CLASS_NOT_MANAGED exception

### ISSUE THREAD

**Issue by igler** [javers/javers#227]
I am getting the following error when trying to compare two entities:
<pre><code>JaversException: CLASS_NOT_MANAGED JaVers runtime error - given javaClass '....eip.location.EmonsLocation' is mapped to CustomType, ManagedType expected</code></pre>

Have tried:
<pre><code>.registerEntity(new EntityDefinition(EmonsLocation.class))
.registerCustomComparator(new EmonsLocationJaVersComparator(), EmonsLocation.class)</code></pre> in <code>TransactionalJaversBuilder</code>.  The comparator looks like:

<pre><code>public class EmonsLocationJaVersComparator implements CustomPropertyComparator&lt;EmonsLocation, ValueChange> {

	@Override
	public ValueChange compare(EmonsLocation left, EmonsLocation right, GlobalId globalId, Property property) {

		if(left != null && right != null && left.equals(right))
			return null;
		else {
			String leftName = null;
			String rightName = null;

			if (left != null)
				leftName = left.getIdentifier();

			if (right != null)
				rightName = right.getIdentifier();

			return new ValueChange(globalId, property, leftName, rightName);
		}
	}
}</code></pre>

<code>EmonsLocation</code> is a concrete class with <code>@Entity</code> annotation.

**Comment by bartoszwalacik** [comment]
CustomComparators are intended to use for Value types and not for whole Entities,
they are used by diff algorithm to calculating property-to-property diff

**Comment by bartoszwalacik** [comment]
and since you have registered your type as Entity, there is a conflict

**Comment by igler** [comment]
The point is that in my scenario locations are administrated by other locations. I want to trigger when some changes this administration behavior. How can I solve this? The entity has a relation to another location:
<pre><code>@ManyToOne
protected EmonsLocation administratedBy;</code></pre>

**Comment by bartoszwalacik** [comment]
so you want to calculate a change on Locatoin when another Location is changed?

**Comment by igler** [comment]
Yes, when I change the <code>administratedBy</code> reference. The entry in left/right of the change should be a special combination of locationNumber and town. That's why I implemented a <code>CustomPropertyComparator</code>.

**Comment by bartoszwalacik** [comment]
Im affraid that it cant be calculated now in JaVers without changing your domain model, CustomPropertyComparator can only be used for comparing Entity or ValueObject properties. To solve your case, we would need CustomEntityComparator ...

**Comment by igler** [comment]
But CustomEntityComparator isn't implemented yet in JaVers, right?

**Comment by bartoszwalacik** [comment]
Not yet implemented but we dont need new change types. It would act like CustomPropertyComparator, which uses existing change types

**Comment by igler** [comment]
Do you think that it is a complex task to implement or can I do this contribution?

**Comment by bartoszwalacik** [comment]
I think you could contribute it, it could be done simillary to CustomPropertyComparator , first think about API changes and design of this feature that we can disqus...

**Comment by igler** [comment]
So do we need a <code>CustomEntityComparator</code> beside <code> CustomPropertyComparator</code>?

**Comment by igler** [comment]
Upgraded to latest 1.3.17 and there is no error printed any more. Unfortunately the custom comparator <code>EmonsLocationJaVersComparator</code> I have written does not jump in.

**Comment by bartoszwalacik** [comment]
latest is 1.3.20
do you have problems with your CustomPropertyComparator implementation? what kind of?

**Comment by igler** [comment]
Tried with 1.3.20 but not better. The problem is that a <code>CustomPropertyComparator</code> is not called. Have others but these work fine. Let's take the following entity-extract:
<pre><code>public abstract class Location extends AuditEntity {
    ...
    @ManyToOne
    protected Location administration;
    ....
}

public class EmonsLocation extends Location {
    ....
    @ManyToOne
    private LocationNetwork network;
    ....
}</code></pre>

Have written a <code>CustomPropertyComparator</code> for <code>LocationNetwork</code> and registered it though <code>registerCustomComparator(new LocationNetworkJaVersComparator(), LocationNetwork.class)</code>. This works fine. Also did this on <code>EmonsLocation</code> plus <code>registerEntity(new EntityDefinition(EmonsLocation.class))</code> but it is not called when changing the administration property.

**Comment by igler** [comment]
With 1.3.20 and a change to <code>registerEntity(new EntityDefinition(Location.class))</code> (which brought the upper error when doing so) and modifying <code>CustomPropertyComparator</code> accordingly it works now. You can close this issue if you want to.
