### ISSUE TITLE
Dependency on slf4j causing conflicts when deploy on WSO2 AS 

### ISSUE THREAD

**Issue by cwichoski** [javers/javers#233]
Hi, 

When running javers 1.3.12 on WSO2 AS 5.2.1 we got follow exception:

```log
 java.lang.LinkageError: loader constraint violation: when resolving method 
"org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" 
the class loader 
   (instance of org/wso2/carbon/webapp/mgt/loader/CarbonWebappClassLoader) of the current class, 
   org/slf4j/LoggerFactory, 
and the class loader 
   (instance of org/eclipse/osgi/internal/baseadaptor/DefaultClassLoader) for resolved class, 
   org/slf4j/impl/StaticLoggerBinder, 
have different Class objects for the type LoggerFactory; 
used in the signature
    org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:299)
    org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:269)
    org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
    org.javers.core.JaversBuilder.&lt;clinit&gt;(JaversBuilder.java:61)
    ...
```

Analysing the problem, can you use java.util.logging.Logger instead of LoggerFactory, this way the javers can run without conflicts in any web container too.

Best regards

**Comment by bartoszwalacik** [comment]
Nope, we use slf4j by design,  its well adopted standard for logging api in java. Its not concrete implementation but only abstraction layer designed to be easily integrated with various logging libraries. Did you tried to solve this problem by configuration proper bridge at your side?

**Comment by bartoszwalacik** [comment]
here is the instruction how to configure slf4j to java.util.logging bridge:
http://www.slf4j.org/images/legacy.png
