### ISSUE TITLE
Feature: IdFilter with Date

### ISSUE THREAD

**Issue by xeraa** [javers/javers#243]
Goal: Get all changes of a specific object (we have the class name and ID) for a given time range. We could just get all changes and throw away the ones outside our timeframe, but this sounds really inefficient.

First, we wanted to wrap the Javers Diff as discussed in #188. But then I saw that all the relevant information is already included in the database (we're using MongoDB). Would you be interested in a pull request something like the following or is there a better approach?

* Currently available: `javers.findChanges(QueryBuilder.byInstanceId(Object localId, Class entityClass).build());`
* Since query, giving you all the changes for that object since the given date: `javers.findChanges(QueryBuilder.byInstanceId(Object localId, Class entityClass, Date since).build());`
* Timeframe query, giving you all the changes for that object within the given timeframe: `javers.findChanges(QueryBuilder.byInstanceId(Object localId, Class entityClass, Date from, Date to).build());`

**Comment by bartoszwalacik** [comment]
Having a timeframe query could be a useful feature. We are open to your Pull Request.
Please use builder convention for query API, so sth like this:
`QueryBuilder.byInstanceId(Object localId, Class entityClass).from(Date).to(Date)`

Also rememner that this change should be implemented for both `MongoRepository` and `JaversSqlRepository`. The best place for integration tests is `JaversRepositoryE2ETest` as it is run using all `JaversRepository` implementations.

Let me know if you will need some support in design or coding

**Comment by bartoszwalacik** [comment]
released just now, in version 1.4.2, see http://javers.org/documentation/jql-examples/#commit-date-filter
