### ISSUE TITLE
Selectively apply changes from one object to another

### ISSUE THREAD

**Issue by huksley** [javers/javers#251]
Hello!

Is there any way to copy changes from one to other, including nested collections and objects?

Something like that:

    changes = javers.compare(tommyOld, tommyNew);
    applyAllChanges(tommyOld, changes);
    applyChanges(tommyOld, new MyChangesFilter() { ... });

**Comment by huksley** [comment]
#question

**Comment by bartoszwalacik** [comment]
short answer: no
Javers does not alter user objects, I dont think it should

**Comment by bartoszwalacik** [comment]
lot of things can go wrong when you would try to alter user objects, Javers-core cannot take this responsibility
