### ISSUE TITLE
 right to left language json saving problem

### ISSUE THREAD

**Issue by yong86** [javers/javers#252]
when saving data to snapshot table , I got "{
  "customerName": "??? ????? ???? ???? ???????",
   "customerId": 300,
  "customerType": 1,
}
First I know that it may not be an issue regarding javers.
Second, I'm using spring data jpa, right to left language in customer name and I handle this situation in SQLSERVER by changing customerName colum type to nchar, but here I don't know what to do?

**Comment by yong86** [comment]
Thanks for your reply.
No,I don't use any exotic charset, but as i said before, SQLSERVER save the customer with ??? if the column type is varchar not nvarchar.Also, when debugging the customer name is appearing correct in the object.

**Comment by bartoszwalacik** [comment]
so you have altered type of columns in jv_snapshot table, from varchar not nvarchar?

**Comment by yong86** [comment]
No, I mean in the customer table

**Comment by bartoszwalacik** [comment]
Javers doesn't care about your castomer table, try to find out what is unusual in your customer Java objects which is causing this strange problem ...

**Comment by yong86** [comment]
I just tell you the only case when I got these question marks and it is not related to Javers case in any way.

**Comment by bartoszwalacik** [comment]
sorry but I dont understand you, what do you mean by right to left language? is this Arabic or something? Try to write a failing test which isolates your case, you can push it to your fork of Javers repository

**Comment by yong86** [comment]
Sorry for letting you misunderstand my issue.I mean Arabic language.

**Comment by bartoszwalacik** [comment]
@yong86, honestly, I dont know how right-to-left languages are supposed to work in Java.
If you want to have right-to-left language support in JaVers, think about contributiong a Pull Request
