### ISSUE TITLE
 ENTITY_INSTANCE_WITH_NULL_ID JaVers runtime error

### ISSUE THREAD

**Issue by yong86** [javers/javers#253]
Hello,
I have a one to many relation between customer and customer attributes tables:
customer model: 

    @Entity
    @Table(name = "CUSTOMER")
    @JsonIdentityInfo(generator = ObjectIdGenerators.None.class, property = "@id", scope =      Customer.class)
    public class Customer implements Serializable {
	@Id
	@SequenceGenerator(name="SEQ_GEN", sequenceName="SEQ_CUSTID",  allocationSize=1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="SEQ_GEN")
	//@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "CUSTOMER_ID")
	private Long					customerId;

	@Column(name = "CUSTOMER_EMAIL")
	private String					customerEmail;

	@Column(name = "CUSTOMER_NAME", columnDefinition = "nvarchar(500)", nullable = false)
	private String					customerName;

	@OneToMany(mappedBy = "customer", fetch = FetchType.EAGER,cascade = CascadeType.ALL)
	@PrivateOwned
	private List<CustomerAttr>		customerAttrs;

second model:

    @Entity
    @Table(name = "CUSTOMER_ATTRS")
    @JsonIdentityInfo(generator = ObjectIdGenerators.None.class)
    public class CustomerAttr  implements Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "CUSTOMER_ATTR_ID")
	private Long		customerAttrId;

	@Column(name = "ATTRIBUTE_VALUE", columnDefinition = "nvarchar(500)")
	private String		attributeValue;

	@JsonIgnore
	@ManyToOne
	@PrimaryKeyJoinColumn(name = "CUSTOMER_ID")
	private Customer	customer;

	@Column(name = "CUSTOMER_ID")
	private Long		customerId;

when I'm trying to commit the customer only without any attributes ,I got this info + an exception:
> INFO org.javers.core.metamodel.type.TypeFactory - javersType of class im.data.model.Customer inferred as EntityType
 INFO org.javers.core.metamodel.type.TypeFactory - javersType of [class java.lang.Long] inferred as ValueType, it's used as id-property type
INFO org.javers.core.metamodel.type.TypeFactory - javersType of java.util.List<im.data.model.CustomerAttr> inferred as ListType from prototype ListType{baseType:'interface java.util.List'}
[qtp2101527076-48] INFO org.javers.core.metamodel.type.TypeFactory - javersType of java.util.List<im.data.model.BillingAccount> inferred as ListType from prototype ListType{baseType:'java.util.List<im.data.model.CustomerAttr>'}
[qtp2101527076-48] INFO org.javers.core.metamodel.type.TypeFactory - javersType of class im.data.model.CustomerAttr inferred as EntityType
[qtp2101527076-48] INFO org.javers.core.metamodel.type.TypeFactory - javersType of [class java.lang.Long] inferred as ValueType, it's used as id-property type

Exception: 
>ENTITY_INSTANCE_WITH_NULL_ID JaVers runtime error - Found Entity instance of class 'im.data.model.CustomerAttr' with null id

**Comment by bartoszwalacik** [comment]
when you are passing your objects to JaVers, they must have id. Exception is saying that they doesnt have id.
If you are using Hibernate, you have to do `javers.commit()` after Hibernate does its job with flushing objects to DB and incrementing sequences. 
Are you calling javers.commit() explicite or implicite using `@JaversAuditable` aspect?

**Comment by yong86** [comment]
I'm using eclipselink to get connection:




     Connection connection = this.getEntityManager().unwrap(java.sql.Connection.class)
and I updated the commit function:




     @Override
    public Commit commit(String author, Object currentVersion) {
    	System.out.println("test----------------------------------------");
    	Commit cm = delegate.commit(author, currentVersion);
    	JpaEclipseLinkConnectionProvider je = JpaEclipseLinkConnectionProvider.getInstance( );
    	entityManager = je.getEntityManager();
         entityManager.getTransaction().commit();
        return cm;
    }

**Comment by bartoszwalacik** [comment]
There is no support for EclipseLink in JaVers, 
definetly you shouldn't call `entityManager.getTransaction().commit();` manually.

Try to implement this in javers-way, simmilary to what we did for Hibernate support.
see `HibernateUnproxyObjectAccessHook` and `JpaHibernateConnectionProvider`.
Later on you can contribute this to Javers.
