### ISSUE TITLE
It's there any possible to clean the repository

### ISSUE THREAD

**Issue by lankanqi** [javers/javers#254]
I don't persistent repository to db,just the inmemeory.When the service do the saveOrUpdate ,I get the object's changesList.If i don't limit the query,i will get all changes.
I just want the last  commit changes,maybe there are more then two changes about the object.
How can i do?
![qq 20151118095953](https://cloud.githubusercontent.com/assets/14138415/11230623/26ca7080-8ddb-11e5-85d8-6a39c793b8e7.png)

**Comment by lankanqi** [comment]
And there is a confused problem.When i add a javersauditable on a method of a service,if the method throws an exception,the service will rollback,this mean the object did't be edit,but the javers commit it.
the picture show above,i catch the auditable too,but I try to proceed the joint point first.
It's better to change the JoinPoint to ProceedingJoinPoint?
![qq 20151118095953](https://cloud.githubusercontent.com/assets/14138415/11230801/2ab0dc82-8ddd-11e5-8ffa-731be142c7cd.png)

**Comment by bartoszwalacik** [comment]
InMemoryRepository is not transactional but you can use SqlRepository with H2 inmemory db
