### ISSUE TITLE
Sequence Numbers in SQLSERVER

### ISSUE THREAD

**Issue by yong86** [javers/javers#255]
I have a problem regarding sequence numbers in the four tables.for example, in snapshot table, the primary keys saved as :
100
101
200
201
202
300
301
to be more precise, if the current value of the sequence(jv_snapshot_pk_sq) is 2,I get 200 and 201 and then the sequence incremented by 1 and I get 300 and 301 and so on in the other tables.
So,Is it a problem regarding sql server or javers?

**Comment by bartoszwalacik** [comment]
In many db engines, sequences guarantee to be monotonical and unique and not necessarily without 'gaps'. JaVers has nothing to do about this policy. It just calls seq.nextval.
