### ISSUE TITLE
Is there any way to commit an object which extend base object?

### ISSUE THREAD

**Issue by lankanqi** [javers/javers#256]
class A extend BaseA{
    public void process(String param){//...}
}

class BaseA{
  Long id;
String name;
//..
}

**Comment by bartoszwalacik** [comment]
Why not?

**Comment by lankanqi** [comment]
I wrote a test using my project bean.like this

**Comment by lankanqi** [comment]
I know why,it is because I forgot to add Id annotation on the baseclass id field. And the baseclass implements the Serializable interface.So it become valueobjecttype.
