### ISSUE TITLE
Question Regarding JQL

### ISSUE THREAD

**Issue by yong86** [javers/javers#257]
If I have three objects: **x, y, z**
x-> 1 .. n with y
z-> 1.. n with y
when I save x,y and z, I get correct snapshots for the three objects:
x -> **{A: .., xID:..}**
z-> {**zID**:..}
y-> { **xID**:.. , **zID**:..}

My question now is, how can I use JQL to get all the changes of x,z and y searching by **A**?

**Comment by bartoszwalacik** [comment]
I'm not sure if I understand this notation, what does it mean `x-> 1 .. n with y`?
could you write it in Java or maybe ask this question using Javers domain language (Entity, ValueObject, GlobalId)

**Comment by yong86** [comment]
I mean one to many relationship

**Comment by bartoszwalacik** [comment]
still, i dont know what is `x -> {A: .., xID:..}`,

did you read http://javers.org/documentation/jql-examples/ ?

**Comment by yong86** [comment]
class y :   

        @Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "y_ID")
	private Long yId;

	@ManyToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn(name = "x_ID")
	private x x1;

	@Column(name = "x_ID")
	private Long xId;

      @ManyToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn(name = "z_ID")
	private z z1;

	@Column(name = "z_ID")
	private Long zId;

class x:

       @GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "x_ID")
	private Long xId;

     @Column(name = "A")
	private string  a;
	 
	@JsonIgnore
	@OneToMany(mappedBy = "x")
	private List<y>	yList;

Class z:

        @GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "z_ID")
	private Long zId;
	 
	@JsonIgnore
	@OneToMany(mappedBy = "z")
	private List<y>	yList;

**Comment by yong86** [comment]
sorry for that
taken from snapshot table:

for x state:
**{ "A": "test", "y": [],"xId": 1}**

for z state:
**{  "y": [],"zId":1}**

for y state:
**{ "yId": 1, ,"xId": 1, "zId":1}**

**Comment by yong86** [comment]
I want to get the changes from the three states search by **test**. Did you get me?

**Comment by bartoszwalacik** [comment]
@yong86 we are moving Questions from github Issues to http://stackoverflow.com/
to be better accesible for Javers comminity.
I will answer this question but please move it to stack.

**Comment by yong86** [comment]
tags on stackoverflow?  javers

**Comment by bartoszwalacik** [comment]
There is no javers tag yet, we will create it as soon as possible

**Comment by yong86** [comment]
Could you please answer my question here till you add the tag on stackoverflow?. I want it urgently

**Comment by bartoszwalacik** [comment]
Just put question without any tag

**Comment by yong86** [comment]
http://stackoverflow.com/questions/33973623/versions-in-javers-query-language

**Comment by yong86** [comment]
You must  tag at least one

**Comment by bartoszwalacik** [comment]
ok, i didnt know about at least one tag, we need to earn 1500 reputation points to be able to create tags,
(question is answered on Stack)
