### ISSUE TITLE
CLASS_NOT_FOUND JaVers runtime error - class not found 

### ISSUE THREAD

**Issue by yong86** [javers/javers#259]
I don't know why it is happening,when I save the object using spring data ,javers saved it correctly but when I try to read the change from a different place like: 

      List<Change> changes = javers.findChanges(QueryBuilder.byClass(x.class).build() )
**I got CLASS_NOT_FOUND JaVers runtime error - class not found - x**

I tried to debug to find the exception in 

     JsonConverter.class.forName(qualifiedName);
why the JsonConverter didn't find the class in the path??

**Comment by bartoszwalacik** [comment]
I dont know. As you can see in Javers source, it just calls standard Java method - `class.forName()`.
It could be some issue with you classpath or classloaders. 
You can wait for next Javers version (1.4.0), there will be `class.forName()` calling.
