### ISSUE TITLE
Cannot commit JavassistLazyinitializer object

### ISSUE THREAD

**Issue by lankanqi** [javers/javers#261]
like this :
![issue](https://cloud.githubusercontent.com/assets/14138415/11437017/1b6ec38e-9525-11e5-8035-12c220334be6.png)

shows error:
ENTITY_INSTANCE_WITH_NULL_ID JaVers runtime error - Found Entity instance of class

**Comment by bartoszwalacik** [comment]
We are movin questions to http://stackoverflow.com/ 
Please reask this question on Stack.
Maybe someone had the same problem like you. This is not a JaVers bug, you cannot commit Entity instance with null id.
