### ISSUE TITLE
InstanceID.value() includes typename twice. Is it correct?

### ISSUE THREAD

**Issue by smirnp** [javers/javers#275]
Is it correct, that InstanceId.value() includes the typename twice?
```
  // gives "typename / other values'
public String value() {
        return this.getTypeName() + "/" + this.getCdoIdAsString();  
}
 // gives comma-separated persistent values including typename again
private String getCdoIdAsString() {
        return ReflectionUtil.reflectiveToString(this.cdoId); 
}
```
As a result mongo receives the following query and returns 0 results:
```
{ "globalId_key" : 
"StateStructures.Framework/49168d17-60e9-4720-97d2-a6f7928e18b6-0000,StateStructures.Framework"}
```
If I manually remove last "StateStructures.Framework" with comma then mongo returns the expected rows.

**Comment by bartoszwalacik** [comment]
@smirnp we are moving questions to http://stackoverflow.com/questions/tagged/javers?sort=newest
i promise to answer this question if you move it to Stack
