### ISSUE TITLE
How to access Property?

### ISSUE THREAD

**Issue by adamyong** [javers/javers#283]
From 1.4.0 release, 
"PropertyChange is now decoupled from Property, reference from propertyChange to concrete property is replaced with propertyName String field."

What's the alternative way to access Property after 1.4.0 changes ? As I would like to access "looksLikeId" in Property

**Comment by bartoszwalacik** [comment]
We are moving questions to http://stackoverflow.com . Could you move this question to stack? Use javers tag. I will answer it there

**Comment by adamyong** [comment]
question moved

**Comment by bartoszwalacik** [comment]
Thanks, give me a while. I'll be back to you in the evening
