### ISSUE TITLE
Exposing ReferenceChange Object References

### ISSUE THREAD

**Issue by gtnarg** [javers/javers#286]
See http://stackoverflow.com/a/34643133/4931921

It would be useful to expose object references to the before and after state of a ReferenceChange when diffing using Javers.compare().  Currently only the Global Id and not the refererences themselves are provided.

**Comment by bartoszwalacik** [comment]
@ggreaves if you want it fast, think about contributing a Pull Request :)

**Comment by bartoszwalacik** [comment]
released in 1.4.4
http://javers.org/documentation/features/#release-notes
