### ISSUE TITLE
Problem with compare two list

### ISSUE THREAD

**Issue by ernest210** [javers/javers#289]
Hello.
I have a question regarding list comparator. I have a web application which have page with table.
I can edit data in this table and also delete row.
Standard comparator working correct when i edit data but i have problem when i remove row.
The problem is common (i think) when i remove e.g one row what is happening 
javers comparing old list with now one it's looks something like this:
old list have two object now list have one object (i removed first one) now javers don't know which object
was removed and he compare first object from old list with second object from new list and for him
whole object was changed and that is not true.

My thought was I will wrote own list comparator and in this comparator before javers compare method will be colled
i check if comparing objects have the same ID. 
Unfortunately i have problem to obtain object ID.
My comparator looks like this

public class ListComperator implements CustomPropertyComparator<List, ValueChange> {
	
	public ValueChange compare(List list1, List list2, GlobalId globalId, Property property) {
	
		for (Object o1 : list1) {
	 
			for (Object o2 : list2) {
				if(o1.getId().equals(o2.getId()) )	{
					javers.compare(o1, o2);
				}
			}
	 
		}
	
	}
}

The second list "list2" have my object from which i can get any property e.g ID.
The firs list "list1" is list with some ValueObjectId and i don't know how to get property with id from object o1. 
Is there a way to get this information or maybe i'm doing something totally wrong please help.

**Comment by bartoszwalacik** [comment]
Hi, questions are moved to http://stackoverflow.com, please move this question using javers tag. I will answer it
