### ISSUE TITLE
New property in entity takes long time to commit

### ISSUE THREAD

**Issue by ibailak** [javers/javers#300]
Hi,

Every time I add a new property to an entity the commit method takes a long time, from 0,5s to 1s for every record. That is really bad when I have collections with 50k documents, or even more than 1 million! It takes hours or days to complete the complete update for all the records. On the other hand, if the property is being changed (not added as new) is super fast, like I would expect with new property. I'm using Mongo for persistence. 

Is this something normal? 

Thanks!

**Comment by bartoszwalacik** [comment]
I can look at your case but you need to provide a runnable example which isoletes this issue. It could be a new test case pushed to your javers fork

**Comment by bartoszwalacik** [comment]
no response from reporter, closing
