### ISSUE TITLE
Additional commit properies (like tenant, device, anything)

### ISSUE THREAD

**Issue by arthurtaborda** [javers/javers#305]
Hi

I want to store multiple properties for the author. In my case, it would be id of the user, session id and device being used. I know I can use a class and serialize to a json string, but can I do a search based on the author? What if I want to search for the commits of a user, or a user with certain device.

Thank you

**Comment by bartoszwalacik** [comment]
Hi, query by author (just String Id for now) looks like a good idea.
Considering other things, we could do it in more general way and allow to attach Tag sets to each commit, and then query by those Tags.

**Comment by bartoszwalacik** [comment]
Unfortunately our backlog is full, consider contribution, see https://github.com/javers/javers#guidelines-for-contributors
if so, plese consult the design with us

**Comment by bartoszwalacik** [comment]
alternative way: property set
Map<String, String>

**Comment by bartoszwalacik** [comment]
JQL should allow running queries with filters with these new commit properties

**Comment by bartoszwalacik** [comment]
released in 2.0.0-RC
