### ISSUE TITLE
JQL - new withVersion() filter

### ISSUE THREAD

**Issue by bartoszwalacik** [javers/javers#322]
new filter for snapshot queries:

`javers.findSnapshots( QueryBuilder.byInstanceId("bob", Employee.class).withVersion(5).build() )`

`withVersion()` should work simmilary to `withCommitId()` filter

requested by:
@atomfrede
@milanov

**Comment by bartoszwalacik** [comment]
It could be implemented in the same way like `commitId` filter done by @mwesolowski
see https://github.com/javers/javers/pull/318/files

**Comment by bartoszwalacik** [comment]
@milanov, looks like @mwesolowski already did it :)

**Comment by atomfrede** [comment]
@bartoszwalacik @mwesolowski Wow, that was fast! Impressive!

**Comment by bartoszwalacik** [comment]
released in v. 1.4.7
see http://javers.org/documentation/jql-examples/#version-filter

**Comment by bartoszwalacik** [comment]
@atomfrede check out new `withVersion()` filter, does it solve your issue?
