### ISSUE TITLE
MongoRepository globalId_key

### ISSUE THREAD

**Issue by craigb78** [javers/javers#336]
Hi there,
I'm using Mongodb as my javers repository.
In my jv_snapshots collection, org.javers.repository.mongo.MongoRepository is adding a globalId_key field. I have 2 questions!

1/ what is the purpose of globalId_key ? It duplicates the info held in the globalId { entity: "", cdoId: "" } structure, and I think it's possible to have a composite index in mongo (on both these fields)

2/ MongoRepository.writeToDBObject()  has this line: `dbObject.append(GLOBAL_ID_KEY,snapshot.getGlobalId().value());`
Which does does go through my JsonTypeAdapter for my Id field .. so  I end up with the results of MyId.toString() in my jv_snapshots collection. Is this intended, or is it a bug?

Craig

**Comment by bartoszwalacik** [comment]
Hi,

1. this filed is used for queries (it has db index)
2. yes, it's intended, globalId contains stringified entity id
