### ISSUE TITLE
Applying diff to objects (patching)

### ISSUE THREAD

**Issue by heruan** [javers/javers#343]
Being javers a *diff framework*, it would be very useful to have methods to apply a diff to objects such that
```java
public <X> void patch(X target, X source) {
    Diff before = this.javers.compare(target, source);
    assertTrue(before.hasChanges());
    before.apply(target); // do magic here
    Diff after = this.javers.compare(target, source);
    assertFalse(after.hasChanges());
}
```
Applying a set of changes to a target object would be very useful for example working with persistence frameworks like JPA, versioning frameworks and so on.

**Comment by bartoszwalacik** [comment]
What is the use case for this kind of patch ?

**Comment by bartoszwalacik** [comment]
@heruan i'm closing this because there is no response from you. Moreover, changing user's objects is not what we are eager to do in Javers ...

**Comment by thaiden** [comment]
The use case, to implement delta protocol


B = base
L = previous state
D = delta(diff)

1. outdated state, something sends diff
B = L + D : sending diff to patch outdated state, so now we have a new base

2. another diff been send
B = B + D

**Comment by bartoszwalacik** [comment]
Not in our backlog, sorry

**Comment by Kira-Cesonia** [comment]
Welp. I guess I'll just try do it myself.
If I get it to work, this will be a core feature in tri-JaDe.
You can track my progress on https://github.com/Kira-Cesonia/tri-JaDe
