### ISSUE TITLE
ERROR: missing FROM-clause entry for table "jv_commit_pk_seq"

### ISSUE THREAD

**Issue by dvbeato** [javers/javers#344]
I'm getting this error using @JaversAuditable in my update method.

INSERT INTO jv_commit(author, commit_date, commit_id, commit_pk) VALUES(:author, :commit_date, :commit_id, :commit_pk)] with root cause
org.postgresql.util.PSQLException: ERROR: missing FROM-clause entry for table "jv_commit_pk_seq"
  Position: 8

**Comment by bartoszwalacik** [comment]
did you set proper sql dialect? (to PostgreSQL)

**Comment by bartoszwalacik** [comment]
answered on gitter

**Comment by dvbeato** [comment]
It works if you explicit set the database on your application.properties/yml spring.jpa.database=POSTGRESQL

**Comment by bartoszwalacik** [comment]
setting spring.jpa.database=POSTGRESQL
it is ok as a quick workaround, but we can think out sth smarter...

**Comment by bartoszwalacik** [comment]
fixed in JaVers 1.5.1 (no additional properties needed)
