### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by erizzo** [javers/javers#353]
If I try to include a `Collection` object in my POJO (but intialize it as a concerete type such as `ArrayList`), JaVers complains with the following error:

> JaversException: MANAGED_CLASS_MAPPING_ERROR given javaClass 'class java.util.ArrayList is mapped to java.util.ArrayList, expected ManagedType

For example, declared like this:
`private Collection<String> names;`

The actual problem, [according to StackOverflow](http://stackoverflow.com/q/36410861/639520), is that JaVers does not support fields declared as the abstract `Collection` type. The error message should be more clear about this.

**Comment by bartoszwalacik** [comment]
fixed in 1.6.1
