### ISSUE TITLE
JaversAuditableRepositoryAspect does not properly handle thrown exceptions

### ISSUE THREAD

**Issue by Drizzt321** [javers/javers#355]
Javers Spring support uses JaversAuditableRepositoryAspect on Spring-Data `@Repository` classes for `@JaversAuditable` or the Spring-Data `CrudRepository` interface. If an exception is thrown from one of those methods, then JaversAuditableRepositoryAspect, which uses `@After` will still execute and try and perform a versioning. According to [Spring AOP Docs](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/aop.html), `@After` will always execute, regardless of if there was an exception thrown or not. `@AfterReturning` instead executes only if the method returns normally.

Here's the [original StackOverflow question](https://stackoverflow.com/questions/36465724/spring-aop-javersauditable-still-trying-to-commit-a-change-when-exception-has) for reference.

**Comment by bartoszwalacik** [comment]
fixes merged to master, waiting for release

**Comment by bartoszwalacik** [comment]
released in 1.6.2
