### ISSUE TITLE
Javers Query Language

### ISSUE THREAD

**Issue by pawelszymczyk** [javers/javers#36]
As a User, I want to query for Changes & Snapshots 
using GlobalId and propertyName

TODO: 
add field Set<Property> changedProperties to CdoSnapshot 
add method Javers.getChangeHistory(JaversQuery query)
add method Javers.getStateHistory(JaversQuery query)

**Comment by igler** [comment]
Any plans when this feature will be implemented?

**Comment by bartoszwalacik** [comment]
looks like a JQL is a most wanted feature now, so we do it as a next step.
(before MSSQL and Oracle). Think a fair promise is end of April

**Comment by igler** [comment]
Sounds good! Looking forward to test this feature.

**Comment by bartoszwalacik** [comment]
JQL is released in javers 1.2.0
http://javers.org/documentation/jql-examples/
