### ISSUE TITLE
Error in schema check for MsSql Server

### ISSUE THREAD

**Issue by enietom** [javers/javers#361]
I have a JaverSqlRepository configuration with "MSSQL" as dialect. Everything was working fine, but the second time I started the app I got an SQL exception error after the following warning message:

> WARN  [JaversSchemaManager] (83)- column jv_snapshot.version not exists, running ALTER TABLE ...

I debuged in order to see what was going on, and it appears to be an issue in JaversSchemaManager.addSnapshotVersionColumnIfNeeded. Javers is trying to execute:

`ALTER TABLE jv_snapshot ADD COLUMN version BIGINT`

but "COLUMN" is not recognized by MsSQL. I tried running:

`ALTER TABLE jv_snapshot ADD version BIGINT`

and it executed correctly.

This is happening in the last version of Javers and Microsoft SQL Server 2012.

**Comment by bartoszwalacik** [comment]
That's because I don't have Windows to test these schema migration scripts ...
Thanks for reporting, I will fix it

**Comment by bartoszwalacik** [comment]
Do you think this fix is correct? https://github.com/javers/javers/commit/ab328129bad60bd61530b9756b3ae89acdd44f35

**Comment by enietom** [comment]
That throws a... 

> "Cannot find data type NUMBER."

 ... error (at least on my MSSQL 2012 server). Guess you would have to add a new "else if" for the "MsSqlDialect" and enter the SQL should be:

`ALTER TABLE jv_snapshot ADD version BIGINT`

**Comment by bartoszwalacik** [comment]
ok, the last version should work

**Comment by bartoszwalacik** [comment]
fix released in javers 1.6.3 
plese let me know if it is fine now
