### ISSUE TITLE
JDK 1.6 Compatibility

### ISSUE THREAD

**Issue by jccampanero** [javers/javers#370]
Hi, good afternoon.

Is Javers compatible with Java 1.6? Is there any version of the library with such compatibility? We are restricted to use JDK 1.6 in our project. We just need diff functionality.

Thank you very much!!
J. Carlos

**Comment by bartoszwalacik** [comment]
No, JaVers is not compatible with Java 6. Java 7 is still supported but we strongly encourage to use Java 8

**Comment by jccampanero** [comment]
Thank you very much Bartosz, I appreciate your prompt response.

Cheers,
J. Carlos

**Comment by bartoszwalacik** [comment]
No problem, in fact we are thinking about rewriting JaVers to Java8, it gonna happen more less when Oracle release Java9. Since then, new JaVers versions will be compatible only with Java 8 and 9
