### ISSUE TITLE
When auditing data in java.lang.Iterable, exception occurred "ORA-01000: maximum open cursors exceeded" in oracle database

### ISSUE THREAD

**Issue by carrchang** [javers/javers#371]
The exception is:
```
Caused by: java.sql.SQLException: ORA-00604: error occurred at recursive SQL level 1
ORA-01000: maximum open cursors exceeded
ORA-00604: error occurred at recursive SQL level 1
ORA-01000: maximum open cursors exceeded
ORA-01000: maximum open cursors exceeded
```

My solution is:
```alter system set open_cursors = 1000;```

> The number just a example, maybe need more bigger than this. 

So I think we need a batch mode to process data(commit and snapshot). The Original commit as:
```
org.javers.core.Javers#commit(String author, Object currentVersion);
```
need new api like:
```
org.javers.core.Javers#commit(String author, java.lang.Iterable<Object> currentVersion);
```

**Comment by bartoszwalacik** [comment]
Which Javers version are you using?

**Comment by carrchang** [comment]
1.6.5

**Comment by bartoszwalacik** [comment]
Please provide a failing test case with isolation of this bug

**Comment by carrchang** [comment]
After testing within a simple spring-boot demo project, the problem not to be repeated, I think the real problem must be in the environment of my app. I will solve it by myself.

Thank you for your attention!

**Comment by bartoszwalacik** [comment]
Good to hear
