### ISSUE TITLE
Error Message Enhancement Request

### ISSUE THREAD

**Issue by gtnarg** [javers/javers#394]
I am receiving the following error message:

`ENTITY_INSTANCE_WITH_NULL_ID Found Entity instance of class 'com.mypackage.MyClass' with null id`

The message is correct and I understand what it means because I integrated javers into the application but it could be misleading to someone not familiar with Javers.  In the case of the diff where this is occurring I have set the idPropertyName to a different property (i.e. not id) but the message indicates that the "id" is null when it actually isn't.  Would it be possible enhance the message with the name of the idPropertyName that is null?

**Comment by bartoszwalacik** [comment]
Could be, will you contribute a PR? That's easy to do: Entity.java line 96

**Comment by gtnarg** [comment]
Sure - be happy to :)

**Comment by bartoszwalacik** [comment]
fixed in 2.0.4
