### ISSUE TITLE
Define schema for javers related tables

### ISSUE THREAD

**Issue by ianagius** [javers/javers#398]
At the moment, JaVers is creating tables in the public schema. It would be great to be able to define the schema where these tables are created,

**Comment by bartoszwalacik** [comment]
Agreed but schema support have to be implemented in polyJdbc first

**Comment by ouaibsky** [comment]
It could be nice to provide some configuration as well in order to tune table name.
I'm working for a big company, where DBA's rules are strict and we must follow some guidelines on naming (mainly table)

Christophe

**Comment by ianagius** [comment]
has there been any progress on this case? We just need to expose a setter method for private String schema property in SchemaInspectorImpl.

**Comment by bartoszwalacik** [comment]
no progress yet. Dont think that someone from core team will take this issue soon. If you need this feature - contribute

**Comment by bartoszwalacik** [comment]
see also https://github.com/polyjdbc/polyjdbc

**Comment by ianagius** [comment]
We have decided to contribute :) and we have created a pull request for you to consider. Let us know if you have any questions or you would like further clarifications.

**Comment by bartoszwalacik** [comment]
I can't accept this, see https://github.com/javers/javers/pull/433#pullrequestreview-435527
It will be easier to work on this issue, if you follow my guidelines. As I wrote in the second comment in this issue: schema support have to be implemented in polyJdbc first.

**Comment by LucasDesenv** [comment]
This is a good one... It's not quite nice to use public schema for auditing.. kinda security failure, no? Or I didn't get it?

**Comment by bartoszwalacik** [comment]
security failure? I'm affraid that you are missing that JaVers doesn't write to **public** schema. It writes to a default schema, for most databases it means schema of a current db user

**Comment by LucasDesenv** [comment]
Oh, I get it! Thanks for explaining.

**Comment by bartoszwalacik** [comment]
done & released in 2.4.0

**Comment by pedroxs** [comment]
How to configure the schema? I could not find anywhere on the docs page

**Comment by bartoszwalacik** [comment]
@pedroxs docs updated, see https://javers.org/documentation/repository-configuration/#sql-databases

**Comment by pedroxs** [comment]
Perfect, thanks!
