### ISSUE TITLE
additional data regarding a commit

### ISSUE THREAD

**Issue by conor-roche-rockalltech** [javers/javers#401]
I can see the commit supports storing the author, is there a way to store additional data against the commit that isnt part of the domain object (in my case i would like to store the channel the change came in from (channel can be a soap ws, application UI, rest api etc) )

**Comment by conor-roche-rockalltech** [comment]
ive just spotted CommitPropertiesProvider so closing this.

**Comment by bartoszwalacik** [comment]
right:)
http://javers.org/documentation/jql-examples/#commit-property-filter
