### ISSUE TITLE
Add support to @PropertyName

### ISSUE THREAD

**Issue by mundodojava** [javers/javers#403]
Create a member level PropertyName to customize the property name of change

**Comment by bartoszwalacik** [comment]
This feature looks like really easy to implement, perfect issue for a contribution

**Comment by bartoszwalacik** [comment]
new ann should be added here `org.javers.core.metamodel.annotation.PropertyName` Target METHOD & FIELD

New field, `String name`, should be added to Property class.
By default, name should be initialized from `member.propertyName()` (as is now).

When `@PropertyName` is present, name should be set from ann value.

This logic, should be implemented in `BeanBasedPropertyScanner` and `FieldBasedPropertyScanner`


Tests should be added in `PropertyScannerTest`

**Comment by bartoszwalacik** [comment]
`@PropertyName` added in javers 3.1.0
see http://javers.org/documentation/domain-configuration/#supported-annotations
