### ISSUE TITLE
@ShallowReference for properties

### ISSUE THREAD

**Issue by croffler** [javers/javers#412]
It would be nice if the @ShallowReference annotation could be used on a property.
I have some entities that have a large graph (many relations). In many cases I would like for Javers to just save the ID's of the embedded entities. If I use @Diffignore the relationship info is lost.

**Comment by bartoszwalacik** [comment]
agreed that it could be useful, unfortunately, implementation would not be easy (ShallowReference is now a JaversType)

**Comment by LucasDesenv** [comment]
We need this issue solved to use Javers in our company. Do you guys have plans to solve this one? If so, si there a release date planned?

**Comment by bartoszwalacik** [comment]
I dont think that anyone from JaVers core team is going to take care about this issue soon

**Comment by bartoszwalacik** [comment]
You can contribute a PR but i'm affraid that it won't be easy one

**Comment by croffler** [comment]
What I have done for now is to use @Diffignore.

Most of the Entities we have, those properties (associations) can't be
changed once the Entity is created. If we need to get the actual info for
those properties we can retrieve them from the RDBMS.

Chris

**Comment by mwesolowski** [comment]
@bartoszwalacik please take a look at the branch https://github.com/javers/javers/tree/issue-412-shallow-reference-for-properties  This is my first attempt to solve this issue. I'm sure you can provide me with some tips what can be improved.

**Comment by bartoszwalacik** [comment]
great, will take a look

**Comment by bartoszwalacik** [comment]
done in release 2.5.0

**Comment by croffler** [comment]
Awesome

**Comment by LucasDesenv** [comment]
Nice one, @mwesolowski !
