### ISSUE TITLE
New Javers repository type - Logger

### ISSUE THREAD

**Issue by pszymczyk** [javers/javers#419]
The idea is to store Javers commits using org.slf4j.Logger. It could be quite usefull because there is more and more popular to automatically persist logs in some remote storage (like Elasticsearch) and then grep them using specified interface (like Kibana or Logstash).

The problem is that logs have specified retention so last Cdo snapshot should be persited in some other place. One of the possible solution is to use persistent map - http://chronicle.software/products/chronicle-map/.

**Comment by bartoszwalacik** [comment]
size of this persistent map worries me, it has to be equal to all objects count (all last snapshots)
