### ISSUE TITLE
Document Javers.compare thread safety

### ISSUE THREAD

**Issue by rr040** [javers/javers#423]
I have to compare a lot of objects to avoid expensive REST calls, but I'm not sure wheter I can share a Javers instance in different threads or I should create a new instance for each task.

**Comment by bartoszwalacik** [comment]
Javers instance is thread-safe, so you dont have to create more than one

**Comment by ritonglue** [comment]
Is it documented somewhere that a Javers (interface) implementation must be thread safe ?
