### ISSUE TITLE
Enhance Aspect to support JpaRepository#saveAndPublish

### ISSUE THREAD

**Issue by ouaibsky** [javers/javers#427]
Have a look at #426 

I make some inheritance because modifying existing JaversSpringJpaApplicationConfig is gonna introduce jpa dep on starter-mongo and I guess we don't want that.

Christophe

**Comment by bartoszwalacik** [comment]
I dont know which version of JpaRepository you are using but in latest there is no such method

**Comment by ouaibsky** [comment]
this class is part of org.springframework.boot:spring-boot-starter-data-jpa.

This dependency is coming with spring-boot-starter-sql.

If I add this into JaversSpringDataAuditableRepositoryAspect (javers-spring) it's gonna require a new dep on spring-boot-starter-data-jpa and I'm don't know if it's what you want (and in this case it meaning other jar starter-mongo will get transitive dep on jpa and it's likely not what you want as well).

I could also had to update only exisiting JaversSpringDataAuditableRepositoryAspect with regexp
> execution(public * save*(..))

But maybe it could lead to match method that should not be part of this aspect ...
Christophe

**Comment by bartoszwalacik** [comment]
@ouaibsky could you please answer my question:
I dont know which version of JpaRepository you are using but in latest there is no such method, what is `JpaRepository.saveAndPublish()`?

**Comment by ouaibsky** [comment]
@bartoszwalacik 

Sorry my bad, copy paste error I'm talking about *saveAndFlush*.

**Comment by bartoszwalacik** [comment]
https://github.com/javers/javers/issues/431
