### ISSUE TITLE
Question: How to browse changes for an embeddable entitity ?

### ISSUE THREAD

**Issue by ouaibsky** [javers/javers#428]
Hi

I use Entity JPA that contains Embedded Entities.
Let's pick an example:

> Entity Foo contains embeddable Bar

```java
@Entitty
public class Foo {
private Bar;
...
}

@Embeddable
public class Bar {
...
}
```

When B changed, new line are added into jv_snapshot with classname **Bar** (and jv_global_id contains fragment with **Bar** referencing **Foo**

The pb is how to get changes for **Bar** ?

It looks like QueryBuilder.byInstanceId accept only class annotated with @Entity (which is not the case of **Bar** of course).

Thanks in advance.
Christophe

**Comment by bartoszwalacik** [comment]
This is not an issue but a question. Please move it to http://stackoverflow.com/questions/tagged/javers
We will answer

**Comment by bartoszwalacik** [comment]
already answered, don't cross-post issues, it makes our job hardrer
