### ISSUE TITLE
Auto-audit aspect also on JpaRepository.saveAndFlush()

### ISSUE THREAD

**Issue by bartoszwalacik** [javers/javers#431]

**Comment by ouaibsky** [comment]
Do you expect another PR to do this enhancement ?

**Comment by bartoszwalacik** [comment]
You can try but please, this time, keep it simple and clean. Maybe we can talk about design first (at https://gitter.im/javers/javers)

**Comment by ouaibsky** [comment]
OK, I'll try to reach this url at home but unfortunately my company's proxy is refusing to open gitter.

**Comment by bartoszwalacik** [comment]
https://github.com/javers/javers/pull/426#issuecomment-247250109

**Comment by bartoszwalacik** [comment]
released in 3.6.0
