### ISSUE TITLE
ReflectionUtil.reflectiveToString should be able to handle UUID

### ISSUE THREAD

**Issue by philnate** [javers/javers#441]
If your entity key is of type java.util.UUID it will be encoded on call to GlobalId.value()/toString() to something like: MyEntity/6119540349362061825,-7372191321594927012 while it should be the correct UUID as string. The only solution currently is to use explicit EntityDefinition and handing over some custom field holding the String value of the UUID.

Version is 2.3.0

**Comment by bartoszwalacik** [comment]
Why it should be UUID as string?

**Comment by philnate** [comment]
I would consider a UUID a rather common-id field. If you now want to look into the plain data stored, you won't see you familiar UUID string, rather than this MyEntity/6119540349362061825,-7372191321594927012 kind of construct.

**Comment by bartoszwalacik** [comment]
right, UUID should be added to well-known-value-types

**Comment by bartoszwalacik** [comment]
fixed in v 2.4.1
