### ISSUE TITLE
Ignoring all properties in a class

### ISSUE THREAD

**Issue by edmallia** [javers/javers#448]
We would like to ignore all properties in a class which is part of a hierarchy.  Currently this can be done by putting an @DiffIgnore annotation on all the properties of the class in question.  What we are proposing is to add a class level annotation (say @DiffIgnoreAllProperties) that would ignore all the properties in that class but still track the entity.

Example.  Consider we have the following classes.

```
abstract class A {
    private Long id;
    private String name;
}

class B extends A {
    private String foo;
    private String bar;
    private String foobar;
}

class C extends A {
    private String alpha;
    private String beta;
    private String charlie;
}
```

We would like to track all types of class A and we only need to track id and name.  Currently this can be done in this way:

```
abstract class A {
    @Id
    private Long id;
    private String name;
}

class B extends A {
    @DiffIgnore
    private String foo;
    @DiffIgnore
    private String bar;
    @DiffIgnore
    private String foobar;
}

class C extends A {
    @DiffIgnore
    private String alpha;
    @DiffIgnore
    private String beta;
    @DiffIgnore
    private String charlie;
}
```

This works fine, however with large class hierarchies and classes with a lot of properties placing @DiffIgnore on each property can become cumbersome.  What we are proposing to to add and @DiffIgnoreAllProperties annotation (open to new names) so that the above classes would look like this.

```
abstract class A {
    @Id
    private Long id;
    private String name;
}

@DiffIgnoreAllProperties
class B extends A {
    private String foo;
    private String bar;
    private String foobar;
}

@DiffIgnoreAllProperties
class C extends A {
    private String alpha;
    private String beta;
    private String charlie;
}
```

Any thoughts?  We are preparing a PR in relation to this. What do you think ?

**Comment by bartoszwalacik** [comment]
interesting idea, but maybe better name for this new ann would be `@IgnoreDeclaredProperties` ?

**Comment by ianagius** [comment]
create a pull request 448
