### ISSUE TITLE
Changing from null to empty collection doesn't register

### ISSUE THREAD

**Issue by LucasSloan** [javers/javers#454]
I'm using javers to record changes to an object, then grab the changes that were made and apply them to an object in our datastore transactionally, because we don't want to keep a transaction open long enough to run the code that generates the changes.  This works fairly well, but we've run into an issue since one of the things we generate is a map that can be empty and Javers doesn't seem to be recognizing that changing from a null value to an empty is a change.

Example code:

    class JaversCollectionTester {
        List<String> stringListField;
        Map<String, String> stringMapField;

        public JaversCollectionTester(List<String> stringListField, Map<String, String> stringMapField) {
            this.stringListField = stringListField;
            this.stringMapField = stringMapField;
        }

        public void setStringListField(List<String> stringListField) {
            this.stringListField = stringListField;
        }

        public void setStringMapField(Map<String, String> stringMapField) {
            this.stringMapField = stringMapField;
        }
    }

    public void doTest() {
        JaversCollectionTester collectionTester = new JaversCollectionTester(null, null);

        Javers javers = JaversBuilder.javers().build();
        javers.commit("importJobDiff", collectionTester);

        collectionTester.setStringListField(new ArrayList<String>());
        collectionTester.setStringMapField(new HashMap<String, String>());

        javers.commit("importJobDiff", collectionTester);
        final List<Change> changes = javers.findChanges(QueryBuilder.anyDomainObject().build());
        // Expects a list of 2 changes, instead changes is empty
        System.out.println("changes: " + changes);
    }

Is this the intended behavior? Is there a workaround for this?

**Comment by bartoszwalacik** [comment]
JaVers just works that way and treats nulls as empty collections. If we create this kind of change I think that most JaVers users would treat it as a noise

**Comment by bartoszwalacik** [comment]
JaVers aims in tracking changes in a domain model (only business relevant data) and not technical clutter

**Comment by bartoszwalacik** [comment]
wont do
