### ISSUE TITLE
Update website examples

### ISSUE THREAD

**Issue by vrozkovec** [javers/javers#459]
Hi, I have trouble retrieving NewObject change.
Using version 2.7.0, it should be already there, I've noticed this commit:
https://github.com/javers/javers/commit/510ca7aa758a82b7045a4af8134fff94b0c15352

However this page:
http://javers.org/documentation/repository-examples/#read-changes-history

still uses the pre-NewObject version code.

Somehow I am still unable to retrieve NewObject change though. Using JaversSqlRepository implementation and Hibernate, no Spring.

**Comment by vrozkovec** [comment]
My bad.. I wasn't aware of QueryBuilder's withNewObjectChanges() method :)
So NewObject is retriewed, though update of the website is still needed :)

thanks

**Comment by bartoszwalacik** [comment]
ok, I will take a look

**Comment by bartoszwalacik** [comment]
could you please explain what's misleading in the doc? there is no example for withNewObjectChanges(), maybe we should add it ...

**Comment by bartoszwalacik** [comment]
now i see that we have example for NewObjectChanges - http://javers.org/documentation/jql-examples/#new-object-filter
So what we can improve in our doc?
