### ISSUE TITLE
Javadoc incorrect in Javers.class

### ISSUE THREAD

**Issue by DavidDudson** [javers/javers#471]
https://github.com/javers/javers/commit/80498f3f2dfb0277b400d6659f10d0c29f497aaf#diff-ba26073ba7a0090c0829de8a8abc54e9

Changed the signature of getTypeMapping to 
`<T extends JaversType> T getTypeMapping(Type userType);`

The javadoc for that method still has the usage...

 `ManagedType jType = javers.getTypeMapping(Person.class)`

This does not work.

**Comment by DavidDudson** [comment]
Never mind, i'd just confused the type heihrarchy

**Comment by bartoszwalacik** [comment]
well, do you think we should fix this javadoc? in Java, Type is a supertype of Class and Interface, so we use Type
