### ISSUE TITLE
Bug: GlobalIdPK cache is not clear when transaction rollback has been performed in Javers 2.7.2 version

### ISSUE THREAD

**Issue by YaraslauBarysenka** [javers/javers#472]
The https://github.com/javers/javers/issues/467 issue is still reproducible when I use Javers 2.7.2 version.

In order to reproduce the issue use the same updated example:
[javers-bug-example.zip](https://github.com/javers/javers/files/621741/javers-bug-example.zip)

The all steps and instructions are the same.

P.S.
Thank you for your help and quick responses.

**Comment by bartoszwalacik** [comment]
As far as I can see from this example, you are not using our javers-spring integration module http://javers.org/documentation/spring-integration/

That's the recommended way for javers-spring integration and that's the place where I fixed the issue. See javadoc for `JaversSqlRepository.evictCache()`
https://github.com/javers/javers/blob/master/javers-persistence-sql/src/main/java/org/javers/repository/sql/JaversSqlRepository.java

If you don't want to use javers-spring module you can disable the cache using
`SqlRepositoryBuilder.withGlobalIdCacheDisabled()` or call `JaversSqlRepository.evictCache()` on each rollback, just like we do in `JaversTransactionalDecorator`
