### ISSUE TITLE
Compare using custom comparator yields an exception

### ISSUE THREAD

**Issue by ilyagutman** [javers/javers#473]
Hi Bartosz, 

We were hoping you could help us to move forward with the following issue. We are registering a custom comparator for our [simple] custom class. Create two test instances of this class type and immediately compare them with the compare method. The code compiles properly, but gives us a run-time error - `EXCEPTION:JaversException MANAGED_CLASS_MAPPING_ERROR: given javaClass 'class com.dao.SevOneIdentifier' is mapped to CustomType, expected ManagedType`

```
////////////////////////////////////////////////////////////////////////////
// Our simple custom class for which we need custom comparator 
////////////////////////////////////////////////////////////////////////////
public class SevOneIdentifier {
    private int id;
    private String name;

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public SevOneIdentifier(int id, String name) {
        this.id = id;
        this.name = name;
    }
}

/////////////////////////////////////////////////////////////////////////////////////////
// Our implemented custom comparator that FOR NOW always returns null
////////////////////////////////////////////////////////////////////////////////////////
public class SevOneIdentifierComparator implements org.javers.core.diff.custom.CustomPropertyComparator<SevOneIdentifier, ValueChange> {

    public SevOneIdentifierComparator() {
        System.out.println("in SevOneIdentifierComparator ctor");
    }

    @Override
    public ValueChange compare(SevOneIdentifier left, SevOneIdentifier right, GlobalId globalId, Property property) {

        System.out.println("comparing left:" + left.getId() + " " + left.getName() + " right:" + right.getId() + " " + right.getName());

        return null;
    }
}
////////////////////////////////////////////////////////////////////////////
// Our main code that puts it all together
////////////////////////////////////////////////////////////////////////////
Javers javers = JaversBuilder.javers().registerCustomComparator(new SevOneIdentifierComparator(), SevOneIdentifier.class).build();
SevOneIdentifier id1 = new SevOneIdentifier(1, "test");
SevOneIdentifier id2 = new SevOneIdentifier(2, "test2");
Diff diff = javers.compare(id1, id2);
```

We do see that the constructor for of the comparator is properly called during the registration.
Also please note that we are using javers 2.6.0.

Thank you
Ilya Gutman + the Team

**Comment by ilyagutman** [comment]
After we registerValueObject(SevOneIdentifier.class) the issue was resolved. Thank you.

**Comment by gbrinkmann** [comment]
Thank you for the info, I had the same problem using a custom string comparator.

I'm building a `public TreeComparator(T rootNode1, T rootNode2)` and after I've added
`Class cls = rootNode1 != null ? rootNode1.getClass() : rootNode2 != null ? rootNode2.getClass() : null;`
and used `.registerValueObject(cls)` when building, the `java.lang.ClassCastException: org.javers.core.metamodel.type.CustomType cannot be cast to org.javers.core.metamodel.type.PrimitiveOrValueType` appears no longer.

(comment added because it may be interesting for other searchers)
