### ISSUE TITLE
@Diffignore exception

### ISSUE THREAD

**Issue by croffler** [javers/javers#480]
When I annotate one of my entities with @Diffignore I am getting the following exception when I try to save an instance in Javers:

MANAGED_CLASS_MAPPING_ERROR: given javaClass 'class rw.gov.ifmis.sequence.domain.CommitmentSequenceNumber' is mapped to IgnoredType, expected ManagedType

 According to the docs : 
@DiffIgnore — declares a given class as totally ignored by JaVers. All properties with ignored type are ignored.

I assumed that Javers would completely ignore this instance.

What am I missing ?

**Comment by bartoszwalacik** [comment]
When you pass an object to javers.commit(), Javers builds an object graph starting from a given object. This is a recursive work.

In this graph, nodes are your domain objects (Entities or ValueObjects)
and edges are references between them.

When Javers spots object mapped to IgnoredType, it simply ignores that object. In that case, node is not  created. So if you start from IgnoredType you get an empty graph, which, obviously can't be committed.

The question is, why are you trying to commit an ignored object?

**Comment by croffler** [comment]
I have a persistent framework that triggers via hibernate  (PostInsertEventListener, PostUpdateEventListener, PostDeleteEventListener)  an event that then automatically calls Javers to save and delete entities in the javers repo. 
I assumed that javers just ignores entities that are annotated with @Diffignore. I guess I'll have to do the check myself

**Comment by bartoszwalacik** [comment]
Exactly
