### ISSUE TITLE
Ignore Properties

### ISSUE THREAD

**Issue by LordPinhead** [javers/javers#482]
Hi,

maybe you could integrate an Annotation to Ignore some Properties in a Bean.

```java
public class Person {
	
    @Id
    private String login;
    private String name;
    
    @IgnoreProperty
    private String sex;

    public String getSex() { return sex; }
}

```

In my Application, i use Database Triggers when changes are stored in my tables with some extra fields (i.e. table: Person -> Person_Hist). In my GUI i would have to use a lot of if statements to suppress them. It would be really easy to put some Annotations in the Parent Bean instead.

**Comment by bartoszwalacik** [comment]
use Javers' `@DiffIgnore` (http://javers.org/documentation/domain-configuration/#supported-annotations)
