### ISSUE TITLE
3 way diff/merge

### ISSUE THREAD

**Issue by jwaterloo** [javers/javers#486]
These are all wish list and feature requests.
1) 3 way diff
2) 3 way merge
3) separate artifacts for visualization of 2 and 3 way diff and merge, view and edit/apply for different framworks, servlet, JSP mustache angular2 ... this could be used to allow end users to resolve optimistic concurrency conflicts. Developer could just hook in back end and style. The text only view only mode would work great for for assertion failure output when testing, asserting whether 2 graphs are equal.

**Comment by bartoszwalacik** [comment]
and what is 3 way diff/merge? What is a use case? 
considering visualisation, JaVers has text pretty print feature and we don't have plans to build any kind of GUI
