### ISSUE TITLE
Upgrade slf4j-api to 1.7.7

### ISSUE THREAD

**Issue by raupachz** [javers/javers#487]
If you use javers-core with javers-persistence-sql the dependency resolution does not agree on the same slf4j-api version.

javers-core (2.8.2) -> slf4j-api (1.7.2)
javers-persistence-sql (2.8.2) -> polyjdbc (0.6.4) -> slf4j-api (1.7.7)

Just a minor issue.

**Comment by bartoszwalacik** [comment]
ok, I will upgrde to 1.7.7 in the next release

**Comment by bartoszwalacik** [comment]
fixed in master
