### ISSUE TITLE
JQL with .andPropertyWithValue

### ISSUE THREAD

**Issue by raupachz** [javers/javers#488]
Hello,

maybe this is already possible and I just missed the part in the documentation.

I want to use Javers in a multi-tentant system. That means we have entities that belong to a specific user with a Id reference to that user. Think of a shared database for independent users and not a database per user architecture.

For example:

```
@Entity
@TypeName("Person")
class Person {

  @Id
  private Integer id;
  private Integer userId;

}
```

Querying  for Entity changes by Instance Id is easy:

```
QueryBuilder
  .byInstanceId(1, Person.class)
  .build()
```

Querying all Entities is also possible:

```
QueryBuilder
  .byClass(Person.class)
  .build()
```

Question is how can I query all Entites with a concrete property value? I was looking for something like this:

```
QueryBuilder
  .byClass(Person.class)
  .andPropertyWithValue("userId", 1)
  .build()
```

Is this even possible?

**Comment by bartoszwalacik** [comment]
There is no such query filter. Theoretically, `andPropertyWithValue()` could be implemented but it would be terribly slow (no DB index). I suggest you to use commit properties -- `withCommitProperty()` (they are indexed).
