### ISSUE TITLE
Add support for using the limit and offset filters to filter by commit.

### ISSUE THREAD

**Issue by wcchristian** [javers/javers#491]
Currently the limit and offset filters in QueryBuilder act on snapshots. I would like to be able to filter on commit Id so I could "Get all changes for a range of commit ids" this way I would be able to more easily group my changes by commit id.

**Comment by bartoszwalacik** [comment]
I'm afraid that kind of jql query would be slow, because database query limit and offset could not be used.

**Comment by bartoszwalacik** [comment]
wont do
