### ISSUE TITLE
Mongo DocumentConverter can not convert boolean

### ISSUE THREAD

**Issue by fsoylemez** [javers/javers#494]
Hello,
fromJsonElement method throws illegalargumentexception( unsupported jsonelement type) if it faces a Boolean value.(version 2.9.1)

**Comment by bartoszwalacik** [comment]
ok, we will fix it

**Comment by bartoszwalacik** [comment]
can't reproduce, I've added the new test to catch this bug but the test is passing - https://github.com/javers/javers/commit/a9bbc574584f6ec1833fac198234deb2753fb0bd

could you please post a reproduction scenario?

**Comment by fsoylemez** [comment]
Hi Bartosz,
problem resolved when i added lines
"
                if(list.isBoolean()) {
                    return Boolean.valueOf(jsonElement.getAsBoolean());
                }
"
thank you for the quick response.

**Comment by bartoszwalacik** [comment]
Ok, but still, how can I reproduce the issue in a test case?

**Comment by bartoszwalacik** [comment]
ok, I have the repro, there was a bug in this new test case. I'm working on the fix ..

**Comment by bartoszwalacik** [comment]
fixed in 2.9.2

**Comment by fsoylemez** [comment]
thank you!
sorry that i couldnt return in time with the scenario.

**Comment by fsoylemez** [comment]
can i ask when 2.9.2 will publicly be available?

**Comment by bartoszwalacik** [comment]
It is public since today morning
