### ISSUE TITLE
JaversMethodFactory.methodKey(Method) could generate duplicate ids

### ISSUE THREAD

**Issue by sschedl** [javers/javers#499]
Hello,

I found the problem that some properties get ignored in the diff, I could track it down to JaversMethodFactory.methodKey that generates duplicate ids for:
ShaDigest.shortDigest("isOrOperation")  = 32757
ShaDigest.shortDigest("getCmdline") = 32757

I'm using javers 2.9.1

Best Regards

Stefan

**Comment by bartoszwalacik** [comment]
thanks for reporting, I'll check it out

**Comment by bartoszwalacik** [comment]
fixed in 3.0.2
