### ISSUE TITLE
Intermediate generic parent scenario: Don't know how to extract Class from type 'ID'.

### ISSUE THREAD

**Issue by prook** [javers/javers#501]
Consider the following class hierarchy, note the ID type parameter in particular:
```
class Identified<ID> {
    ID id;
}

class Versioned<ID, VER> extends Identified<ID> {
    VER version;
}

class Person extends Versioned<Long, Long> {
    String name;
}

class PersonTest {
    @Test
    public void testCompare() {
        Javers javers = JaversBuilder.javers().build();
        javers.compare(new Person(), new Person());
    }
}
```

Instead of resolving ID to Long, JaVers blows up:

> o.j.c.m.t.TypeMapper - Can't calculate JaversType for property: Field ID id; //declared in Identified
>
>JaversException CLASS_EXTRACTION_ERROR: JaVers bootstrap error - Don't know how to extract Class from type 'ID'.
>
> 	at org.javers.common.reflection.ReflectionUtil.extractClass(ReflectionUtil.java:216)
> 	at org.javers.core.metamodel.type.TypeMapperState.findNearestAncestor(TypeMapperState.java:156)
> 	at org.javers.core.metamodel.type.TypeMapperState.infer(TypeMapperState.java:149)
> 	at org.javers.core.metamodel.type.TypeMapperState.lambda$getJaversType$18(TypeMapperState.java:86)
> 	at org.javers.core.metamodel.type.TypeMapperState.computeIfAbsent(TypeMapperState.java:107)
> 	at org.javers.core.metamodel.type.TypeMapperState.getJaversType(TypeMapperState.java:86)
> 	at org.javers.core.metamodel.type.TypeMapper.getJaversType(TypeMapper.java:100)
> 	at org.javers.core.metamodel.type.TypeMapper.getPropertyType(TypeMapper.java:165)
> 	at org.javers.core.graph.ObjectGraphBuilder.lambda$getSingleReferencesWithManagedTypes$43(ObjectGraphBuilder.java:107)
> 	at org.javers.core.metamodel.type.ManagedClass.getManagedProperties(ManagedClass.java:65)
> 	at org.javers.core.metamodel.type.ManagedType.getProperties(ManagedType.java:49)
> 	at org.javers.core.graph.ObjectGraphBuilder.getSingleReferencesWithManagedTypes(ObjectGraphBuilder.java:106)
> 	at org.javers.core.graph.ObjectGraphBuilder.buildSingleEdges(ObjectGraphBuilder.java:76)
> 	at org.javers.core.graph.ObjectGraphBuilder.buildEdges(ObjectGraphBuilder.java:71)
> 	at org.javers.core.graph.ObjectGraphBuilder.buildGraphFromCdo(ObjectGraphBuilder.java:59)
> 	at org.javers.core.graph.ObjectGraphBuilder.buildGraph(ObjectGraphBuilder.java:48)
> 	at org.javers.core.graph.LiveGraphFactory.createLiveGraph(LiveGraphFactory.java:39)
> 	at org.javers.core.diff.DiffFactory.buildGraph(DiffFactory.java:101)
> 	at org.javers.core.diff.DiffFactory.compare(DiffFactory.java:56)
> 	at org.javers.core.JaversCore.compare(JaversCore.java:127)

Observed in JaVers 2.9.2 and 3.0.0.

**Comment by bartoszwalacik** [comment]
fixed in 3.0.2
