### ISSUE TITLE
Unresonable snapshots while commiting not changed entity with id annotated with @EmbeddedId

### ISSUE THREAD

**Issue by floresek** [javers/javers#504]
Hi,

commiting the same object identified with property annotated using @EmbeddedId to javers SQL repository (oracle) casues every time unreasonable record in jv_snapshot with changed_properties column set to ['id']

See code below (groovy). 

``` java
@Embeddable
class TestEmbeddableId {
    String part1
    Long part2
}

class TestWithEmbeddedId {

    @EmbeddedId
    TestEmbeddableId id

    String value1
}

...
...
def obj = new TestEmbeddedId(
		id: new TestEmbeddableId(
				part1: 'id1',
				part2: 1l,
		),
		value1: 'value1',
)

javers.commit('anonymous', obj)
javers.commit('anonymous', obj)
javers.commit('anonymous', obj)

def changes = javers
		.findChanges(QueryBuilder.byInstanceId(obj.id, TestEmbeddedId.class)
				.withNewObjectChanges(true)
				.build())
				
// changes count and content is valid but 3 snapshots is created in jv_snapshot - 1 INITIAL and 2 UPDATE (unreasonable with changed_properties = ['id'])
...
```

Tested with 2.9.2 version (SQL, oracle 12)

Cheers
Mariusz

**Comment by floresek** [comment]
BTW

In our project (using javers) we have done some changes to sql-repository classes - see classes from attachment below.
Current javers implementation does not work properly in cluster environment (JBoss EAP 6/7)

Could you review the changes as candidate to be included in javers code, please?

Change .docx to .zip first (I couldn't attach zip file)

(for 2.9.2 version)
[javers-changes.docx](https://github.com/javers/javers/files/803956/javers-changes.docx)

Cheers
Mariusz

**Comment by bartoszwalacik** [comment]
Ok, thanks for reporting, I will check it out. 
I guess that second comment concerns another issue? I'm confused about this .docx, why not simpy a pull request?

**Comment by floresek** [comment]
Sorry about .docx attachment but the code is a little tricky (because of current javers API encapsulation level) and I'm sure you will do it better (maybe including new configuration f.e. for max tries when creating new commit id).

**Comment by javerstravis** [comment]
Mariusz, czy chesz żebym rozpakował tego doca/zipa i porównywał kod który tam znajdę (ręcznie?) z kodem JaVersa, żeby wydedukować na podstawie tych różnic na czym dokładnie polega problem pt "coś nie działa na JBoss"?

Na ekranie wrzucania issue jest na samej górze prośba o:
Please review the guidelines for contributing to this repository.
https://github.com/javers/javers/blob/master/CONTRIBUTING.md

Jeśli to co zgłaszasz to bug report, to:

Bug Reports have to contain:
- Clear description of your expectations versus reality
- Runnable test case which isolates the bug and allows us to easily reproduce it on our laptops. You can push this test case to your fork of this repository.

**Comment by bartoszwalacik** [comment]
Concerning your first issue. I can't see any redundant snapshot being created.
Only one snapshot is created. Let me know if you manage to reproduce the issue as a and failing test case.

```
package org.javers.core.cases

import org.javers.core.JaversBuilder
import org.javers.repository.jql.QueryBuilder
import spock.lang.Specification

import javax.persistence.Embeddable
import javax.persistence.EmbeddedId

class Case504Floresek extends Specification {

    @Embeddable
    class TestEmbeddableId {
        String part1
        Long part2
    }

    class TestWithEmbeddedId {
        @EmbeddedId
        TestEmbeddableId id
        String value1
    }

    def "should ..."(){
      given:
      def javers = JaversBuilder.javers().build()

      def obj = new TestWithEmbeddedId(
              id: new TestEmbeddableId(part1: 'id1',part2: 1l),
              value1: 'value1')

      when:
      3.times{
          javers.commit('anonymous', obj)
      }

      def snapshots = javers.findSnapshots(QueryBuilder.anyDomainObject().build())
      def changes = javers.findChanges(QueryBuilder.byInstanceId(obj.id, TestWithEmbeddedId.class)
              .withNewObjectChanges(true)
              .build())

      snapshots.each {println it}
      changes.each {println it}

      then:
      snapshots.size() == 1
      changes.size() == 3
    }
}
```

**Comment by floresek** [comment]
Bartosz,

your test fails if you change javers repository to SQL (I tested it with oracle RDB)

Cheers
Mariusz

**Comment by floresek** [comment]
@javerstravis - już wyjaśniam co i dlaczego zmieniliśmy
(zmian nie ma dużo i są oznaczone komentarzem ... by MAF)

Zmiany względem wersji 2.9.2 w reakcji na problemy w środowisku klastra serwerów aplikacyjnych:

I. Wyszukiwanie 'najświeższego' snapshot nie zwrało takowegoż

Obecna implementacja:
Bazuje na MAX snapshot_pk - a nie powinna

Dlaczego?:
Zakładam, że tworzycie sekwencje z domyślnymi ustawieniami. W efekcie na oracle utworzona sekwencja ma ustawione:
* cache size: 20
* not ordered
Przydzielenie nowego id z sekwencji następuje w oddzielnych sesjach / per węzeł i nie gwarantuje rosnących wartości w funkcji czasu

Rozwiązanie:
Jako, że tabela jv_snapshot nie posiada pola z datą/godziną utworzenia, to wykonujemy złączenie z jv_commit i pobieramy rekord z MAX jv_commit.commit_date

Zmiany w org.javers.repository.sql.finders.CdoSnapshotFinder#queryForCdoSnapshotDTOs

II. Co jakiś czas dostawaliśmy JaversExceptionCode.CANT_SAVE_ALREADY_PERSISTED_COMMIT
(zapewne na skutek wywołania commit na różnych węzłach w zbliżonym momencie czasu)

Nasze obejście:
Podbicie minor na przydzielonym commit id (max 5 prób) - zanim rzucony zostanie ww. wyjątek

Zmiany w org.javers.repository.sql.JaversSqlRepository#persist

**Comment by bartoszwalacik** [comment]
Nie jestem na bieżąco z Oracle, ale z tego co pamiętam to sekwencje Oracle gwarantują rosnące  wartości dla kolejnych transakcji. Problemem więc może nie być sekwencja bazodanowa ale algorytm alokacji sekwencji w PolyJDBC https://github.com/polyjdbc/polyjdbc/blob/master/src/main/java/org/polyjdbc/core/key/SequenceAllocation.java . Ogólnie, temat błędów w środowisku rozproszonym powinien być kontynuowany w oddzielnym issue, ponieważ z tego co rozumiem, nie ma związku z nadmiarowymi snapshotami

**Comment by bartoszwalacik** [comment]
redundant snapshots appears only in SQL repository, failing test pushed to https://github.com/javers/javers/tree/case_504

**Comment by bartoszwalacik** [comment]
After some digging I figured out that it's not a bug.
Simply, you forgot to implement equals() for your @Id type. I've added a section about this case in 
in documentaion - 
http://javers.org/documentation/domain-configuration/#entity-id-property **Object.equals()**
