### ISSUE TITLE
Sequence cache cannot be cleared (for tests)

### ISSUE THREAD

**Issue by mdii** [javers/javers#506]
Hi,

I am using JaVers 3.0.0 with Spring Boot. Some of our integration tests (using H2) fail because sequence values are cached in org.polyjdbc.core.key.SequenceAllocation and unless we re-initialize the spring context the cache is not cleared. 
It would be very helpful to be able to clear this cache before each test as we don't always re-initialize the spring context between tests.

**Comment by bartoszwalacik** [comment]
Hi, could you give a better description of the problem? Why your tests fail because of polyjdbc SequenceAllocation?

**Comment by bartoszwalacik** [comment]
maybe there should be a flag to simply disable SequenceAllocation in PolyJDBC

**Comment by mdii** [comment]
Yes, that would resolve the problem that I encountered.

**Comment by bartoszwalacik** [comment]
To be honest, I'm not sure how clearing the SequenceAllocation cache would fix your issue.
Could you provide a better description of your test scenario?

**Comment by mdii** [comment]
I am not able to reproduce the behavior that I encountered previously.
Maybe you can close this issue. I will open another one with a more complete description once I see again the issue that I had with the sequence cache.
