### ISSUE TITLE
BigInteger as ID for entityType causes INITIAL state to never exit

### ISSUE THREAD

**Issue by dwtalk** [javers/javers#507]
Using BigInteger as an @Id, I was unable to get the UPDATE state for my object, it would only stay in the INITIAL state. Adding BigInteger to the well known types fixed the issue as it allows to cdoID to properly be evaluated as the decimal representation of the BigInteger rather than a wonky string value (see attached)
![unspecified-7](https://cloud.githubusercontent.com/assets/1330371/23489722/9f69bdde-feb9-11e6-8d2b-46bd881f8006.png)

Pull request is being created for this.
.

**Comment by bartoszwalacik** [comment]
released in 3.0.3
