### ISSUE TITLE
Deal with Mysql Aoutoincrement ID

### ISSUE THREAD

**Issue by henryEcho** [javers/javers#518]
Hi, 

Currently I working on a project that build on top of Spring & MyBatis. I got an issue while persisting the object with autoincrement id in mysql. 
The object that i want to audit is mapped to the table.
When i put the @ID annoatation, it gives an "mapped as Entity has no Id property. Use @Id annotation to mark unique and not-null Entity identifier" error.
How could i assign the ID while the ID itself is automatically assigned by the database?

thank you.

**Comment by bartoszwalacik** [comment]
please move this question to http://stackoverflow.com/questions/tagged/javers
We will answer
