### ISSUE TITLE
Shallow References in Many-To-One (Single Edge) vs One-To-Many / Many-To-Many (Multi-Edge)

### ISSUE THREAD

**Issue by dimitarp** [javers/javers#528]
Why shallow references are considered when [building single edges](https://github.com/javers/javers/blob/master/javers-core/src/main/java/org/javers/core/graph/EdgeBuilder.java#L33) but [not multi-edges](https://github.com/javers/javers/blob/master/javers-core/src/main/java/org/javers/core/graph/EdgeBuilder.java#L78)?
Is this a bug or am I missing something?

Thanks in advance!

**Comment by bartoszwalacik** [comment]
looks like  a missing feature

**Comment by bartoszwalacik** [comment]
fix is released in 5.3.0
