### ISSUE TITLE
search changes for valueobject properties

### ISSUE THREAD

**Issue by fsoylemez** [javers/javers#530]
Hello,
I need to search for changes on a property of a valueobject.Somehow i couldnt figure it out.
i tried both findSnapshot and findChanges methods;i can reach first level properties but can not reach property of valueobjects.there is only reference valueobjectId,can not go further.

**Comment by bartoszwalacik** [comment]
issues are for bugs and feature requests, please ask questions at http://stackoverflow.com/questions/tagged/javers
