### ISSUE TITLE
Add a way for javers to sort by property name of snapshots and commits when paging.

### ISSUE THREAD

**Issue by wcchristian** [javers/javers#534]
I suggest adding a way to sort findSnapshots and findCommits so that the user can easily page while maintaining a sort.

Example usage.

`
javers.findSnapshots(QueryBuilder.byClass(Foo.class).skip(0).limit(100).sortBy('commitId').build());
`

The idea is that javers would sort the records before dealing with the skip and limit parameters.
This would allow for users to better make use of paging when they don't need the results to be sorted by date.

**Comment by bartoszwalacik** [comment]
JaVers always sorts by commitId in descending order. This is equiv to sorting by commit date desc. This order (reverse chronological) is fundamental for some javers features (like new Shadows) so we cant change it.

**Comment by wcchristian** [comment]
ok, thanks

**Comment by vmax1145** [comment]
As I can see in cluster environment with multiple nodes running
sorting by commitId gives wrong ordering...
Each node reserves  ids SEQUENCE_ALLOCATION_SIZE = 100L; 
that's lead to total order mess when same object is modified by different cluster nodes in different commits.
Please, reopen.

**Comment by bartoszwalacik** [comment]
right, we should disable sequence allocation for commit_id table

**Comment by PawanTiwariOodles** [comment]
.sortby('') method is not working , says add cast to method receiver

**Comment by bartoszwalacik** [comment]
in 3.9.1 we Fixed the implementaton of RANDOM CommitIdGenerator.
You can use it in distributed applications. 

```
Javers javers = javers().withCommitIdGenerator(CommitIdGenerator.RANDOM)
                        .build();
```
