### ISSUE TITLE
Possibility to manage Javers' SQL schema creation

### ISSUE THREAD

**Issue by bartoszwalacik** [javers/javers#542]
- flag to disable automatic schema creation
- method to call schema creation programatically

**Comment by antoniocasino** [comment]
Hi , I wrote a code that could manage schema creation, I wrote a test and connected it with h2. I had some issue with dependencies ( it's the first time I use gradle ) but it seems to work correctly.
I cloned the repo. What is the best way to share it?

**Comment by bartoszwalacik** [comment]
hi, just fork javers repo and then create the Pull Request

**Comment by bartoszwalacik** [comment]
see https://github.com/antoniocasino/javers/blob/master/CONTRIBUTING.md

**Comment by bartoszwalacik** [comment]
@antoniocasino, just released in 3.8.1
