### ISSUE TITLE
Extend jv_commit's author length or change it to text

### ISSUE THREAD

**Issue by Starkom** [javers/javers#551]
We use Spring's integration and its SpringSecurityAuthorProvider. And with growing of project and growing of count of roles in our system, provider generates too long values for DB schema with varchar(200) generated by 
https://github.com/javers/javers/blob/master/javers-persistence-sql/src/main/java/org/javers/repository/sql/schema/FixedSchemaFactory.java#L97

We workarounded it with altering table jv_commit's author column to varchar(400), but I think it's better to use text data type instead of string here.

**Comment by bartoszwalacik** [comment]
@Starkom thanks for reporting, feel free to create PR with change from `varchar(200)` to `varchar(400)`. I would like to stick to `varchar` because unbounded `text` seems to heavy.

**Comment by Starkom** [comment]
Unfortunately, I'm not close familiar with all supported databases. But in Postgres 'text' is much better than varchar(n). It is slight faster and takes the same storage space.

**Comment by Starkom** [comment]
Hmm, in MySQL varchar is much faster: https://stackoverflow.com/questions/11441823/when-to-use-text-in-mysql-instead-of-varchar

So there is no silver bullet :(

**Comment by bartoszwalacik** [comment]
true for Postgres, I wonder about MySql. OK, we can try with text and run perf tests

**Comment by bartoszwalacik** [comment]
That's the point, we also support Oracle and MS SQL, so maybe it would be safe to stay with varchar

**Comment by bartoszwalacik** [comment]
btw. why you stores user's roles in author column? there should be only user's login or id

**Comment by Starkom** [comment]
Yeah. I agree. I rewrote our code to using author field as only user-id, and to storing roles in commit's properties.
Anyway schema can be enhanced for Postgres. As I see there are separate logic for MysqlDialect in FixedSchemaFactory. So it can calls text() instead of string().withMaxLength(200/600) for PostgresDialect.

**Comment by bartoszwalacik** [comment]
if we define this col as text in PolyJdbc it will be:
in Postgres - `TEXT`
in MySQL - `TEXT`
in MsSQL - `VARCHAR(MAX)`
in Oracle - `CLOB`

We can do it but I don't see the clear use case, author field is indexed and designed to store human -redable user identity like Surname or email ...
