### ISSUE TITLE
Enhancement: Comments for Commits

### ISSUE THREAD

**Issue by f-aubert** [javers/javers#557]
I alllow myself another suggestion, having the feeling it could be easily implemented. But again I hope I did not miss anything. Could each commit be provided an optional textual comment? A bit like Git. It would be greater if it somehow could be provided in advance for all those spring data auto commits, but at the moment I cannot think of anything else than a method setNextCommitComment on the Javers Object. But I'd gladly discuss it with you!

**Comment by bartoszwalacik** [comment]
You can use commit properties for that (groovy):

```groovy
javers.commit("author", object, ["comment":"my change desc ..."])
```

see https://javers.org/javadoc_3.x/org/javers/core/Javers.html#commit-java.lang.String-java.lang.Object-java.util.Map-

**Comment by f-aubert** [comment]
Ok, that is what I missed... And then I suppose I shall try to use a CommitPropertyProvider Bean on which I would set the Comments before I pass my Entity to the Repository, and delete it afterwards.

**Comment by bartoszwalacik** [comment]
Exactly
