### ISSUE TITLE
Using Custom Comparators to return multiple ValueChanges on an object as well as Deep diffs

### ISSUE THREAD

**Issue by spnchian** [javers/javers#564]
How can I create a Custom Comparator that allows me to generate multiple Changes in an object. I'm not sure how to do that as the examples given in the docs allow only a single Change and it doesn't seem possible to wrap multiple Changes into a single Change object. 

How can I get Javers to generate a deep diff of Objects embedded inside the class that I am creating the Custom Comparator for. The Javers object seems to stop "diffing" once it hits the class with Custom Comparators. 

I am creating a Custom Comparator for Store. I want to have multiple Changes reflecting changes in the Store name and location while also having a deep diff on the Item class that is a part of Store. 
`public class Store`
`       String name`
`       String location`
`        Item item`

`public class Item`
      `String name`
      `int price`

Expected output:
  ValueChange on Store.name, Store.location. Diff on item as well.

**Comment by bartoszwalacik** [comment]
please move this question to https://stackoverflow.com/questions/tagged/javers
Issues is the place for bug reports and feature requests only
