### ISSUE TITLE
When using hibernate and spring boot the HibernateUnproxyObjectAccessHook does not cover all scenarios

### ISSUE THREAD

**Issue by dwtalk** [javers/javers#565]
The implementation of HibernateUnproxyObjectAccessHook and how it plugs into the GlobalIdFactory's create method covers most scenarios.

However, I did find an scenario where when a Query is build and run byInstance, the instance ID of the hibernate proxy is assumed and not the id of the desired object (which is proxied).

Specifically the error I was seeing is: "ENTITY_INSTANCE_WITH_NULL_ID" which will be resolved with a pull request momentarily.

I was able to correct the issue using the ObjectAccessHook in the createInstanceId method of the GlobalIDFactory just as it is used in the create method.

**Comment by dwtalk** [comment]
Pull request created for this 1 line fix

https://github.com/javers/javers/pull/566

**Comment by bartoszwalacik** [comment]
Thanks, PR merged, will be released tomorrow

**Comment by bartoszwalacik** [comment]
released in 3.3.5
