### ISSUE TITLE
Issue with ContainerChange class

### ISSUE THREAD

**Issue by TomekJurkowski** [javers/javers#567]
Hello, recently I've added javers to my project to handle audit logs and it is a great tool, but I found one problem with the ContainerChange class.
Imagine this scenario:
I have a class A:
```
class A {
    List<Int> numbers;
}
```
1. I create an instance of A with single element in the `numbers` list, let's say that element is 7
2. I update that instance of A, by extending `numbers` with another element, let's say 9

After these two steps, when I examine the changes logged by javers like this:
```
Javers javers = JaversBuilder.javers().build();
List<Change> changes = javers.findChanges(QueryBuilder.byClass(A.class).build());
```
the update that I did instep 2. is represented by a `ContainerChange` object with two elements in its internal `changes` list. Those elements are:
- `ElementValueChange` with `leftValue = 7` and `rightValue = 9`
- `ValueAdded` with `value = 7`

I find this to be rather weird. Can you explain to me why it's done like this?

Personally, I would expect `ContainerChange.changes` to contain either
- single `ValueAdded` with `value = 9`
or
- `ValueRemoved` with `value = 7`, `ValueAdded` with `value = 7` & `ValueAdded` with `value = 9`

**Comment by bartoszwalacik** [comment]
so you have the left list:
[7]
and the right list is:
[7,9] or [9,7]
?

**Comment by TomekJurkowski** [comment]
ok, I think I know what you are getting at.
Within my object of Class A I initially had [7], and after the update it has [9, 7].
So one can say that the very first item in the list has changed from 7 to 9 and then a new item 7 has been added to the list.

Am I to understand that if the list after update was [7,9] then `ContainerChange` object would only have `ValueAdded(value = 7)` on its change list?

**Comment by bartoszwalacik** [comment]
yes, ValueAdded(value = 9)

**Comment by bartoszwalacik** [comment]
see https://javers.org/documentation/diff-configuration/#simple-vs-levenshtein

**Comment by TomekJurkowski** [comment]
right, thanks!
