### ISSUE TITLE
Shadows don't represent a complete view

### ISSUE THREAD

**Issue by mdii** [javers/javers#568]
Hello, 
I was recently playing with querying shadows. I find it a great and useful feature, however I noticed that when I query for a rather complex object the historical view is not fully returned.

I have an entity X that has a many-to-one relationship with entity Y. 
Ys are created and updated independently of Xs, so when an X is updated no snapshot is created for its Y. Now when I query for shadows of X, the value of its Y is null. I believe in this case, the shadow query should look for the last snapshot of Y that precedes the snapshot of X.

I am not sure how exactly shadow creation works, but it seems that it searches the object graph in the same commit.

**Comment by bartoszwalacik** [comment]
Hi, good question. In fact, Shadows query can return incomplete graph, when some Entity not exists in any commit in your query scope (assuming that you are using COMMIT_DEPTH).
I think we should create the third, broader query scope, lets say FULL_DEPTH.

When using this scope, JaVers would load latest Shadow of the missing Entity. It would give you full graph but you pay in extra db queries.

**Comment by bartoszwalacik** [comment]
I'm going to develop this as the next feature in javers

**Comment by bartoszwalacik** [comment]
fixed in 3.5.0
New scope: commit-seep+ 
see https://javers.org/documentation/jql-examples/#shadow-scopes
