### ISSUE TITLE
ShallowReference and Id

### ISSUE THREAD

**Issue by mdii** [javers/javers#573]
Hello,

I am wondering if it is possible to have ShallowReference on the identifier of an entity.
In my use case I have a one-to-one mapping between X and Y. If I use the id of X as the primary key of Y I get StackOverflow error when I persist X. When I use a generated id for Y, everything works fine.

**Comment by bartoszwalacik** [comment]
For an Entity, a type of its Id-property should be Value and it should be possible to use the same type (Value) in many Entity. I don't know why you are getting StackOverflow error, could you push a failing test case with the reproduction scenario?

**Comment by mdii** [comment]
The problem I mentioned is rather an entity modeling issue and so I don't think it is a limitation in javers. Therefore I close this issue.
