### ISSUE TITLE
Java EE Support

### ISSUE THREAD

**Issue by mark1900** [javers/javers#575]
I am looking into Java EE integration (JPA, CDI, EJBs, etc ) with Javers and I don't see any specific documentation on this.

I am slightly worried as I looked at the [spring-integration](https://javers.org/documentation/spring-integration/) and it seems like there is quite a few classes in the supporting library - [javers-spring source](https://github.com/javers/javers/tree/master/javers-spring).

If I extracted and reused the following classes, would the following code be expected to work as expected?  Or would more work be required?
* [JpaHibernateConnectionProvider.java](https://github.com/javers/javers/blob/master/javers-spring/src/main/java/org/javers/spring/jpa/JpaHibernateConnectionProvider.java)
* [HibernateUnproxyObjectAccessHook.java](https://github.com/javers/javers/blob/master/javers-spring/src/main/java/org/javers/hibernate/integration/HibernateUnproxyObjectAccessHook.java)

```java
ConnectionProvider connectionProvider = new JpaHibernateConnectionProvider();

JaversSqlRepository sqlRepository = SqlRepositoryBuilder
		.sqlRepository()
		.withConnectionProvider(connectionProvider)
		.withDialect(DialectName.MSSQL)
		.withSchema( "javers" )
//        .withObjectAccessHook( new HibernateUnproxyObjectAccessHook() )
		.build();

sqlRepository.ensureSchema();

javers = JaversBuilder
		.javers()
		.withMappingStyle( MappingStyle.BEAN )
		.registerJaversRepository( sqlRepository )
		.build();
```

**Comment by bartoszwalacik** [comment]
Sorry, but I don't understand this issue.
javers-spring module wokrs with all Spring applications
javers-persistence-sql module works for Spring applications with JPA + Hibernate persistence.
Currently, we do not offer any integration for EJB or other DI containers.

Of course you can take some classes from JaVers codebase and reuse/extend them in different context but you are doing it on your own risk.

**Comment by mark1900** [comment]
I was hoping for a javers-jee library and this is why I created the "Java EE Support" feature request.  Unfortunately, the current solutions (javers-spring and javers-persistence-sql) have a dependency on Spring.    

I definitely understand creating a javers-jee library is at my own risk, though if you have any input it would be much appreciated.
