### ISSUE TITLE
improvement: QueryParams that allow filtering by duplicated commitProperties

### ISSUE THREAD

**Issue by TomekJurkowski** [javers/javers#578]
Hello @bartoszwalacik, I have a suggestion for an improvement, that came to my mind while working on a project, where I use javers. The QueryParams class allows us to add commitParameters, that can be used as filters while fetching snapshots from javers. It's very cool and all, but do you think it would be possible to make the `QueryParams.commitParameters` a multimap?

Here's a use case where I personally would find it very useful to have:
Imagine we want Javers to save audit info about such class:
```
class Classroom {
    studentIds: List<Int>
    ...
}
```

and then we would like to find all audit logs filtered by student's id.
With current implementation it is not possible to do so, am I right?

To provide such functionality I used an ugly workaround:
- I created a String constant:
 ```STUDENT_ID_COMMIT_PROPERTY_VALUE = "student_id"```
- I would commit a Classroom object to javers like this:
```javers.commit(author, record, prepareCommitProperties(record))```
where
```
private Map<String, String> prepareCommitProperties(record: Classroom) {
    HashMap<String, String> map = new HashMap()
    record.studentIds.forEach {
        studentId -> map.put(studentId, STUDENT_ID_COMMIT_PROPERTY_VALUE)
    }
    return map
}
```
- I would retrieve filteredsnapshots by setting a proper commitProperty on QueryBuilder:
```queryBuilder.withCommitProperty(studentId.toString(), STUDENT_ID_COMMIT_PROPERTY_VALUE)```

This solution works, but is rather bad and misleading, as I put values to the commitParameters map as keys. Is there a better way in javers to deal with my use case? Or maybe transforming commitParameters to a multimap could be added?

Best regards!

**Comment by bartoszwalacik** [comment]
Hi @TomekJurkowski, nice workround :) There is no better way without changing your domain model.
Commit properties are designed to store commit metadata and not data extracted from domain objects. We don't want to change Commit properties into more complex structure.

What I can suggest you is to altering your domain model and leverage Shadow queries,
for example:

```
class Classroom {
     List<Student> students
}
```

see https://javers.org/documentation/jql-examples/#shadow-scopes

**Comment by TomekJurkowski** [comment]
Thank you for your response @bartoszwalacik ! :)
