### ISSUE TITLE
openjpa: Change Type wrong?

### ISSUE THREAD

**Issue by P8hJ** [javers/javers#581]
Hello

Did you see my problem?

https://stackoverflow.com/questions/46279841/javers-cdosnapshot-snapshottype-different-from-mssql-to-h2

It looks to me like a bug? Correct?

**Comment by bartoszwalacik** [comment]
Hi, did you read https://github.com/javers/javers/blob/master/CONTRIBUTING.md#guidelines-for-bug-reporting ?

**Comment by bartoszwalacik** [comment]
see Stack
