### ISSUE TITLE
Typo in documentation: "us" should be "as"

### ISSUE THREAD

**Issue by mmoayyed** [javers/javers#586]
> JaVers treats ValueObjects as property containers and doesn’t care much about their classes. This approach is known ~~us~~ Duck Typing, and is widely adopted by dynamic languages like Groovy.

Should be:

> JaVers treats ValueObjects as property containers and doesn’t care much about their classes. This approach is known <i>**as**</i> Duck Typing, and is widely adopted by dynamic languages like Groovy.

I am not sure where the documentation is maintained, or I would have gladly submitted a PR to fix.

Link https://javers.org/documentation/jql-examples/ under "Free ValueObjects refactoring"

**Comment by bartoszwalacik** [comment]
Please create a PR here http://github.com/javers/javers.github.io

**Comment by bartoszwalacik** [comment]
fixed, thanks
