### ISSUE TITLE
Commit withdrawal

### ISSUE THREAD

**Issue by bartoszwalacik** [javers/javers#588]
In some cases, user need to withdraw certain commits. For example:

* transaction rollback - if JaVers data are  stored in different database than application data. When transaction is roll-backed in application's database, we should also withdraw commits persisted in JaVers repository
* commits with malformed data caused by some bug in an application
* case described here https://github.com/javers/javers/issues/587  posted by @mmoayyed

**Comment by bartoszwalacik** [comment]
API design:

`javers.withdrawCommit(CommitId)`

test cases:
1. when latest snapshot (commit which contain only latest snapshots), commit object with its snapshots should be deleted from db. This is a happy path
1. when initial snapshot is withdrawn, next snapshot should be marked as initial (if exists)
1. when snapshot-in-the-middle is withdrawn, Change Queries should not brake, see `SnapshotIdentifier.previous()`
1. when entity snapshot is withdrawn and there are valueObjects owned by this entity (and they have snapshots in next commits) we can't make them orphans. Look like owning entity snapshot cant be simply deleted but moved to next commit

@mmoayyed if you are eager to contribute, I think we can start from writing failing E2E tests for these cases, preferably in JaversRepositoryE2ETest

**Comment by mmoayyed** [comment]
Sounds good. Let me get a functional build first and then I'll put together tests etc.

**Comment by windbender** [comment]
I like this idea.  Question:  can you remove a commitId if there are already subsequent commits ?  

I could imagine a case where this might be trivial possible ( commits are in different areas of the object graph ) and then areas where a subsequent commit might modify the same data.

**Comment by bartoszwalacik** [comment]
That's the case no. 3 that I've described. Fortunately, snapshots are almost unaware of each other. The only dependency between them is the `previous()` reference, which should be updated.

**Comment by cameronbraid** [comment]
Is this still something that is on the table ?  Async auditing is something I am interested in.

**Comment by bartoszwalacik** [comment]
Now, I'm the only one guy working on JaVers and my plans for the next months are:

    async commit - https://github.com/javers/javers/issues/593
    optimizing SQL repo performance

So if you need commit withdrawal, the only way is your contribution. We can work together on design, but coding is on your side :)

**Comment by bartoszwalacik** [comment]
i don't believe anyone can implement it
