### ISSUE TITLE
Doubt latest version

### ISSUE THREAD

**Issue by phelypp** [javers/javers#59]
Hello Friends 

Last Version in maven repository was compile JDK 8?

Thanks!

**Comment by anassBo** [comment]
Hi,

can you please tell me how to run javers on jdk 5.0.
i am working on an existing project that is already build with jdk5.0 and we want to add data audit functionnality.

thanks a lot for your response

**Comment by bgalek** [comment]
We're sorry but javers supports only jdk 1.7 and above. We hope that you
will upgrade to java 8 soon :)
3 mar 2015 16:52 "anassBo" <notifications@github.com> napisał(a):
