### ISSUE TITLE
JsonConverter.toJson(null) returns non-JSON format result

### ISSUE THREAD

**Issue by rasputin243** [javers/javers#592]
Passing null to the toJson() as shown below returns a string equal to `null`:
`System.out.println(_jsonConverter.toJson(null));` 

I would expect the result to be `{ }` considering that the result should be JSON-formatted.

**Comment by rasputin243** [comment]
JsonConverter appears to wrap Google's gson.toJson() method: 

`public String toJson(Object value) {
        return this.gson.toJson(value);
    }` 

It would be simple to check if the returned string is like `null` and return `{ }` instead.

**Comment by bartoszwalacik** [comment]
null is right JSON, you can check it in your browser dev tools:

```javascript
JSON.stringify({});
"{}"
JSON.stringify(null);
"null"
JSON.stringify([1,2]);
"[1,2]"
```
