### ISSUE TITLE
FindShadows() with withChildValueObjects and withScopeDeepPlus returns wrong number of nested collection child

### ISSUE THREAD

**Issue by philippeboyd** [javers/javers#602]
I don't understand why shadows return the wrong amount of collection child.

basically here's the code :

```java
Role roleAdmin = new Role("ADMIN");
roleAdmin.setPermissions(Lists.newArrayList(permissionReadUser, permissionViewUser, permissionCountUser, permissionExistsUser, permissionCreateUser));
roleAdmin = roleRepository.save(roleAdmin); // First version of role admin (5 permissions)

roleAdmin.setDescription("Admin role :D");
roleAdmin = roleRepository.save(roleAdmin); // Second version of role admin (5 permissions + description)

roleAdmin.getPermissions().add(permissionUpdateUser);
roleAdmin.getPermissions().add(permissionDisableUser);
roleAdmin.getPermissions().add(permissionDeleteUser);
roleAdmin = roleRepository.save(roleAdmin); // Third version of role admin (8 permissions + description)
```

So technically, 
on version 1, I would have : 5 Permissions, no description
on version 2, I would have : 5 Permissions, with description
on version 3, I would have : 8 Permissions, with description

However, when I query the shadows, this is the result (from logs):

```java
JqlQuery jqlQuery = QueryBuilder.byInstanceId(roleAdmin.getId(), Role.class)
		.withChildValueObjects()
		.withScopeDeepPlus()
		.build();

List<Shadow<Role>> shadows = javers.findShadows(jqlQuery);

shadows.forEach(e -> {
	System.out.println(e.get());
	System.out.println("SNAPSHOT roleAdmin permission size : " + e.get().getPermissions().size());
});
```

```
// VERSION 3
Role{permissions=[READ_USER, VIEW_USER, COUNT_USER, EXISTS_USER, CREATE_USER, UPDATE_USER, DISABLE_USER, DELETE_USER], name='ADMIN', description='Admin role :D'}
SNAPSHOT roleAdmin permission size : 8

// VERSION 2
Role{permissions=[READ_USER, VIEW_USER], name='ADMIN', description='Admin role :D'}
SNAPSHOT roleAdmin permission size : 2

// VERSION 1
Role{permissions=[], name='ADMIN', description='null'}
SNAPSHOT roleAdmin permission size : 0
```

The last version seems to be fine, however, the other 2 are not.

You can find my repository here : https://github.com/philippeboyd/javers-issue-managed-type
make sure to checkout branch `shadow_bug`

**Comment by philippeboyd** [comment]
Ok I'm mind blowned! I found the solution to this problem which is not what I was expecting after following the Javers Doc...

When I put `Integer.MAX_VALUE` as the `maxGapsToFill` argument to `withScopeDeepPlus()` it works as intended. 

```java
JqlQuery jqlQuery = QueryBuilder.byInstanceId(roleAdmin.getId(), Role.class)
		.withChildValueObjects()
		.withScopeDeepPlus(Integer.MAX_VALUE)
		.build();
```
```
// VERSION 3
Role{permissions=[READ_USER, VIEW_USER, COUNT_USER, EXISTS_USER, CREATE_USER, UPDATE_USER, DISABLE_USER, DELETE_USER], name='ADMIN', description='Admin role :D'}
SNAPSHOT roleAdmin permission size : 8

// VERSION 2
Role{permissions=[READ_USER, VIEW_USER, COUNT_USER, EXISTS_USER, CREATE_USER], name='ADMIN', description='Admin role :D'}
SNAPSHOT roleAdmin permission size : 5

// VERSION 1
Role{permissions=[READ_USER, VIEW_USER, COUNT_USER, EXISTS_USER, CREATE_USER], name='ADMIN', description='null'}
SNAPSHOT roleAdmin permission size : 5
```

I haven't go deeper but why does `maxGapsToFill` influences the number of elements in a collections?

maxGapsToFill has a default value of 10. Therefore, If i put 6 as the argument, I will have the following result : 

```java
JqlQuery jqlQuery = QueryBuilder.byInstanceId(roleAdmin.getId(), Role.class)
		.withChildValueObjects()
		.withScopeDeepPlus(6)
		.build();
```

```
// VERSION 3
Role{permissions=[READ_USER, VIEW_USER, COUNT_USER, EXISTS_USER, CREATE_USER, UPDATE_USER], name='ADMIN', description='Admin role :D'}
SNAPSHOT roleAdmin permission size : 6 <-- because maxGapsToFill is at 6

// VERSION 2
Role{permissions=[], name='ADMIN', description='Admin role :D'}
SNAPSHOT roleAdmin permission size : 0

// VERSION 1
Role{permissions=[], name='ADMIN', description='null'}
SNAPSHOT roleAdmin permission size : 0
```

@bartoszwalacik , I don't know how to explain this behaviour...

**Comment by bartoszwalacik** [comment]
`maxGapsToFill` limits the number of *referenced* entities to be loaded. It doesn't mater if they are stored in collections or simply as field referenses. Each object counts.

Maybe we should rename this parameter to `maxReferencedObjectToLoad` ...

**Comment by philippeboyd** [comment]
I understand, but it still doesn't explain why there's a collection size of 0 on version 1 and 2 from my previous example when using `maxGapsToFill` at 6

**Comment by bartoszwalacik** [comment]
no? when you set maxGapsToFill = 6, you get max 6 references resolved (the limit is global for the query)

**Comment by philippeboyd** [comment]
Ah! I thought it was for each shadow. Thanks for the explanation @bartoszwalacik

**Comment by bartoszwalacik** [comment]
looks like I need to improve the docs:) I'm working on better logging (kind of a profiler for Shadow queries). It will help in cases like this, stay tuned

**Comment by bartoszwalacik** [comment]
see changes in 3.7.5 https://javers.org/release-notes
