### ISSUE TITLE
Compare Lists Like Sets

### ISSUE THREAD

**Issue by drakin** [javers/javers#605]
Add new compare Algorithm to be able compare lists like a sets (ignoring ordering).
For now, If we want to compare collection without ordering, we should to use sets.
In case, when we need to ignore ordering and we can not to change existing lists Objects to sets we have some troubles. 
We can not to change our model and use Sets.

**Comment by bartoszwalacik** [comment]
👍

**Comment by bartoszwalacik** [comment]
@drakin thanks for your contribution. Since merge, you are listed on https://javers.org/ as a JaVers contributor. Now we need to update the docs and the change will be ready to release.

**Comment by bartoszwalacik** [comment]
I mean this section https://github.com/javers/javers.github.io/blob/master/documentation/diff-configuration/index.md

**Comment by bartoszwalacik** [comment]
released in 3.7.0, see https://javers.org/documentation/diff-configuration/#list-algorithms
