### ISSUE TITLE
IllegalArgumentException when there're multiple snapshots with the same version

### ISSUE THREAD

**Issue by cybuch** [javers/javers#608]
For some reason there's null snapshot here: https://github.com/javers/javers/blob/master/javers-core/src/main/java/org/javers/core/snapshot/SnapshotDiffer.java#L72
Then it's passed to ObjectNode via constructor where it explodes with IllegalArgumentException, because of non-null validation.

**Comment by bartoszwalacik** [comment]
Please provide a runable example with a bug reproduction

**Comment by cybuch** [comment]
https://github.com/cybuch/javers/blob/master/javers-core/src/test/groovy/org/javers/core/JaversLeakingNullTest.groovy

Here you are. 
Some explanation: This has happened to me in production environment, I didn't debug why. We used several versions of Javers since 1.x to 3.x right now (configured with spring boot starter). I'm aware that `SnapshotDiffer` has method with comment that it expects that the previousSnapshots map contains predecessors of all non-initial and non-terminal snapshots. However shouldn't it fail fast on line 44 then (where the map returns null)? All I've got is `IllegalArgumentException` - null passed to `ObjectNode`. It doesn't tell me much. Few ideas: fail fast and throw self explaining exception? E.g. 'your entity history is inconsistent'. Remove that change from the list of changes that will be returned and maybe log a warning? It would be just nice to let developer know what has happened and what he/she can do to fix situation instead of returning `IllegalArgumentException`

**Comment by bartoszwalacik** [comment]
So as far as I understand, you have missing records in your database?  How did it happened?
Javers is not prepared for data corruption in its database. It's hard to handle this kind of exceptions. All we can do is to improve the error message.

**Comment by cybuch** [comment]
So it seems. I don't know how it happened, we don't touch javers data at all. Recently we just wanted to present it to users and then it exploded. I have to check if there's any pattern (how often this situation occurs and so on), but in the debug I saw e.g. 20 snapshots and the last one that was being processed had missing previous snapshot

**Comment by bartoszwalacik** [comment]
That's strange. There are two options:

* Someone manually deleted records in your Javers database. If so, we need to improve the error message.
* There is an error in Javers and snapshots are created with wrong version number. If that's true, it means there is a serious bug in Javers code.

The only way to find out what's going in is to check your data. Check your snapshots state, authors and timestamps. Are there missing records?

**Comment by cybuch** [comment]
We've checked the db state and the real problem is multiple snapshots with the same version, will provide test case later

**Comment by cybuch** [comment]
Problem solved: Javers data was OK, I've found this issue on non-production environment with corrupted data.
