### ISSUE TITLE
Deep compare collections

### ISSUE THREAD

**Issue by umk8yw** [javers/javers#619]
Hello, 

I have a collection as a property for my object and I am trying to do a compare action.
I have read here 
http://www.atetric.com/atetric/javadoc/org.javers/javers-core/1.3.4/org/javers/core/Javers.html 
that if I "wrap collections in some Value Objects" the deep comparing of the collection is possible.

My question is, how exactly I can wrap my collection into Value Objects?

Thank you

**Comment by bartoszwalacik** [comment]
please ask questions on stack http://stackoverflow.com/questions/tagged/javers?sort=newest

**Comment by umk8yw** [comment]
Sure, I've moved my question here:
https://stackoverflow.com/questions/47864608/wrap-collections-in-value-objects
