### ISSUE TITLE
Losing CommitId accuracy as long is converted to double

### ISSUE THREAD

**Issue by ngbalk** [javers/javers#630]
https://github.com/javers/javers/blob/a59a1bed2a5e0ff35e311f7d87f80249bc30ae4c/javers-core/src/main/java/org/javers/core/commit/CommitId.java#L55

If the majorId in CommitId is sufficiently large (more than 17 digits and approaching Long.MAX_VALUE), we lose accuracy  in our remaining digits when we perform the following calculation:

`        return new BigDecimal(majorId+(minorId*.01)).setScale(2, BigDecimal.ROUND_HALF_UP);
`

because the majorId (long) is implicitly converted to a double. Explained: https://stackoverflow.com/questions/17930910/converting-long-to-double-in-java-i-found-some-discrepancy

The consequence of this is that many different commitIds will be rounded to the same value when they are serialized and persisted.  Then, javers fails to correctly build Shadows, since many snapshots will have the same commitIds.

**Comment by ngbalk** [comment]
As an additional note, you might be wondering how one gets themselves in a situation where you have such a large commitId... I was previously using the now deprecated CommitIdGenerator.RANDOM to create my commitIds, and now when i switched to CommitIdGenerator.SYNCHRONIZED_SEQUENCE, I ended up with very large commitIds going forward.

**Comment by bartoszwalacik** [comment]
RANDOM Generator is deprecated now, any other ideas than simply updating all CommitIDs in your database to sequence?

**Comment by ngbalk** [comment]
It seems to me that any migration from RANDOM to SEQUENCE will likely face this problem as Javers will begin sequencing on top of the latest large random value (stored in **jv_head_id** table).  My fix was to manually edit **jv_head_id** to be a smaller number (i.e. 0.0)

**Comment by bartoszwalacik** [comment]
Luckily, RANDOM generator wasn't very popular :)
I don't see easy fix for this case in javers code, so recommended solution is manual db update.
