### ISSUE TITLE
Fail to JaversCore.findChanges when domain class is missing

### ISSUE THREAD

**Issue by olekihnatowicz** [javers/javers#632]
Source code was refactored and one class was deleted. From now on I am unable to query Javers for changes (JaversCore.findChanges) if theses changes contains removed class.

Solution: Add registerDeletedClasses (in JaversBuilder) to inform Javers that snapshot for these types should be ignored in JaversCore.find*. In javers starters there should be config field - list of ignored types.

**Comment by olekihnatowicz** [comment]
Alternatively if snapshots are not needed for other purposes (audit), we can provide tool to remove these snapshots from db during migration.

**Comment by bartoszwalacik** [comment]
connected with 
https://github.com/javers/javers/issues/723

**Comment by bartoszwalacik** [comment]
probably fixed in https://github.com/javers/javers/issues/723
