### ISSUE TITLE
Auto Detected Mapping style

### ISSUE THREAD

**Issue by angeliski** [javers/javers#633]
Is possible implement something like auto detect for the mapping style? I work in a legacy project and sometimes I need use mixed mapping styles. Is very difficult when I need change one big entity just to Javers work. Will be nice if I can configure Mixed style and Javers make like simple try-catch test

**Comment by bartoszwalacik** [comment]
at least, you end with better code :) 
why mixing, why you can't just use FIELD?

**Comment by angeliski** [comment]
Simple, because I can't refactor the entire base legacy in one shot. Is a transition stage. If I don't have a MIX, I can't put the refactor in production.

**Comment by bartoszwalacik** [comment]
still, I dont understand why want to mix FIELD with BEAN. Try to describe the problem, then we could talk about possible solutions

**Comment by angeliski** [comment]
Sorry. Maybe I have understanded the problem wrong. I have one web application where I having the annotation @Id in Fields and in get methods. When I use both, the Javers broke. The result is JaversException ENTITY_WITHOUT_ID.

**Comment by bartoszwalacik** [comment]
You can have annotations both on fields and getter, it's not a problem for Javers

**Comment by bartoszwalacik** [comment]
@angeliski please come back when you come up with a better description of your problem, a failing test would be helpful
