### ISSUE TITLE
TypeMapperState prints to System.out

### ISSUE THREAD

**Issue by lybeck** [javers/javers#634]
The class [TypeMapperState](https://github.com/javers/javers/blob/ded405134d6cc8f8be51005688a781b7b5abea77/javers-core/src/main/java/org/javers/core/metamodel/type/TypeMapperState.java#L166) outputs debug info to `System.out`, should probably use `Logger::debug` instead.

**Comment by bartoszwalacik** [comment]
Looks like a minor issue, just contribute a pull request
