### ISSUE TITLE
Enhancement: Snapshots collection name should be configurable.

### ISSUE THREAD

**Issue by ngbalk** [javers/javers#636]
https://github.com/javers/javers/blob/0b6c518753e5838d7c7f05366d5727dbe6a39af1/javers-persistence-mongo/src/main/java/org/javers/repository/mongo/MongoSchemaManager.java#L18

This would allow for different services with different domains to use different collections to store versioned objects.  Otherwise many services share the **same collection** to store versioned objects - can lead to the collection getting very large, and scaling strategies (**sharding**, for example) could differ from one domain object to another domain object.  

For example, If i have a **PersonService** and a **CarService**, I might want to have collections **jv_snapshots_persons** and **jv_snapshots_cars** to keep the two domains separate and allow me to employ different sharding strategies for the collections.

In this spirit of this enhancement, I'm curious how people are scaling this collection jv_snapshots, especially when it comes to sharding.

**Comment by bartoszwalacik** [comment]
A quick solution when having different services would be different db schemas. I don't know much about sharding, but the approach you suggest - separate Snapshots collection/table for each class looks like a nice feature also for SQL databases. Let me know If you are going to contribute it.

**Comment by ngbalk** [comment]
After giving this some thought, I think that separate collections for writing could be achieved fairly simply - we could pull out the class name from **globalId.entity.ownerId** and write snapshots to a collection by that name (for example if the class was called Person, we could write to **jv_person**).  Reading / querying would present a bigger challenge - how would we want to handle class-independent queries like: **QueryBuilder.anyDomainObject()**.  Javers should query all collections / tables and aggregate the result?

**Comment by bartoszwalacik** [comment]
I think that collection or table name should be declared explicitly in a separate annotation. Reusing class or type name would make refactoring harder.
And you are right about `anyDomainObject()` - it means select from all tables and merging, not nice :(

**Comment by ngbalk** [comment]
So I've implemented a basic version of this feature in this [commit](https://github.com/ngbalk/javers/commit/fa2db2b11d783ea9c755b4905d089dfccaf82b8e)

I've added an annotation [@PersistenceLocation](https://github.com/ngbalk/javers/blob/fa2db2b11d783ea9c755b4905d089dfccaf82b8e/javers-core/src/main/java/org/javers/core/metamodel/annotation/PersistenceLocation.java#L11) which lets you specify where each domain object should be persisted to (i.e. in Mongo, the collection name).  Writing to the DB is easy enough, but querying is where its more challenging and I haven't quite come up with a great solution yet.  Right now, we are querying **_every_** snapshot collection in order to find the snapshots we are looking for in a particular query.  I haven't yet found a way to efficiently handle all the dynamic queries Javers supports (i.e. query by class name, valueObject path, class name + child objects, etc.).

Would love to get your feedback.

**Comment by ngbalk** [comment]
My attempt at "smarter" queries (i.e. trying to infer which collection to query based on the query itself) is [https://github.com/ngbalk/javers/commit/bb03f8ed662616afd20f4c9514c9f182f33b4b35](url).

As you can see, it wouldn't handle all query cases.

**Comment by bartoszwalacik** [comment]
See my comments. Most queries concern single Entity so they can be run on one collection

**Comment by ngbalk** [comment]
Thanks for the comments.   Per your note above, we could have a strategy where we "try" on the one collection, and if we can't find anything, we do more of a broadcast query.  Should help optimize that a bit.

**Comment by bartoszwalacik** [comment]
Looks like nobody is working on this

**Comment by tinesoft** [comment]
What is the current status of @ngbalk's solution?

From what i understand reading this thread, the "writing to different collections" part is pretty well handled by his mentioned [commit](https://github.com/ngbalk/javers/commit/fa2db2b11d783ea9c755b4905d089dfccaf82b8e) , but the main issue now lies in how to efficiently query the db for snapshots afterwards. Am i right?

So what about his last suggested approach to optimize then?

> Thanks for the comments. Per your note above, we could have a strategy where we "try" to fulfill our query on one collection (if it concerns a single Entity), and if we can't find anything, we do more of a broadcast query. Should help optimize that a bit.

I can maybe provide my help if this approach is validated...

**Comment by bartoszwalacik** [comment]
@tinesoft yes you are right, write is done, but read is more tricky. The algorithm should work in this way:

* ValueObjects should be stored in the same collection like their owning Entities
* In JaVers we have three types of queries:
    * Query by Id - it's easy to implement it by reading only one collection
    * Query by type - the same, we know which collection it is
    * Any object query - this query would be hard to implement on many collections (merging & sorting on the java side would be troublesome and slow). For know I suggest to not implement it and come up with some 'good enough' or incubating solution. It would be fast and useful as soon as you don't need Any object query.

I can create a branch for it in the javers repo and give access for you guys.

**Comment by tinesoft** [comment]
Hi @bartoszwalacik 

Thanks for your feedback.
This feature would be terrific. And i'm willing to spend sometime on it.
For now, if you could just create the branch, i'll fork the repo and gladly submit a PR.

**Comment by bartoszwalacik** [comment]
ok, you should have access to the javers repo now,
the branch:
`mongo-collection-for-each-entity`

**Comment by tinesoft** [comment]
Great! I've just joined the javers organisation!
Will start working one this feature asap :)

**Comment by ngbalk** [comment]
@tinesoft Glad to see you're picking this up! I'm still very interested in this feature as well.  Let me know if I can be of any assistance.

**Comment by tinesoft** [comment]
Hi @bartoszwalacik.

Sorry for the delay on resolving this issue,  I've been lacking free time to continue what  @ngbalk had started...

But that should change in the coming days, so I'll continue the work. You can keep the ticket opened. Thanks!

**Comment by kritikapasricha** [comment]
Any updates on this? It looks like people started working on this an year back.

**Comment by bartoszwalacik** [comment]
Looks like this issue is abandoned. Let me know if you guys come up with a PR, than I will reopen it.
