### ISSUE TITLE
Deailing with ObjectId

### ISSUE THREAD

**Issue by ctmay4** [javers/javers#64]
Using Morphia, the primary identifier is always an ObjectId.  They are annotated in Morphia with @Id.  In my particular case, I have an entity where is ObjectId is the database unique identifier, but for end users I represent uniqueness by three fields (algorithm, version, name).  So in the JSON mapping that gets returned through an API, the ObjectId is actually hidden to end users.  Using ObjectId as the key for the diffs would be fine, however I am having a few issues:

Here is a basic test case:

``` java
import org.bson.types.ObjectId;
import org.javers.core.Javers;
import org.javers.core.JaversBuilder;
import org.javers.core.diff.Diff;
import org.junit.Test;
import org.mongodb.morphia.annotations.Embedded;
import org.mongodb.morphia.annotations.Entity;
import org.mongodb.morphia.annotations.Id;
import org.mongodb.morphia.annotations.Property;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

public class JaVersTest {

    @Embedded
    @Entity(noClassnameStored = true)
    public class TopLevelEntity {

        @Id
        private ObjectId _id;
        @Property("algorithm")
        private String _algorithm;
        @Property("version")
        private String _version;
        @Property("name")
        private String _name;
        @Property("description")
        private String _description;

        public TopLevelEntity() {
        }

        public TopLevelEntity(ObjectId id, String algorithm, String version, String name) {
            _id = id;
            _algorithm = algorithm;
            _version = version;
            _name = name;
        }

        @JsonIgnore
        public ObjectId getId() {
            return _id;
        }

        public void setId(ObjectId id) {
            _id = id;
        }

        @JsonProperty("algorithm")
        public String getAlgorithm() {
            return _algorithm;
        }

        public void setAlgorithm(String algorithm) {
            _algorithm = algorithm;
        }

        @JsonProperty("name")
        public String getName() {
            return _name;
        }

        public void setName(String name) {
            _name = name;
        }

        @JsonProperty("version")
        public String getVersion() {
            return _version;
        }

        public void setVersion(String version) {
            _version = version;
        }

        @JsonProperty("description")
        public String getDescription() {
            return _description;
        }

        public void setDescription(String description) {
            _description = description;
        }
    }

    @Test
    public void testBasic() {
        Javers javers = JaversBuilder.javers().build();

        ObjectId id = ObjectId.get();

        TopLevelEntity entity1 = new TopLevelEntity(id, "alg1", "1.0", "name1");
        TopLevelEntity entity2 = new TopLevelEntity(id, "alg1", "1.0", "name1");
        entity2.setDescription("A new description");

        Diff diff = javers.compare(entity1, entity2);
        System.out.println("diff: " + javers.toJson(diff));
    }
```

Here I am relying on the @Id to define the key.  It returns the following error:

```
java.lang.RuntimeException: error getting unwrap from field '_time'
    at org.javers.common.reflection.ReflectionUtil.invokeField(ReflectionUtil.java:187)
    at org.javers.common.reflection.ReflectionUtil.invokeFieldEvenIfPrivate(ReflectionUtil.java:179)
    at org.javers.core.metamodel.property.FieldProperty.get(FieldProperty.java:44)
    at org.javers.core.metamodel.object.CdoWrapper.getPropertyValue(CdoWrapper.java:35)
    at org.javers.core.graph.ObjectNode.getPropertyValue(ObjectNode.java:78)
    at org.javers.core.diff.RealNodePair.isNullOnBothSides(RealNodePair.java:29)
    at org.javers.core.diff.DiffFactory.appendPropertyChanges(DiffFactory.java:108)
    at org.javers.core.diff.DiffFactory.createAndAppendChanges(DiffFactory.java:96)
    at org.javers.core.diff.DiffFactory.create(DiffFactory.java:61)
    at org.javers.core.diff.DiffFactory.compare(DiffFactory.java:54)
    at org.javers.core.Javers.compare(Javers.java:103)
```

However if I switch to BEAN mapping, it uses the Jackson annotations.  I switch the mapping definition to:

``` java
        Javers javers = JaversBuilder.javers()
                .withMappingStyle(MappingStyle.BEAN)
                .registerEntity(TopLevelEntity.class, "id")
                .build();
```

And now I get this output:

```
diff: {
  "changes": [
    {
      "changeType": "ValueChange",
      "globalId": {
        "entity": "com.imsweb.seerapi.lab.staging.JaVersTest$TopLevelEntity",
        "cdoId": {
          "_time": 1417191004,
          "_machine": -80961410,
          "_inc": 1695747708,
          "_new": true
        }
      },
      "property": "description",
      "left": null,
      "right": "A new description"
    }
  ]
}
```

This looks better.  Few questions:

Why does it deal with ObjectId when BEAN mapping but not FIELD mapping?

ObjectId is usually presented by its toString version.  For example, the value looks something like this:

```
54789e5cfb2ca07e65130e7c
```

ObjectId has a createFromLegacyFormat which I think should be able to construct it from the values that are saved in the diff, but it would be a much better representation to use the toString output as the key.  Is there any way to tell Javers that?

Lastly, is there a way to define multiple fields as a identifier?  For example, what if I didn't want to use ObjectId at all in the diffs.  Instead, the key would be made up of algorithm, version, name.  It doesn't seem like that is currently possible, but would be nice in certain situations.

**Comment by umk8yw** [comment]
Is the problem with defining multiple fields as a identifier solved? 
If not, I would be glad to be a contributor because I need this solution.

**Comment by bartoszwalacik** [comment]
yeah, it was solved 3 years ago :)

**Comment by umk8yw** [comment]
I was talking about your first answer:
"Multiple fields as a identifier (aka composite key) is another issue. In fact it's a feature, which could be added to our backlog. As a workaround, you could encapsulate these 3 fields in a new class (ValueObject), i know it could be an invading change for your code ...
Possibly we could implement this feature faster, working together with you as a contributor?" 

I see that this https://javers.org/documentation/domain-configuration/#entity-id is the solution where you encapsulate the fields which are the unique key in a new class. 
I am interested in defining multiple fields as an identifier, for this I didn't find anything. In some cases the business model doesn't allow changes like the one suggested as an workaround in your answer.

**Comment by bartoszwalacik** [comment]
ok, i see, defining multiple fields as an identifier, so using `@Id` multiple times in the same class. This is not supported but looks like not very hard to add, we can do it together if you are eager to contribute but please create a new issue for this (could be titled Composite Id).
