### ISSUE TITLE
EntityDefinition doesn't pick up inherited fields/methods

### ISSUE THREAD

**Issue by jamesdbaker** [javers/javers#640]
I have some interfaces defined as follows:

    public interface WithId {
      String getId();
    }

    public interface MyObject extends WithId {
      //getId() is inherited
      //Some more methods, properties, etc
    }

When I try to register the object (with the following), it fails to detect the `id` property as expected:

    Javers javers = JaversBuilder.javers()
        .withMappingStyle(MappingStyle.BEAN)
        .registerEntity(new EntityDefinition(MyObject.class, "id"))
        .build();

The error I get is: `PROPERTY_NOT_FOUND: property 'id' not found in class 'MyObject'`

If the `getId()` method is directly on `MyObject`, then the code above works as expected. This is using `javers-core` version 3.7.5.

**Comment by bartoszwalacik** [comment]
And what about the concrete class?

**Comment by jamesdbaker** [comment]
A concrete implementation doesn't throw an error, but in my use case I don't necessarily know what concrete implementation I'm going to be passed (just that it will implement the interface MyObject).

**Comment by bartoszwalacik** [comment]
fix released in 3.8.2
