### ISSUE TITLE
JsonConverter not ignoring IgnoreType-s registered via JaversBuilder

### ISSUE THREAD

**Issue by stefanicai** [javers/javers#649]
When JsonConverter writes an object, it should not write properties of types that were registered as ignored via javersBuilder.registerIgnoredClass. It should also ignore properties that were marked as ignored via ClientsClassDefinition-s.

@bartoszwalacik was this by design or is it a bug?

A test would look like this- I have the whole test, can upload it in a branch if this is indeed a bug.

    class JsonConverterIgnoredClassesTest extends Specification {
        def "should not print ignored ClientClassDefinitions"() {
            given:
            def javers = JaversBuilder.javers().registerIgnoredClass(DummyAddress.class).build()
            def jsonConverter = javers.getJsonConverter()

            when:
            def classWithDummyAddressProp =  new ClassWithOneNotIgnoredProperty(name: "Johnny", address: address)
            def jsonString = jsonConverter.toJson(classWithDummyAddressProp)

            then:
            !jsonString.contains("Melbourne")

            where:
            address << [new DummyAddress(city: "Melbourne", street: "20 collins st")]
        }
    }

**Comment by bartoszwalacik** [comment]
JsonConverter obtained by `javers.getJsonConverter()` is a generic-purpose converter and it's not aware of Javers domain model mapping. I don't think it should be.
