### ISSUE TITLE
Mxing create and update

### ISSUE THREAD

**Issue by echarp** [javers/javers#652]
When saving an _existing_ entity, but with a _new_ related entity which is saved during cascading, it seems javers is handling the related new entity as an update.

It triggers an "ENTITY_INSTANCE_WITH_NULL_ID".

Do you know if I could change anything so that javers would know this entity is new, yet saved along an updated entity during cascading?

Solutions to circumvent this issue:
* give some unrelated id to the new entity, like -1 (ugly and breaks UI)
* pre-save the related entity before updating the top one (cascading is no longer really useful)

**Comment by bartoszwalacik** [comment]
There is no cascading in JaVers , are you talking about hibernate cascades?

**Comment by bartoszwalacik** [comment]
If so, use our hibernate unproxy hook, it's configured automatically in javers' spring boot starter

**Comment by echarp** [comment]
I'm using spring boot and spring boot starter.

Yes, thinking about cascading an update to an existing entity, which has a related OneToMany new entity.

It seems this new entity is seen by javers as an existing one, thus generating the dreaded "ENTITY_INSTANCE_WITH_NULL_ID" exception :)

**Comment by echarp** [comment]
(hibernate cascading)

**Comment by bartoszwalacik** [comment]
try to push s failing test case for this issue

**Comment by bartoszwalacik** [comment]
a failing test

**Comment by echarp** [comment]
Totally related to #234 :(
