### ISSUE TITLE
Missing shadows after upgrading from 3.7.0 to 3.7.5 (and 3.8.5)

### ISSUE THREAD

**Issue by rreitmann** [javers/javers#658]
We are using Javers to historize our domain objects and it is doing a great job! However, after upgrading from 3.7.0 to 3.7.5 and above the following junit tests in our spring boot project fail (the branch is configured to use javers 3.8.5 at the moment):
[Missing Study Shadows](https://github.com/dzhw/metadatamanagement/blob/rreitmann/issue1501/src/test/java/eu/dzhw/fdz/metadatamanagement/studymanagement/rest/StudyVersionsResourceTest.java#L91)
[Missing Survey Shadows](https://github.com/dzhw/metadatamanagement/blob/rreitmann/issue1501/src/test/java/eu/dzhw/fdz/metadatamanagement/surveymanagement/rest/SurveyVersionsResourceTest.java#L89)

Both tests use the following piece of code to load the shadows with `limit=5` and `skip=0` (from [GenericDomainObjectVersionsService.java](https://github.com/dzhw/metadatamanagement/blob/rreitmann/issue1501/src/main/java/eu/dzhw/fdz/metadatamanagement/common/service/GenericDomainObjectVersionsService.java#L75))
```java
public List<T> findPreviousVersions(String id, int limit, int skip) {
    T domainObject = repository.findOne(id);

    if (domainObject == null) {
      return null;
    }

    QueryBuilder jqlQuery = QueryBuilder.byInstance(domainObject)
        .withScopeDeepPlus(Integer.MAX_VALUE).limit(limit).skip(skip);

    List<Shadow<T>> previousVersions = javers.findShadows(jqlQuery.build());

    return previousVersions.stream().map(shadow -> {
      T domainObjectVersion = shadow.get();
      if (domainObjectVersion.getId() == null) {
        // deleted shadow
        domainObjectVersion.setLastModifiedBy(shadow.getCommitMetadata().getAuthor());
        domainObjectVersion.setLastModifiedDate(shadow.getCommitMetadata().getCommitDate());
      }
      return domainObjectVersion;
    }).collect(Collectors.toList());
  }
```
Both tests expect to get 3 shadows (1 initial commit + 2 updates) but do get only 2 shadows.

Please let me know if this is an intended change introduced with 3.7.5 or if this is an unintended side effect from the performance improvements introduced with 3.7.5

**Comment by bartoszwalacik** [comment]
Yes, there were significant changes in 3.7.5 in Shadow query runner (see https://javers.org/release-notes).
Remember that `limit` param limits the number of Snapshots and not the number of Shadows.
One Shadow can be reconstructed from many Snapshots (depending on your object graph structure).

What I can recommend, when you are testing Shadow queries, set the Snapshots limit with safe margin, for ex 100.

**Comment by bartoszwalacik** [comment]
see Performance & Profiling section in this javadoc https://javers.org/javadoc_3.x/org/javers/core/Javers.html#findShadows-org.javers.repository.jql.JqlQuery-

Please reopen this issue if you think you found a bug

**Comment by rreitmann** [comment]
I think I found a way for achieving what I need. I do now page through the snapshots of the root of the object graph and collect the commit ids. Afterwards I query for all shadows which can be reconstructed for the collected commit ids. I am assuming that there will always be a snapshot for the root even if a property further down in the graph is changed. 

```java
 public List<T> findPreviousVersions(String id, int limit, int skip) {
    QueryBuilder snapshotQuery = QueryBuilder.byInstanceId(id, domainObjectClass)
        .limit(limit).skip(skip);

    List<CdoSnapshot> snapshots = javers.findSnapshots(snapshotQuery.build());
    if (snapshots.isEmpty()) {
      return new ArrayList<>();
    }
    
    List<BigDecimal> commitIds = snapshots.stream().map(
        snapshot -> snapshot.getCommitId().valueAsNumber())
        .collect(Collectors.toList());
    
    List<Shadow<T>> previousVersions = javers.findShadows(
        QueryBuilder.byInstanceId(id, domainObjectClass)
        .withCommitIds(commitIds).build());

    return previousVersions.stream().map(shadow -> {
      T domainObjectVersion = shadow.get();
      if (domainObjectVersion.getId() == null) {
        // deleted shadow
        domainObjectVersion.setLastModifiedBy(shadow.getCommitMetadata().getAuthor());
        domainObjectVersion.setLastModifiedDate(shadow.getCommitMetadata().getCommitDate());
      }
      return domainObjectVersion;
    }).collect(Collectors.toList());
  }
```
Is that correct?

**Comment by rreitmann** [comment]
@bartoszwalacik Can you please check if my assumption [above](https://github.com/javers/javers/issues/658#issuecomment-380098969) is correct.

**Comment by bartoszwalacik** [comment]
@rreitmann seems correct but could be slow. I would be better to have correct & fast paging for Shadows in JaVers itself. Let me check it. I'll be back to you.

**Comment by bartoszwalacik** [comment]
Ok, so seems like we should fix `limit()` and `skip()` for Shadow queries. The failing test is pushed.

**Comment by bartoszwalacik** [comment]
fixed in 3.10.0

Use the new Stream API for Shadow queries — `javers.findShadowsAndStream()` with `Stream.skip()` and `Stream.limit()`. This is the only correct way for paging Shadows

**Comment by bartoszwalacik** [comment]
Thanks @rreitmann, yes in Java Streams ordering is important.

**Comment by rreitmann** [comment]
Ok, I did not know that. Thx, for letting me know.

>
