### ISSUE TITLE
Add option for AS_SET compare to ignore Diffs in sub-collections

### ISSUE THREAD

**Issue by headphonejack** [javers/javers#663]
When performing an AS_SET comparison on a _list of collections_, it would be good to have an option to stop comparing children once the parent has no diffs (according to the AS_SET ListCompareAlgorithm).

For example, in psuedo-code:
```
[
  [a,b,c],
  [d,e,f],
  [g,h,i]
]
```
vs
```
[
  [g,h,i],
  [a,b,c],
  [d,e,f]
]
```
produces no diffs at the parent level because AS_SET does not care about ordering, but will then compare contents of the child lists and produce Diffs.

Please let me know if I've missed something in the API/docs around this

Related to:
#605 
#606

**Comment by bartoszwalacik** [comment]
JaVers has simple logic for comparing Collections. Items are treated as values. Comparing is simply based on equals(). For example, Sets are compared using standard Java Set semantic:

```
    public static <E> Set<E> difference(Set<E> first, Set<E> second) {
        if (first == null) {
            return EMPTY_SET;
        }

        if (second == null) {
            return first;
        }

        Set<E> difference = new HashSet<>(first);
        difference.removeAll(second);
        return difference;
    }
```

So, AS_SET is not used for nested Lists. Maybe it should but it looks like a big change in javers-core.

**Comment by headphonejack** [comment]
Thanks - I there should be the option to do this. I'll look into what it would take - any pointers on where to start that could speed up my search?

**Comment by bartoszwalacik** [comment]
I would start from modeling the result. Take a look at ListChange and SetChange. The collections change model should be extended.

**Comment by bartoszwalacik** [comment]
Closing because lack of activity, please reopen if you'd like to contribute
