### ISSUE TITLE
Persistng commitDate with milliseconds precision on MySql

### ISSUE THREAD

**Issue by bartoszwalacik** [javers/javers#664]
related PR to poly - https://github.com/polyjdbc/polyjdbc/pull/38
reasons, see https://github.com/javers/javers/issues/657

**Comment by bartoszwalacik** [comment]
@gbondarchuk9 we need to wait a while for the poly release

**Comment by gbondarchuk9** [comment]
@bartoszwalacik I cannot find the test you're talking about, could you please refer with direct link to code?

by the way, I don't see any lines of code related to altering table with timestamp(3)

**Comment by bartoszwalacik** [comment]
@gbondarchuk9 links are here, look up, just above my previous comment

**Comment by bartoszwalacik** [comment]
fix released in 3.9.3
