### ISSUE TITLE
Java9 modules, fix overlapping package names

### ISSUE THREAD

**Issue by pethers** [javers/javers#666]
Overlapping package names in different jar files, cause issues when using module-info.java in java9.

Workaround https://github.com/Hack23/cia/blob/master/service.data.impl/javers-all/pom.xml to bundle all alls jar into 1, but not nice.

Modular jar:s with Automatic-Module-Name set would be prefered.

**Comment by bartoszwalacik** [comment]
Hi, I have tested javers on java10 but without modulepath. Never tested with modules. Would you like to contribute a PR with modules support to javers? We dont want the single jar. Im not sure if automatic module names are the best solution. maybe we can create regular module names and hide most of the public classes inside modules?

**Comment by pethers** [comment]
Main problem is that https://github.com/javers/javers/tree/master/javers-spring-jpa/src/main/java/org/javers/spring/auditable/aspect/springdata and https://github.com/javers/javers/tree/master/javers-spring/src/main/java/org/javers/spring/auditable/aspect/springdata is using the same package name. 

Renaming javers-spring-jpa/src/main/java/org/javers/spring/auditable/aspect/springdata to javers-spring-jpa/src/main/java/org/javers/spring/auditable/aspect/springdatajpa, will solve the package name conflict and should be a minimal change.  Happy to create a pull request for this if wanted ?

Example with automatic module name for javers-spring-data, without any change to jar automatic module name is based on the file name. So by default this would be javers.spring.data.

By adding manifest entries in jar plugin, you can set it to anything you want.
<manifestEntries>
	<Automatic-Module-Name>org.javers.spring.data</Automatic-Module-Name>
 </manifestEntries>

This do not require any changes to jdk compile time version.

Another solution, is to add module-info.java to all modules, but requires multiple jdk toolchain if support for JDK7 -> JDK9 is required. So probably overkill.

**Comment by bartoszwalacik** [comment]
If the packege renaming will do the job, let's do it. Seems like the this class https://github.com/javers/javers/tree/master/javers-spring-jpa/src/main/java/org/javers/spring/auditable/aspect/springdata is not used by users so renaming is safe. Please contribute a PR. Thanks.

**Comment by pethers** [comment]
Created https://github.com/javers/javers/pull/668 , but maybe better option to move JaversSpringDataJpaAuditableRepositoryAspect to javers-spring module. Would not break compatibility and not need package -> protected modifier changes.

**Comment by bartoszwalacik** [comment]
released in 3.7.4
