### ISSUE TITLE
Showing List Changes even when not changed version 3.9.4

### ISSUE THREAD

**Issue by jaynarathod** [javers/javers#670]
Hi am comparing two objects which have a structure like below:

Class MyClass{
String s1;
Services services;
}
Class Services{
ServiceS1 serviceS1;
ServiceS2 services2;
}

Class ServiceS1{
String id;
List<ServiceS1Devices> devicesS1List;
}

Class ServiceS1Devices{
String id;
String name;
Date date;
}

I create objects like this

ServiceS1Devices sd1 = new ServiceS1Devices("1", "d1", 1-2);
ServiceS1Devices sd2 = new ServiceS1Devices("2", "d2", 1-2);
List<ServiceS1Devices> devicesS1List = new ArrayList<>();
devicesS1List.add(sd1);
devicesS1List.add(sd1);
ServiceS1 serviceS1 = new ServiceS1();
serviceS1.setId("ss1");
serviceS1.setDevicesS1List(devicesS1List);
Services services = new Services();
services.setServiceS1(serviceS1);
.... services.setServiceS2(serviceS2);
MyClass obj1 = new MyClass();
obj1.setS1("1");
obj1.setServices(services);

Create a exactly similar object with only one change like below:
MyClass obj2 = new MyClass();
obj2.setS1("2");

Everything else is same, the Services etc

Then I do a compare
Javers javers = JaversBuilder.javers()
                    .withListCompareAlgorithm(LEVENSHTEIN_DISTANCE)
                    .build();
            Diff diff = javers.compare(obj1, obj2);

It gives me following output:

changes - ListChange:3 ValueChange:1

Value Change 1 is expected, why is it showing as List changed too (not expected in this case)?

Thanks!

**Comment by bartoszwalacik** [comment]
please ask questions on Stackoverflow

**Comment by jaynarathod** [comment]
Just curious, why isnt it a bug when the actual results don't match expected results?

**Comment by bartoszwalacik** [comment]
@jaynarathod read the https://github.com/javers/javers/blob/master/CONTRIBUTING.md
That's what you are expected to do in the first place.

If you think you found a bug, please follow the instructions for bug reporting.
Pasting random code snippets in a comment doesn't help us.
