### ISSUE TITLE
'class org.bson.Document' is mapped to MapType, expected ManagedType

### ISSUE THREAD

**Issue by sumit9872** [javers/javers#671]
JaversException MANAGED_CLASS_MAPPING_ERROR: given javaClass 'class org.bson.Document' is mapped to MapType, expected ManagedType.

Don't know why this exception is coming. Javers comparison working for 1 MongoDB entity and not working for similar another entity and raising the exception. I am unable to find a solution over the web.
Having these fields in the entity.

      @Id
	protected ObjectId id;
@AuditableField(fieldLabel = "Category Name")
	private String name;

	private ObjectId modelId;

	@DBRef(lazy = true)
	private List<Attribute> attributes = new ArrayList<>();

	@DBRef(lazy = true)
	private List<Asset> assets = new ArrayList<>();

**Comment by bartoszwalacik** [comment]
@sumit9872 please read the https://github.com/javers/javers/blob/master/CONTRIBUTING.md

If you think you found a bug, please follow the instruction for bug reporting. If you have a question, ask on Stack.
