### ISSUE TITLE
Support current versions of Spring Data (2.x)

### ISSUE THREAD

**Issue by shollander** [javers/javers#677]
Current versions of Spring Data use `saveAll(Iterable)` instead of `save(Iterable)`. When used with `JaversSpringDataAuditableRepositoryAspect`, calls to `saveAll()` are ignored. I believe this is a simple fix that just requires the addition of another pointcut definition in `JaversSpringDataAuditableRepositoryAspect`. `delete(Iterable)` has also been renamed to `deleteAll(Iterable)`.

See [DATACMNS-944](https://jira.spring.io/browse/DATACMNS-944) and [727ab8384cac21e574526f325e19d6af92b8c8df](https://github.com/spring-projects/spring-data-commons/commit/727ab8384cac21e574526f325e19d6af92b8c8df).

**Comment by bartoszwalacik** [comment]
released in 3.9.7
