### ISSUE TITLE
JaVers bootstrap error - component not found - CommitIdGenerator

### ISSUE THREAD

**Issue by Hawk30100** [javers/javers#684]
Hi! We use JaVers (3.10.0) in an application (a webservice, deployed on a tomcat server) for comparing two collections. Unfortunately we have the problem that we get the following error message very sporadically during the execution of unit tests:

`14:16:16 org.javers.common.exception.JaversException: COMPONENT_NOT_FOUND: JaVers bootstrap error - component of type 'org.javers.core.CommitIdGenerator' not found in container  
14:16:16 	at org.javers.core.pico.ContainerArgumentResolver.resolve(ContainerArgumentResolver.java:32)
14:16:16 	at org.javers.common.reflection.ReflectionUtil.newInstance(ReflectionUtil.java:78)
14:16:16 	at org.javers.core.pico.InstantiatingModule$ConstructorInjector.getComponentInstance(InstantiatingModule.java:48)
14:16:16 	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
14:16:16 	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
14:16:16 	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
14:16:16 	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
14:16:16 	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:678)
14:16:16 	at org.javers.core.AbstractContainerBuilder.getContainerComponent(AbstractContainerBuilder.java:22)
14:16:16 	at org.javers.core.JaversBuilder.bootRepository(JaversBuilder.java:760)
14:16:16 	at org.javers.core.JaversBuilder.assembleJaversInstance(JaversBuilder.java:158)
14:16:16 	at org.javers.core.JaversBuilder.build(JaversBuilder.java:121)
14:16:16 	at com.myApplication.<init>(MyApp.java:38)`

Unfortunately, I cannot reproduce this problem because it occurs only sporadically. It seems to occur differently often on different computer systems. This error nerver happens on production runtime. It just happens when executing the unit tests.

Especially our Jenkins, which builds the application at least 15 times a day, fails about 5-8 times a day due to the above mentioned error. It seems like it doesnt matter which version of JaVers we use (we have tried 3.9.0 up to 3.10.0)

Since it's only sporadic and unfortunately it's code I'm not allowed to share, I'm sorry that I can't give you any code to reproduce my issue. We do not use the repository feature. We do only use the Javers.compareCollections method.

But maybe this problem is already known and you can give me tips how I can analyze and fix the problem.

**Comment by bartoszwalacik** [comment]
guys, i'm on holiday in Portugal, will back to you in the next week. I think that someone have already created the PR with the fix for this issue

**Comment by bartoszwalacik** [comment]
@atomfrede, right looks like duplicate to https://github.com/javers/javers/issues/682
so I'm closing this issue. We will fix the bug asap.

**Comment by bartoszwalacik** [comment]
@Hawk30100 please folow https://github.com/javers/javers/issues/682

**Comment by bartoszwalacik** [comment]
fix is on its way to the Central
release javers-3.10.1

**Comment by bartoszwalacik** [comment]
fix released in javers-3.10.1
