### ISSUE TITLE
Failed to call javers.findSnapshots with QueryBuilder.byInstanceId(entityId, entityTypeToFetch)

### ISSUE THREAD

**Issue by minhchau110883** [javers/javers#685]
Javers version: 3.10.0

I'm trying to get the previouse snapshot of an entity based on the current commit version and entityId
`public ResponseEntity<EntityAuditEvent> getPrevVersion(@RequestParam(value = "qualifiedName") String qualifiedName,
                                                           @RequestParam(value = "entityId") String entityId,
                                                           @RequestParam(value = "commitVersion") Long commitVersion)
        throws URISyntaxException, ClassNotFoundException {

        Class entityTypeToFetch = Class.forName("com.chaung.entityaudit.domain." + qualifiedName);

        QueryBuilder jqlQuery = QueryBuilder.byInstanceId(entityId, entityTypeToFetch)
                                           .limit(1)
                                           .withVersion(commitVersion - 1)
                                           .withNewObjectChanges(true);

        EntityAuditEvent prev = EntityAuditEvent.fromJaversSnapshot(javers.findSnapshots(jqlQuery.build()).get(0));

        return new ResponseEntity<>(prev, HttpStatus.OK);

    }`
javers.findSnapshots cannot return value, the reason is when build the query to get the global Id, the value of entity id is incorrect. 
Expected result is 1, but actual is "1" (adding " before and after 1).
Please see screenshot below. Thanks

![image](https://user-images.githubusercontent.com/8534498/42260667-7ac82c42-7f8f-11e8-96cd-f00e4f579c19.png)

**Comment by minhchau110883** [comment]
I know the root cause, it depends on the type of localId, for my case, when 'insert', the type of localId is Long, but when 'find', the type of localId is String. 
So, I closed this issue.

**Comment by bartoszwalacik** [comment]
👍
