### ISSUE TITLE
Missing property in *.yml to set CommitIdGenerator

### ISSUE THREAD

**Issue by dkrogulec** [javers/javers#688]
Following to [this](https://stackoverflow.com/questions/51241622/javers-3-10-1-set-random-commit-id-generator-in-yml-conf-file) stackoverflow topic seems it is missing property in *.yml to set CommitIdGenerator when using SpringBoot. Can you add this feature and describe in docs?

Thanks!

**Comment by bartoszwalacik** [comment]
PR https://github.com/javers/javers/pull/731 merged

**Comment by bartoszwalacik** [comment]
released in 3.12.3
