### ISSUE TITLE
javers+mybatis+springboot

### ISSUE THREAD

**Issue by xdp6688** [javers/javers#699]
有没有javers+mybatis+springboot 的demo？
is there a demo: javers+mybatis+springboot?

**Comment by xdp6688** [comment]
javers 是否支持mybatis？

**Comment by bartoszwalacik** [comment]
wtf?

**Comment by xdp6688** [comment]
is there a javers demo can explain how to use in springboot and mybatis project ?

**Comment by bartoszwalacik** [comment]
never heard about mybatis, ask questions at stackoverflow, not here
