### ISSUE TITLE
Javers storing mysql table data in mongodb

### ISSUE THREAD

**Issue by deepeshuniyal** [javers/javers#702]
We are using mysql and mongodb in our spring boot project, we have added both the dependency.

```
compile 'org.javers:javers-spring-boot-starter-mongo:3.8.4'
compile 'org.javers:javers-spring-boot-starter-sql:3.8.0'
```
and added **_@JaversSpringDataAuditable_** annotation in all the repository (mysql+mongodb).

now all Audit data started saving in mongodb.

What we want is mysqldb data would be saved in mysql and mongodb data save in mongo.

**Comment by bartoszwalacik** [comment]
It wont work out of the box, you can't simply merge two our Spring Boot starters. Try to use JaVers directly (without Spring Boot starters), set up two JaVers instances, and choose to which one you want to commit

**Comment by indiana-jonas** [comment]
Hi

I had the same issue. And I have tried to configure 2 instances of javers. One for MySQL and one for Mongo DB. And that works fine. Though now ALL the Audit data is saved to both Mongo and MySQL. Would it be possible to get some pointers how I can configure which javers bean is used with which Spring Data repository?

Cheers

**Comment by bartoszwalacik** [comment]
@indiana-jonas, simply, don't use our Spring Boot starters and provide your own Spring configuration. It's realtively simple. You can copy the configuration from the starter - see https://github.com/javers/javers/blob/master/javers-spring-boot-starter-sql/src/main/java/org/javers/spring/boot/sql/JaversSqlAutoConfiguration.java and customize it.
