### ISSUE TITLE
tracking a top-level object deletion

### ISSUE THREAD

**Issue by bartoszwalacik** [javers/javers#71]
How would I go about tracking a top-level object deletion? So if I remove an entity completely from my database, how do I "commit" that change to Javers?

we need new method:
```
javers.commitDelete(String author, Object deleted);
```

**Comment by bartoszwalacik** [comment]
solved, waiting to CR. To be released in 1.0.3

**Comment by ctmay4** [comment]
Just tested on the snapshot and it worked well with my tests.  Thanks.

**Comment by bartoszwalacik** [comment]
1.0.3 released to Central
