### ISSUE TITLE
Distribute Javers by Bintray

### ISSUE THREAD

**Issue by pawelszymczyk** [javers/javers#72]
https://bintray.com/

**Comment by bartoszwalacik** [comment]
Paweł, jeśli nic z tym nie robimy, to może zamknij task, bo się dużo tych tasków robi ...

**Comment by pawelszymczyk** [comment]
Ale to jest do zrobienia, lepiej niech zostanie.

**Comment by szpak** [comment]
Btw, chcecie się przenieść z paczkami do Bintray/jCenter całkowicie, czy tylko mieć je również tam (oprócz Maven Central) dostępne?

**Comment by bartoszwalacik** [comment]
Maven Central to must have. Bintray da nam wieksza automatyzacje bo teraz wdrazamy klikajac w nexusa Sonatype. Czyli artefakty bylyby tu I tu

**Comment by bartoszwalacik** [comment]
Btw jesI masz chec na kontrybucje do javersa to cos znajdziemy, pozdr

**Comment by szpak** [comment]
Zastanawiało mnie, czy tylko chcecie, aby artefakty z Centrala były dostępne również w jCenter (co swoją drogą dzieje się automatycznie), czy coś więcej. W kwestii wdrażania to niestety muszę  się zgodzić - historycznie lubię Sonatype OSS i Maven Central, ale w przypadku Nexusa i Gradle nie znam rozwiązania, które by to zapewniło (np. gradle-nexus-plugin wymaga dodania [tego](https://github.com/bmuschko/gradle-nexus-plugin/issues/40)), a dla Bintray/jCenter jest dużo prościej. W ramach prac nad [micro-infra-spring](https://github.com/4finance/micro-infra-spring) ostatnio robiłem [automatyzację wdrażania](https://github.com/4finance/micro-common-release/wiki) (robimy commit z komendą do wydawania i Travis buduje, odpala testy akceptacyjne, wrzuca do Bintray - bez dalszej ludzkiej interwencji).

Jeżeli planowaliście zrobić coś podobnego u siebie to możecie spojrzeć na [micro-common-release](https://github.com/4finance/micro-common-release). U nas działa całkiem sprawnie. W przypadku, jakbyście byli zainteresowani jego użyciem to pewnie mógłbym pomóc we wdrożeniu mechanizmu.

**Comment by bartoszwalacik** [comment]
zależy nam na Maven Central bo to jest standard w światku Java, co do uploadu do jCentral to nie mam zdania, pewnie nie zaszkodzi ale krytyczny jest Maven Central. Rozmawiałem ostatnio ze Szczepanem, że w Mockito mają ładnie zautomatyzowany Gradlem cały flow wdrożeniowy przez Bintray. Nie znam szczegółów.

Anyway jeśli masz sposób jak zrobić release do Maven Central przez 1 polecenie gradle/Travis to my to chętnie zaaplikujemy.

**Comment by szpak** [comment]
Bezpośrednie wrzucanie do Centrala nie działa przez [brak](https://github.com/bmuschko/gradle-nexus-plugin/issues/40) wsparcia w gradle-nexus-plugin. Mi też tego brakuje, ale tam trzeba mocno operować na REST i JSON, a Benjamin nie chce, aby implementacja używała HTTPBuildera, ani innych zalezności, więc raczej nie będę tego implementował w najbliższym czasie.

Bintray plugin od wersji 1.0 [wspiera](https://github.com/bintray/gradle-bintray-plugin/issues/36) synchronizację z Centralem - czyli paczki są wrzucane do Bintray i Bintray je wrzuca do Centrala. Nie testowałem osobiście, ale w Mockito wygląda, że działa i Szczepan gdzieś pisał, że jest to automatyczne.

Jeżeli by Wam wystarczyło, to co opisałem (automatycznie z commita release do jCenter z micro-common-release) + automatyczna synchronizacja z Maven Central to pewnie mógłbym pomóc.

Btw, [slajdy](https://docs.google.com/presentation/d/14mtpaOB7BGNVKOaxe1qTMEGTlZ_SvNnRh6ZIynkurtk/edit?usp=sharing) z mojej prezentacji o procesie w micro-common-release, jakbyście chcieli dowiedzieć się więcej.

**Comment by bartoszwalacik** [comment]
dzięki, pójdziemy w tą stronę, w razie czego będziemy się zgłaszać po wsparcie

**Comment by pawelszymczyk** [comment]
review pls

**Comment by bartoszwalacik** [comment]
jest na to PR?

**Comment by pawelszymczyk** [comment]
był ale zamknąłem, wprowadziłem kilka poprawek i otworzyłem jeszcze raz:
https://github.com/javers/javers/pull/122

**Comment by bartoszwalacik** [comment]
może nie potrzebujemy Bintray tylko https://github.com/Codearte/gradle-nexus-staging-plugin/ ?

**Comment by szpak** [comment]
Jednak trafił mi się wolny weekend i zrobiłem ten plugin. W rezultacie można bez klikania robić release w Nexusie do Centrala. Minusem jest, iż [micro-common-release](https://github.com/4finance/micro-common-release) obecnie wspiera tylko Bintray, więc logikę sami musielibyście dopisać, ale z drugiej strony wtedy więcej "zabawy" byście mieli :).

**Comment by szpak** [comment]
Btw, jakbyście chcieli zostać ze "starym" pluginem `maven` do wypychania paczek to możecie spojrzeć też na [gradle-nexus-plugin](https://github.com/bmuschko/gradle-nexus-plugin/), który trochę upraszcza definiowanie repozytoriów.

**Comment by bartoszwalacik** [comment]
@szpak a patrzyłeś na nowy https://github.com/Codearte/gradle-nexus-staging-plugin/ by Codearte?

**Comment by szpak** [comment]
> @szpak a patrzy�e� na nowy https://github.com/Codearte/gradle-nexus-staging-plugin/ by Codearte?

Patrzy�em. A czy Ty patrzyles, kto napisa� ten plugin by Codearte? :-)

**Comment by bartoszwalacik** [comment]
wow, teraz widzę, no nie skojarzyłem :) wygląda na to że to jest plugin, którego potrzebujemy :)

**Comment by bartoszwalacik** [comment]
wepnę go przed następnym release do Sonatype

**Comment by bgalek** [comment]
1. add @bartoszwalacik private key used for nexus publication to travis Environment Variables
2. use private key string in travis.yml/build.gradle 
3. use szpak's plugin to deploy artifact to sonatype repository
4. add gradle task to upload artifact snapshot to sonatype (will be triggered manually)
5. create new branch - production, enable only merges on it and connect travis build

**Comment by bartoszwalacik** [comment]
po długim boju, wdrażamy się przez Bintray! https://bintray.com/javers/maven/javers/view

**Comment by szpak** [comment]
Btw, via Travis? ręcznie? czy jakoś inaczej?

**Comment by bartoszwalacik** [comment]
na razie nie na Travisie, ale jest dobra automatyzacja, wystarczy wykonać lolaknie ./gradlew bintray
