### ISSUE TITLE
Deserialize from json

### ISSUE THREAD

**Issue by renemeuselwitz** [javers/javers#724]
Hi, 

when serailizing and deserializing Diffs of objects, I'm having some trouble:

Let's assume the following:

`
 
       Item val1 = new Item();
        Item val2 = new Item();
        val1.setId(1234);
        val2.setId(5678);

        Javers javers = JaversBuilder.javers().build();
        Diff diff = javers.compare(val1, val2);

        String json = javers.getJsonConverter().toJson(diff); // until here it works

        Diff javersDiff = javers.getJsonConverter().fromJson(json , Diff.class); // here it crashes

`

I'm getting a "java.lang.IllegalArgumentException: argument should not be null" Exception. Debugging further into it gives me a 
"Method threw 'java.lang.IllegalArgumentException' exception. Cannot evaluate org.javers.core.diff.Diff.toString()"

Any way to actually nicely deserialize my values again as Diff?

Thanks,

**Comment by renemeuselwitz** [comment]
PS: I am using version 3.11.5.

I also rolled back, and the code works like a charm for version.

Seems like it stopped working somewhen in versin 3.9. Still works for my with old versions until 3.8.5

**Comment by bartoszwalacik** [comment]
@rene try to submit a PR with a fix, we will merge

**Comment by bartoszwalacik** [comment]
fix released in 3.12.1
