### ISSUE TITLE
Idea: Keeping snapshots in git

### ISSUE THREAD

**Issue by floresek** [javers/javers#728]
Hi,

I have recently talked with my friend about javers and how it works (and store data in DB) and he suggested interesting idea - to keep snapshots in git (and later resolve them from it by commit number).

Keeping snapshots in DB (a json) is space consuming.

What do you think about that?

Cheers
Mariusz

**Comment by bartoszwalacik** [comment]
Git is one of the slowest database around because it doesn't have indexes.
I'm affraid that javers queries implemented on Git would be terribly slow.

For example, how would you implement

`Optional<CdoSnapshot> getLatest(GlobalId globalId)` ?

**Comment by floresek** [comment]
Implementing is simple: git checkout $revision and finding interesting file.
If not VCS (because to slow) maybe some research on incremental-delta storage should be done?

**Comment by bartoszwalacik** [comment]
and how would you find the latest revision for this object?
Git is to slow to work as application's database.
We are thinking that it would be nice to implement JaversRepository for Cassandra or DynamoDB, but no one is working on it.
