### ISSUE TITLE
Object Comparision showing removed elements in changes

### ISSUE THREAD

**Issue by sivamtech12** [javers/javers#745]

**Comment by sivamtech12** [comment]
i have two objects and trying to find difference between them . find below scenario for detail .

Object1 
<details>
<detail>
<name>siva</name>
<age>28</age>
</detail>

<detail>
<name>ram</name>
<age>30</age>
</detail>
</details>
<detail>
<name>chandru</name>
<age>30</age>
</detail>
</details>

Object 2
<details>
<detail>
<name>ram</name>
<age>30</age>
</detail>
</details>
<detail>
<name>chandru</name>
<age>30</age>
</detail>
</details>

in Object 2  i removed only first index and here javers showing value changes for ram and chandru since index got changed  means now first index have ram and second index have chandru and in  remove object  it is showing   third index chandru

**Comment by sivamtech12** [comment]
javers.compare(['a','b','c','d','e'],
               ['a','c','d','e'])
Step 1 : removed: 'b'

output : 
change objects showing like below since index changes ,

. 'b'>>'c' 
 'c'>>'d' 
 'd'>>'e' 

remove object showing like below 
 removed:'e'

**Comment by bartoszwalacik** [comment]
Sorry but this issue is a mess, please read https://github.com/javers/javers/blob/master/CONTRIBUTING.md in the first place. Is a bug report, question or maybe a feature request?
