### ISSUE TITLE
Method-level annotation should enable delete method to save terminal snapshots

### ISSUE THREAD

**Issue by guima** [javers/javers#751]
When using ordinary repositories, we would like to annotate delete methods and save *terminal* snapshots.

We annotated save and delete repository methods with `@JaversAuditable`, but only *initial* and *update* snapshots were persisted.

We want to enable `commitShallowDelete` to save *terminal* snapshots without Spring Data.

**Comment by bartoszwalacik** [comment]
The new ann should be named `@JaversAuditableDelete`, looks like this task is easy to implement, feel free to contribute a PR

**Comment by dovidkopel** [comment]
Has this been merged in yet?

**Comment by bartoszwalacik** [comment]
there is nothing to merge, someone has to code it first :)

**Comment by guima** [comment]
I already forked and committed It. What should i do now?

**Comment by bartoszwalacik** [comment]
Please create a pull request

**Comment by bartoszwalacik** [comment]
nice job @guima

I will release it in this weekend in 5.2.0

I did some changes (merging the new aspect with the old one, thanks to that we don't won't have to change the docs and users' config)

**Comment by bartoszwalacik** [comment]
released in 5.2.0

**Comment by AdrikaMukherjee** [comment]
can Javers only persist on save and delete methods? can it  save screenshot on  .update?

**Comment by ravivarmakola** [comment]
@bartoszwalacik The [documentation](https://javers.org/documentation/spring-integration/#auto-audit-aspect)  says:
```
@JaversAuditableDelete
TODO
```
Is it the documentation to be done ? is the change already in JaVers post 5.2.0 release?

**Comment by bartoszwalacik** [comment]
@ravivarmakola it's documented in the javadoc https://github.com/javers/javers/blob/master/javers-spring/src/main/java/org/javers/spring/annotation/JaversAuditableDelete.java
