### ISSUE TITLE
Asynchronous commit 

### ISSUE THREAD

**Issue by dmushkov** [javers/javers#757]
It's totally unclear how to use 
`CompletableFuture<Commit> javers.commitAsync(..., Executor);`

Please provide few words how it can be used for ms-sql server

**Comment by bartoszwalacik** [comment]
if you don't know how CompletableFuture works, simply use the classic commit

**Comment by dmushkov** [comment]
Is that even possible ?
It is not supported for sql 
 throw new JaversException(JaversExceptionCode.NOT_IMPLEMENTED,
                "javers.commitAsync() is not available for SQL");

**Comment by bartoszwalacik** [comment]
@dmushkov , did you read the javadoc of the method you are trying to call?


```
/**
     * Async version of {@link #commit(String, Object, Map)}
     * <br/><br/>
     *
     * <b>Important!</b> Works with MontoDB, not implemented for SQL repositories.
     *
     * @param executor ExecutorService to be used to process commit() asynchronously
     */
    CompletableFuture<Commit> commitAsync(String author, Object currentVersion, Map<String, String> commitProperties,
                                          Executor executor);
```

**Comment by dmushkov** [comment]
@bartoszwalacik Thanks! So it's not possible for SQL repositories.

**Comment by bartoszwalacik** [comment]
yep
