### ISSUE TITLE
How do I associate a user with changes for audit?

### ISSUE THREAD

**Issue by jeacott1** [javers/javers#759]
I think I'm missing something really basic here.
 In an audit scenario, I'd usually want to associate the user/entity that actioned the change with the record of that change. I cant find any documentation that says how I should achieve this with jaVers?
what am I missing here?

Thanks

**Comment by bartoszwalacik** [comment]
It's the first argument that you are passing to javers commit method :) 

```java
    /**
     * Persists a current state of a given domain object graph
     * in JaVers repository.
     * <br/><br/>
     *
     * JaVers applies commit() to given object and all objects navigable from it.
     * You can capture a state of an arbitrary complex object graph with a single commit() call.
     *
     * @see <a href="http://javers.org/documentation/repository-examples/">http://javers.org/documentation/repository-examples</a>
     * @param author current user
     * @param currentVersion standalone object or handle to an object graph
     */
    Commit commit(String author, Object currentVersion);
```

also, if you are using `javers-spring` there is automagical integration with Spring Security, see https://javers.org/documentation/spring-integration/#author-provider-bean

**Comment by jeacott1** [comment]
:) thanks! - I knew I was missing something! doh.
