### ISSUE TITLE
Wrong date on Javers with sql repository

### ISSUE THREAD

**Issue by NicoBondarenco** [javers/javers#760]
I'm using Javers with SqlRepository (H2 on unit tests).
In the database, the jv_commit.commit_date is '2018-01-07 12:47:37.334', from what I saw in the code, this datetime is in the timezone +00:00.
I'm in the timezone -02:00, but when I create a query to find shadows, the result returned is '2018-01-07 14:47:37.334', instead of '2018-01-07 10:47:37.334'... Is that correct?

I saw on org.javers.repository.sql.finders.SnapshotQuery$CdoSnapshotMapper, when it's created, that it calls a method "org.javers.core.json.CdoSnapshotSerialized.withCommitDate(resultSet.getTimestamp(COMMIT_COMMIT_DATE))" in this method, the deserialization is done using "org.javers.core.json.typeadapter.util.UtilTypeCoreAdapters.fromUtilDate(Date date)".
In my case, the method receives a java.sql.Date, than i'ts converted to "java.util.Date" (new Date(date.getTime())) and recursivelly called (there is a comment "//hack for old java.sql.Date").

When this method is called again, the LocalDateTime.ofInstant(date.toInstant(), UTC) is called, that's when the timezone is applied wrong, it adds 2 hours instead of subtract it.

Can someone help me please? I don't know if i'm doing something wrong or misconfigurated something...

**EDIT**: What I understood is, when the commit is saved it gets the LocalDateTime from my timezone, e.g.: '2018-01-07 12:47:37.334', (which wold be '2018-01-07 14:47:37.334' in UTC), but in the database is saved as my LocalDateTime, not in UTC, and when i get the select result, it gets the '2018-01-07 12:47:37.334' in my TimeZone and converts to UTC, then returns like my LocalDateTime, but in UTC.
So if i save on a timezone and selects on another, there will be a problem on commit dates.
E.g.: I save a commit with my timezone -02:00, in the database it will be '2018-12-20 12:00:00.000' (using my LocalDateTime) but when I select, the application is running on a timezone of -03:00, when the conversion is applied, it will consider 12:00:00 as the LocalDateTime, then it will convert to UTC 15:00:00, when it is actually 14:00:00.

**Comment by bartoszwalacik** [comment]
Well, since commitDate is stored as `LocalDateTime` if you are writing in one timezone and reading in another, the results won't be correct. Looks like we should change `LocalDateTime` into `ZonedDateTime` in `CommitMetadata`. You are encouraged to contribute.

**Comment by guima** [comment]
We could consider using ```Instant``` for persistence (storing as UTC), leaving the conversion for presentation.

**Comment by bartoszwalacik** [comment]
To be honest, I don't know what is `Instant`, any disadvantages of having `ZonedDateTime` as a commit date?

Btw, we can't just change the type of commit date, it would break compatibility. People have their snapshots persisted with commit date as `LocalDateTime`.

**Comment by bartoszwalacik** [comment]
I've just realized that that this task is duplicate to https://github.com/javers/javers/issues/743
