### ISSUE TITLE
CustomBigDecimalComparator NullPointerException

### ISSUE THREAD

**Issue by buderjoh** [javers/javers#769]
If you use org.javers.core.diff.custom.CustomBigDecimalComparator with a null value you get an NPE 

![image](https://user-images.githubusercontent.com/20115146/51106166-45f5c980-17eb-11e9-899b-85772add19c4.png)

There should be a null check for setScale and possibly for aRounded.equals(bRounded); aswell.

Also minor issue 

The comment in line 21 is missing the .class ->  BigDecimal.class

JaversBuilder.javers().registerCustomComparator(new CustomBigDecimalComparator(2), BigDecimal).build();

**Comment by bartoszwalacik** [comment]
You are right. CustomBigDecimalComparator is here just to serve as the example of CustomComparator, so it's not critical. Contribute a PR with the fix if you like.

**Comment by buderjoh** [comment]
Yeah it is not critical :) 
i have written my own Comparator 

PR -> 771

**Comment by bartoszwalacik** [comment]
merged, it will be released in the next release

**Comment by bartoszwalacik** [comment]
fix released in 5.2.0
