### ISSUE TITLE
Put more context information on SNAPSHOT_STATE_VIOLATION

### ISSUE THREAD

**Issue by lujop** [javers/javers#774]
At org.javers.core.metamodel.object.CdoSnapshotStateBuilder#withPropertyValue when `JaversException(JaversExceptionCode.SNAPSHOT_STATE_VIOLATION)` is throwed put at least propertyName in exception message to help with the problem

**Comment by bartoszwalacik** [comment]
Ok, we will accept a PR

**Comment by bartoszwalacik** [comment]
Please provide a failing test case. See how we write test cases https://github.com/javers/javers/tree/master/javers-core/src/test/groo

**Comment by bartoszwalacik** [comment]
fixed in 5.6.3
