### ISSUE TITLE
Access which property is changed and get change when using findChanges

### ISSUE THREAD

**Issue by donpironet** [javers/javers#780]
I'm using javers as auditing framework in spring boot. 
Now I want to create my own description string instead of using the english one.

So I query my changes like this:

`    List<Change> changes = javers.findChanges(QueryBuilder.byInstanceId(id, entityClass).withChildValueObjects().build());`

Now I want to iterate through the list of changes and get the changed property what the old value was and the new one. So I can just create my own description.

But all the properties are private the only thing I can access is the commitmetadata but there I don't have the changes.

Is there no way to do this?

**Comment by bartoszwalacik** [comment]
Change is abstract, look at concrete subclasses
