### ISSUE TITLE
JSON Path Integration

### ISSUE THREAD

**Issue by dovidkopel** [javers/javers#793]
It would be ideal if we could integrate [JsonPath](https://github.com/json-path/JsonPath) into the already awesome library.

While I haven't played around with it too much, there is a [pg-jsonpath](https://github.com/jvinet/pg-jsonpath) which easily provides JSON path queries to PostgreSQL.

```
SELECT id FROM events WHERE jsonpath(data, '$.participants[?(@.name=="Dolphins")].name')='Dolphins';

SELECT id FROM events WHERE 'Dolphins' = ANY (jsonpatharr(data, '$.participants[*].name'));
```
Granted you might need to limit this functionality to those that have a connector similar to this. I also found this library [hibernate-native-json](https://github.com/velo/hibernate-native-json). 

At the minimum it would be logical to at least support simple top level key/values for the snapshot state data.

**Comment by bartoszwalacik** [comment]
We already have JQL - simple object-oriented query language. We can extend it but adding another language seems strange to me. Btw JSON is just an impl detail, javers is object-oriented by design.

**Comment by dovidkopel** [comment]
My point is right now as far as I can see there doesn't seem to be an easy way to query against the state data. You can look at if there is a changed property of that key but not if a record ever had value "xxxx" for key "yyyy". JSON is the way that the day is currently being stored for the state. I was suggesting a mechanism that may enable you to easy query that state data.

**Comment by bartoszwalacik** [comment]
We have the open issue for that, see https://github.com/javers/javers/issues/556

**Comment by bartoszwalacik** [comment]
Would you like to contribute? Query by snapshot state (property & value) is easy to implement but it means full table/collection scan, it could be slow.

**Comment by YuanZhencai** [comment]
@bartoszwalacik Can I put the state properties of the query into the commit message? CommitPropertiesProvider ?

**Comment by bartoszwalacik** [comment]
sorry but this issue is closed
