### ISSUE TITLE
Javers and SQL Server

### ISSUE THREAD

**Issue by Pinellus** [javers/javers#796]
Hi,
with a **QueryBuilder.byInstanceId**, I get a SQL Exception on SQL Server:

```
SQL_EXCEPTION: An expression of non-boolean type specified in a context where a condition is expected, near 'ORDER'.
while executing sql:     SELECT state, type, version, changed_properties, managed_type, commit_pk, author, commit_date, commit_date_instant, commit_id, g.local_id, g.fragment, g.owner_id_fk, o.local_id owner_local_id, o.fragment owner_fragment, o.type_name owner_type_name FROM jv_snapshot INNER JOIN jv_commit ON commit_pk = commit_fk INNER JOIN jv_global_id g ON g.global_id_pk = global_id_fk LEFT OUTER JOIN jv_global_id o ON o.global_id_pk = g.owner_id_fk WHERE 1 = 1 and (  false) ORDER BY snapshot_pk DESC OFFSET ? ROWS FETCH NEXT ? ROWS ONLY
```

Can you help me?
Regards

**Comment by Pinellus** [comment]
In depth:

Changes changes = javers.findChanges(QueryBuilder.byInstanceId(MyPK, MyClass.class).build() );

Here the JDBC PreparedStatement return a "**WHERE 1 = 1 and (  false)**" that is not compatibile with SQL Server

**Comment by bartoszwalacik** [comment]
OK, l try to fix it, which is not easy because I don't have Oracle database at my fingertips.

**Comment by bartoszwalacik** [comment]
see https://github.com/javers/javers/issues/801#issuecomment-471553873

**Comment by bartoszwalacik** [comment]
fix is  released
5.2.6
https://search.maven.org/search?q=javers-core
check it out
