### ISSUE TITLE
How to use Jav verse for already existing object structure?

### ISSUE THREAD

**Issue by uvcourses** [javers/javers#804]
I have my own Data Modal. i want to compare 2 java object. How do i register my class and field as Entity using javersBuilder. there is no example program for user defined Data Modal.

I can see example only for newly creating Data Modal.

my application is too old. so, i cannot change my code. without changing my Data Modal How to use Javers.

How to explain my data Modal to Javers.

Note: please dont post same link https://javers.org/documentation/domain-configuration/

this is not at all telling how to create custom Modal and communicate to Javers

**Comment by bartoszwalacik** [comment]
questions about basics should be asked on stackoverflow
