### ISSUE TITLE
Slow performance for complex objects

### ISSUE THREAD

**Issue by eugene-savko** [javers/javers#813]
I have complex object for example:
**Audit structure**
Document
- List<Item> items
     - MainInfo data
          - Location location
          - Address location
     - ServiceInfo data
          - Location location
               - id
          - Address location
               - id
     - Additional data
          - id
- List<Comment> comments
     - String value
     - Type type
- List<Attachment> attachments
     - String value
     - Type type
- List<Setting> settings
     - String value
     - Type type
- Type type
other simple type properties

When my document contains many nested object:  item, comments and other object Javers need a lot of time to make init(update) commit and same situation when I am trying to find shadows.
I can't commit changed model directly, because value from nested model can affect value in root object and as result I all time commit full document object.
Sometimes, javers graph contains more then 1000 elements.

When I have switched from json format for each nested object to one big document json, situation has improved.

**Is single json storing for javers acceptable?**
Probably, I have chosen wrong way for improving audit performance.

Thanks in advance

**Comment by bartoszwalacik** [comment]
Hi, provide a test case with working example and push it to github. See how we write test cases https://github.com/javers/javers/tree/master/javers-core/src/test/groovy/org/javers/core/cases

**Comment by bartoszwalacik** [comment]
please reopen if you come up with a test case
