### ISSUE TITLE
Table or view does not exists

### ISSUE THREAD

**Issue by p595285902** [javers/javers#814]
I am getting the following errors when having `@JaversSpringDataAuditable` on my repository.

```
    2019-03-25 15:09:24.045  WARN 4784 --- [nio-9090-exec-2] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 942, SQLState: 42000
    2019-03-25 15:09:24.046 ERROR 4784 --- [nio-9090-exec-2] o.h.engine.jdbc.spi.SqlExceptionHelper   : ORA-00942: table or view does not exist
    
    2019-03-25 15:09:24.088  INFO 4784 --- [nio-9090-exec-2] o.j.s.jpa.JaversTransactionalDecorator   : evicting javersSqlRepository local cache due to transaction rollback
```

Repository:

```
    @RepositoryRestResource(collectionResourceRel = "product", path = "product")
    @JaversSpringDataAuditable
    public interface ProductRepository extends JpaRepository<ProductEntity, Long>...

```
Maven: Javers Version - 5.3.2, SpringBoot version - 2.0.3.RELEASE, Spring - 5.0.6.RELEASE

```
    <dependency>
        <groupId>org.javers</groupId>
        <artifactId>javers-spring-boot-starter-sql</artifactId>
        <version>${javers.version}</version>
    </dependency>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-data-jpa</artifactId>
    </dependency>

```
Javser properties:

`    javers.sqlSchema=OOA1S`

Oracle Version - 12c

Manual javers.commit works fine:

`    2019-03-25 15:09:23.630  INFO 4784 --- [nio-9090-exec-2] org.javers.core.Javers                   : Commit(id:3.0, snapshots:0, author:xxxxxxx, changes -), done in 445 millis (diff:445, persist:0)
`
Not sure what table/view is missing, tried get SQL logs with the following properties but no luck.

```
    logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
    logging.level.org.javers=debug
    logging.level.com.zaxxer=debug
    logging.level.org.hibernate.SQL=debug
    spring.jpa.properties.hibernate.show_sql=true
    spring.jpa.properties.hibernate.use_sql_comments=true
    spring.jpa.properties.hibernate.format_sql=true
    spring.jpa.show-sql=true
```

**Comment by bartoszwalacik** [comment]
Hi, which version of Javers do you use?

**Comment by p595285902** [comment]
Javers Version - 5.3.2, 
SpringBoot version - 2.0.3.RELEASE, 
Spring - 5.0.6.RELEASE

**Comment by p595285902** [comment]
More researchs:
I was getting this error only when trying to commit an Entity class.
Think I got everything according to https://javers.org/documentation/domain-configuration/#domain-model-mapping.

Entity Class:
```
@Builder
@AllArgsConstructor
@Entity
@Table(name = "PC_PRODUCTS", indexes = {
        @Index(columnList = "name", unique = true),
        @Index(columnList = "namespace", unique = true),
        @Index(columnList = "SCM_URL", unique = true)
})
@EntityListeners(value = UpdateListener.class)
@Data
public class ProductEntity extends BaseEntity implements Serializable {
...
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @JsonIgnore
    @Column(name = "id", precision = 19, nullable = false)
    private Long id;

```
I am using JPA `import javax.persistence.*;`

**Comment by bartoszwalacik** [comment]
Are you sure that this error is caused by Javers? Your log says that error is thrown by `o.h.engine.jdbc.spi.SqlExceptionHelper`, so by Hinernate. Which table is missing? All Javers' table names start with `jv_` prefix.

**Comment by p595285902** [comment]
Finally figured out why. 
Caused by this, and of course log doesnt tell me what table because the collection doesnt know either....
```
    @ElementCollection(targetClass = String.class)
    private List<String> documentationUrls;
```
Got check with my team tomorrow about these "tables". 
Sorry, for some reason Hibernate never throw exception without Javers so I thought this is Javers issue. Probably lazy load.
