### ISSUE TITLE
Error on PostgreSQL: relation "jv_commit_pk_seq" already exists

### ISSUE THREAD

**Issue by CristianZatt** [javers/javers#826]
Javers Version: 5.3.5
PostgreSQL version: 42.2.5

Error creating tables: relation "jv_commit_pk_seq" already exists

Log:
`
 :: Spring Boot ::        (v2.1.4.RELEASE)

**Comment by bartoszwalacik** [comment]
@CristianZatt read the contributing guidelines and  start again
https://github.com/javers/javers/blob/master/CONTRIBUTING.md#guidelines-for-bug-reporting

simply throwing a stack trace is not very helpful

**Comment by JavaHelper** [comment]
@All - I'm also facing this issue. Reported here: https://stackoverflow.com/questions/56852206/caused-by-org-postgresql-util-psqlexception-error-relation-jv-commit-alread?noredirect=1#comment100275296_56852206

Does anyone knows solution ?

**Comment by bartoszwalacik** [comment]
@JavaHelper read https://github.com/javers/javers/blob/master/CONTRIBUTING.md#guidelines-for-bug-reporting, this is OSS project, the rules are very simple, and are meant to save MY time.

**Comment by bartoszwalacik** [comment]
Test case is required, it should be written here https://github.com/javers/javers/tree/master/javers-persistence-sql/src/test/groovy/org/javers/repository/sql/integration/opendatabases

**Comment by antonioluzzi** [comment]
I have the same problem :-(

**Comment by JavaHelper** [comment]
its a bug that should be solve ASAP

**Comment by bartoszwalacik** [comment]
Mr. JavaHelper, why dont you to contribute a PR with the fix ASAP?

**Comment by bartoszwalacik** [comment]
fixed in 5.6.2
