### ISSUE TITLE
javers can't compare json boolean type property

### ISSUE THREAD

**Issue by lxdv163** [javers/javers#828]
If  I compare two json object, such as:
{
  prop1: true
}

{
  prop1: false
}
the compare will have no diff result

**Comment by lxdv163** [comment]
I call javers.compare(oldObject, newObject);

**Comment by bartoszwalacik** [comment]
what's json object?

**Comment by lxdv163** [comment]
org.codehaus.jackson.JsonNode

**Comment by lxdv163** [comment]
But found com.fasterxml.jackson.databind.JsonNode works well.
OK, I will ignore it, use later lib
