### ISSUE TITLE
Restoring past versions of object incrementally

### ISSUE THREAD

**Issue by ddimitrgr** [javers/javers#829]
Is applying stored diff objects to a user supplied object supported ? 

This would be useful in incrementally rebuilding historical snapshots when a large number of changes have been made. In this case implementing a paginated REST API will increase performance. In each API call the user supplies an object and it's position in the list of snapshots, and the stored diffs at earlier positions are applied to reconstruct earlier snapshots.

**Comment by bartoszwalacik** [comment]
Sorry, we don't have it in our backlog.
