### ISSUE TITLE
示例项目能否用maven啊？

### ISSUE THREAD

**Issue by binarySortTree** [javers/javers#845]
springboot整合的示例项目能否用maven啊？

**Comment by bartoszwalacik** [comment]
WFT?

**Comment by binarySortTree** [comment]
springboot整合的示例项目单元测试能否用maven构建，使用java编写代码？
Can springboot integrate sample project unit tests be built with maven, write code in java?

**Comment by binarySortTree** [comment]
你写的示例代码我完全看不懂，因为我只会java
I can't read the sample code you wrote because I only have java.

**Comment by bartoszwalacik** [comment]
stop posting in Chinese here
