### ISSUE TITLE
Spring / JPA

### ISSUE THREAD

**Issue by igler** [javers/javers#85]
I'd like to use JaVers in a SpringFramework-environment. I have several repositories connecting to a MySQL database. When will version 1.1 (documentation says it supports SQL databases) approximately be released so I can test it?

**Comment by bartoszwalacik** [comment]
Hi Michael, we are starting to develop JaversSQLRepository in next weekend. Think it should be relaeased in February. Would you like to contribute as a developer extent?

**Comment by igler** [comment]
If I have the time and knowledge to contribute, why not? At least I can help testing things.

**Comment by igler** [comment]
BTW, I am using Hibernate-Envers and spring-data-envers (https://github.com/spring-projects/spring-data-envers) so I can get revisions of a certain entity. My goal is to get an audit-trail of a certain entity or set of entities.

**Comment by bartoszwalacik** [comment]
right, audit-trail is what JaVers was created for

**Comment by bartoszwalacik** [comment]
this issue is duplicate to https://github.com/javers/javers/issues/67 
please comment there to subscribe to notifications

**Comment by bartoszwalacik** [comment]
@igler
JaversSqlRepository beta is available for testing
see version 1.0.7-SNAPSHOT
in https://oss.sonatype.org/content/repositories/snapshots/

**Comment by bartoszwalacik** [comment]
config example:
```groovy
        dbConnection = DriverManager.getConnection("jdbc:h2:tcp://localhost:9092/mem:test")
        def connectionProvider = new ConnectionProvider() {
            @Override
            Connection getConnection() {
               return dbConnection
            }
        }
        
        def sqlRepository = SqlRepositoryBuilder
                .sqlRepository()
                .withConnectionProvider(connectionProvider)
                .withDialect(DialectName.H2).build()
        javers = javers().registerJaversRepository(sqlRepository).build()
        sqlRepository.setJsonConverter(javers.jsonConverter)
```
