### ISSUE TITLE
Different @IDs returns different object

### ISSUE THREAD

**Issue by bitbaggi** [javers/javers#862]
I want to compare to versions of a Object, saved in DB with increment primary Long ID Key.
So javers compares two objects with different @IDs.

```
HistoryEntry historyEntryBefore = new HistoryEntry(1L, "DifferentField 1");
HistoryEntry historyEntryAfter = new HistoryEntry(2L, "DifferentField 2");
Diff diff = javers.compare(historyEntryBefore, historyEntryAfter);
```

Actual behavior:
Javers returns that they are completly different Objects.

Expected behavior:
Javers returns all fields (with @ID field) that are different.

**Comment by bartoszwalacik** [comment]
If two objects have different javers Id they won't be paired to comparison. That's how javers works and it won't be changed. What you can do? Provide the right javers mapping. Use @DiffIgnore to ignore your technical Ids and provide the real Id if those objects are Entities.
