### ISSUE TITLE
Javers displays empty diff when a type of object was changed but fields have the same values

### ISSUE THREAD

**Issue by kamaek** [javers/javers#871]
### Description
I have an entity, which references a value object by an abstract type. There are two descendants of this abstract type. These descendants don't declare new fields, so the only difference between them is the type of an object.

Comparison of such an entity doesn't work as expected. See the [test case](https://github.com/kamaek/javers/commit/857dae794b6141f03fbfd04b4580d21d1a868be8) to reproduce the problem.

### Current behavior
Javers returns an empty diff.

### Expected behavior
Javers returns a diff with a single change saying `the type of field "x" changed from "Foo" to "Bar"`.

I am not sure that this feature is required for all the users, so it makes sense to allow disabling/enabling of this feature.

**Comment by bartoszwalacik** [comment]
Hi, I appreciate the test case. I will take a look on this.

**Comment by bartoszwalacik** [comment]
OK, so currently Javers doesn't care much about type names of ValueObjects. ValueObjects are treated as property containers. Agreed that this change type (let's call it `ValueObjectTypeNameChange`) could be useful for some users and could be added to Javers as opt-in.

Let me know if you plan to contribute a PR with this feature.

**Comment by bartoszwalacik** [comment]
please reopen if you would like to contribute
