### ISSUE TITLE
TypeAdapters not working with org.geolatte.geom.Geometry

### ISSUE THREAD

**Issue by tim-ber** [javers/javers#872]
Using `Spring Boot 2.1.2` and `javers-spring-boot-starter-mongo 5.6.0` I have entities with geometry that I'd like to track with Javers. For example:

```java
import org.geolatte.geom.Geometry;
import javax.persistence.Id;
public class Place {
        @Id
        private Long id;
        private Geometry geometry;
        //Setters and getters
}
```

Without adding any type adapter for the geometry Javers cannot serialize it correctly, and will save changes to the geometry as ~20 different changes in the Javers database instead of one.

I've attempted to add a type adapter for the geometry using BasicStringTypeAdapter:

```java
import org.geolatte.geom.Geometry;
import org.geolatte.geom.codec.Wkt;
import org.javers.core.json.BasicStringTypeAdapter;

public class GeometryBasicStringTypeAdapter extends BasicStringTypeAdapter<Geometry> {
    @Override
    public String serialize(Geometry sourceValue) {
        // serializes geometry to string, e.g. "SRID=4326;POINT(20 30)"
        return Wkt.toWkt(sourceValue);
    }
    @Override
    public Geometry deserialize(String serializedValue) {
        // Deserializes geometry string to geometry
        return Wkt.fromWkt(serializedValue);
    }
    @Override
    public Class getValueType() {
        return Geometry.class;
    }
}
```

Javers:
```java
    @Bean
    public Javers javers() {
        MongoRepository javersMongoRepository =
                new MongoRepository(mongo().getDatabase(databaseName));
        return JaversBuilder.javers()
                .registerJaversRepository(javersMongoRepository)
                .registerValueTypeAdapter(new GeometryBasicStringTypeAdapter())
                .build();
    }
    @Bean
    public MongoClient mongo() {
        return new MongoClient();
    }
```

When a new Place with geometry is saved to database, the custom type adapters `deserialize` method never gets called. When attempting to retrieve history for the entity, I get

> [CdoSnapshotStateDeser]  INFO: Can't deserialize type-safely the Snapshot property: Field ValueType:Geometry geometry, declared in Place. JSON value: {"positions":{},"crs":{"coordinateSystem":{"axes":[{"axisName":"Lon","coordinateSystemAxisDirection":"EAST","unit":{"conversionFactor":0.0174532925199433,"crsId":{"authority":"EPSG","code":9122},"name":"degree"},"normalOrder":0},{"axisName":"Lat","coordinateSystemAxisDirection":"NORTH","unit":{"conversionFactor":0.0174532925199433,"crsId":{"authority":"EPSG","code":9122},"name":"degree"},"normalOrder":1}]},"crsId":{"authority":"EPSG","code":4326},"name":"WGS 84"}}. Looks like a type mismatch after refactoring of Place class. 

I have also tried to add a type adapter for the geometry by extending `JsonTypeAdapter`. With it the above error message doesn't get printed and the method `fromJson` method gets called, however also with this type adapter the deserialization method `toJson` never gets called, so I cannot add a custom deserilization for it. 

How should I go about successfully adding a custom serialization/deserialization for the geometry? Outside of Javers, I use `Jackson`'s `StdSerializer`/`StdDeserializer` for the geometry serialization.

**Comment by bartoszwalacik** [comment]
Hi, could you please move this code to a runnable test case (like in this issue - https://github.com/javers/javers/issues/871)?

**Comment by bartoszwalacik** [comment]
Unfortunately, Gson type adapters are not polymorfic, so you should explicitly list all concrete classes that will be handled by your type adapter. You can do it in this way (groovy):


```groovy
package org.javers.repository.mongo.cases

import com.google.gson.JsonDeserializationContext
import com.google.gson.JsonElement
import com.google.gson.JsonPrimitive
import com.google.gson.JsonSerializationContext
import com.mongodb.MongoClient
import org.geolatte.geom.Geometry
import org.geolatte.geom.Point
import org.geolatte.geom.codec.Wkt
import org.javers.core.JaversBuilder
import org.javers.core.json.JsonTypeAdapter
import org.javers.core.metamodel.type.ValueType
import org.javers.repository.mongo.MongoRepository
import spock.lang.Specification

import javax.persistence.Id

class StackCase extends Specification {

    class Place {
        @Id
        private Long id
        private Geometry geometry
    }

    class GeometryMultiTypeAdapter implements JsonTypeAdapter<Geometry> {
        @Override
        Geometry fromJson(JsonElement json, JsonDeserializationContext jsonDeserializationContext) {
            return Wkt.fromWkt(json.getAsJsonPrimitive().getAsString())
        }

        @Override
        JsonElement toJson(Geometry sourceValue, JsonSerializationContext jsonSerializationContext) {
            return  new JsonPrimitive(Wkt.toWkt(sourceValue))
        }

        @Override
        List<Class> getValueTypes() {
            return [Geometry, Point]
        }
    }

    def "should " () {
        given:
        def mongoRepository = new MongoRepository(new MongoClient().getDatabase("j_int_test"))
        def javers = JaversBuilder.javers()
                .registerJaversRepository(mongoRepository)
                .registerValueTypeAdapter(new GeometryMultiTypeAdapter())
                .build();

        when:
        Place p = new Place(id: 1, geometry: Wkt.fromWkt("POINT (5 10)") )
        def commit = javers.commit("author", p)

        println "Geometry mapping: " +  javers.getTypeMapping(Geometry).prettyPrint()

        then:
        println(commit)
        javers.getTypeMapping(Geometry) instanceof ValueType
        true
    }
}

```
