### ISSUE TITLE
Problem in MongoDB 3.2

### ISSUE THREAD

**Issue by Franck2A-KRG** [javers/javers#884]
Hi,

My system is under MongoDB 3.2.x and when there is more than 100 snapshots the second request failed because $numberDecimal is used. $numberDecimal is not supported on 3.2.x.

Here is the log of the second request that is made:

{ "find" : "jv_snapshots", "filter" : { "globalId_key" : "com.xxx.Contract/A000000#persons/0", "commitMetadata.id" : **{ "$lte" : { "$numberDecimal" : "702976.00" } } }**, "sort" : { "commitMetadata.id" : -1 }, "limit" : 15 }

How can I resolve my issue?

Thanks in advance for your help.

**Comment by bartoszwalacik** [comment]
Hi, why more than 100 snapshots and why the second request ?

**Comment by bartoszwalacik** [comment]
Please provide a reproduction scenario as a [runnable test case](https://github.com/javers/javers/tree/master/javers-core/src/test/groovy/org/javers/core/cases)

**Comment by Franck2A-KRG** [comment]
I just want a workaround with MongoDB 3.2 and a lot of snapshots. I have no time to provide a test case or to explain why your system makes multiple calls.

I have found how to resolve my issue so I close it.
