### ISSUE TITLE
CANT_DELETE_OBJECT_NOT_FOUND

### ISSUE THREAD

**Issue by vask00** [javers/javers#885]
How to solve this exception when call javers.commitShallowDelete(author, object, commitProperties); on non revision history

**Comment by bartoszwalacik** [comment]
Dear @vask00, in OSS project that's not enough to say 'It doesn't work, help me!'

You are expected to contribute, in case of bug reports, you should follow the simple rules described in [Guidelines for Bug Reporting](https://github.com/javers/javers/blob/master/CONTRIBUTING.md). Please read them, and create a new, better issue.
