### ISSUE TITLE
Missing SetChange and MapChange when there is new entries in SortedSet and SortedMap

### ISSUE THREAD

**Issue by mdii** [javers/javers#888]
After upgrading to the latest version (5.7.5), we have noticed that when we compare two objects some changes are not detected anymore. This happens for properties of type `SortedSet` and `SortedMap` (and I guess also for `NavigableMap` and `NavigableSet`). It seems that this regression is introduced in 5.2.5.

[Here](https://gist.github.com/mdii/6f0c0cbbea0ad0085ea2309864c80442) is the test case.

The issue comes from the fact that `MapType.map()` always returns an instance of `UnmodifiableMap`. When the property type is SortedMap, `NodePair.sanitize()` returns an empty map. A similar issue occurs for SortedSet.

**Comment by bartoszwalacik** [comment]
Hi , thanks for reporting, if you can contribute a PR with the fix, please do.

**Comment by mdii** [comment]
PR created

**Comment by bartoszwalacik** [comment]
Fix released in 5.7.7, @mdii thanks for your valuable contribution

**Comment by mdii** [comment]
Thank you!
