### ISSUE TITLE
Provide better collision safety for SYNCHRONIZED_SEQUENCE

### ISSUE THREAD

**Issue by duro1** [javers/javers#894]
Looking to provide better collision avoidance when using the sequence number on distributed machines.

With SYNCHRONIZED_SEQUENCE marked as not safe for distributed, RANDOM generator marked as deprecated, and CUSTOM only able to compare based on timestamp, it is difficult to ensure proper ordering of events with distributed systems if there is any time drift.

providing a secondary comparator criteria allows for reasonable expectations of both ordering and collision avoidance for a smaller number of distributed systems connected to the same JaVers repository. This is not a foolproof solution, but better than what is currently available

**Comment by bartoszwalacik** [comment]
thanks, I will manage your contribution in the next week

**Comment by bartoszwalacik** [comment]
Well, RANDOM generator isn't deprecated, it's recommended if you have more than one instance of your app writing to the same Javers repository.
Yet, if you prefer to stay with SYNCHRONIZED_SEQUENCE, you can get better sorting, which is as I understand the subject of this issue. Give me a while to check your PR.

**Comment by bartoszwalacik** [comment]
Fixed in 5.8.2, @duro1 thanks for your PR contribution.
