### ISSUE TITLE
ListCompareAlgorithm.AS_SET does not take list length into account

### ISSUE THREAD

**Issue by buderjoh** [javers/javers#903]
There is a problem if there is a comparison using the ListCompareAlgorithm.AS_SET of two Objects with a list as attribute.

Example: 

`       Floor floor = new Floor();
        floor.setArea(new BigDecimal(10));

        Floor floor1 = new Floor();
        floor1.setArea(new BigDecimal(10));

        Floor floor2 = new Floor();
        floor2.setArea(new BigDecimal(10));

        Property p1 = new Property().setFloors(Arrays.asList(floor));
        Property p2 = new Property().setFloors(Arrays.asList(floor1, floor2));

        assertTrue(build.compare(p1, p2).hasChanges());`

In this case the compare will return that there have been no changes.
Which is wrong because the second Property has 2 objects in the list instead of one.

The problem is that these 2 Objects are identical and the org.javers.core.diff.appenders.SetChangeAppender.calculateChanges(Object, Object, NodePair, JaversProperty) removes the second floor in this case beacuse the ValueObjectId is the same of floor1 and floor2.

One Solution to this would be if the two comparing Lists have a different length the change is always true.
The second solution would be that the ValueObjectId is calculated differently.

**Comment by buderjoh** [comment]
Fork: https://github.com/buderjoh/javers/tree/javers-903

TestCase:
https://github.com/buderjoh/javers/blob/javers-903/javers-core/src/test/java/org/javers/core/examples/SetCompare.java

**Comment by bartoszwalacik** [comment]
It's not a bug, it's the desired behavior of ListCompareAlgorithm.AS_SET. That's how sets works. If you put two identical objects to a set, the only one of them will be stored. If you have identical objects in your lists, you'd better stick to default ListCompareAlgorithm.

**Comment by buderjoh** [comment]
I know the behaviour of a SET but would this Problem not a new ListCompareAlgorithm?
Which checks first the size of the collection, and if the size is different the compare method has found a change.
A additional object was added to the collection therefore there the collection has changed. 
After that the collection can be transformed into a SET which also takes the order of the list into account.

**Comment by bartoszwalacik** [comment]
by definition , Set is unordered and can't contain duplicates

**Comment by buderjoh** [comment]
Yeah thats right but regarding to the compare algorithm the javers website says:
Choose the Set algorithm if you don’t care about the items ordering. JaVers will convert all Lists to Sets before comparision.

I mean that is true and works as designed but would it not make sense to add an additional algorithm which takes the length into account?

**Comment by bartoszwalacik** [comment]
sorry, i dont think we need it

**Comment by buderjoh** [comment]
Ok thanks for your support :)
