### ISSUE TITLE
ENTITY_INSTANCE_WITH_NULL_ID using javers-spring-boot-starter-sql 5.8.5

### ISSUE THREAD

**Issue by Sdwz** [javers/javers#917]
Hi there,

Using javers-spring-boot-starter-sql 5.8.5, currently going through a rough patch with it.

In one of my rest controller, which is @Transactional, I'm currently saving 2 entities, totally unrelated.

Given the following Entity with a CK ItemIdentity:

```
@Entity
@IdClass(ItemIdentity.class)
@Data
public class Item {

	@Id
    private Long id;

    @Id
    private Long version = 1L;

    @Valid
    @OneToOne(cascade = CascadeType.ALL, orphanRemoval = true)
    private ItemCharacteristics characteristics;

    ...
}
```

RestController goes like :

```
public Item createItemGroupingItems(@Valid @RequestBody Item item)
        throws Exception
{
	_itemRepository.updateQueryForSomeItemWhereIdIn(randomList);

	// random BR

	item = _itemRepository.save(item);

	if(item.getStatus.equals(Status.SOMETHING))
	{
		// Generate a new object with props totally UNRELATED to item object
		_randomObjectRepository.save(RandomObject.builder()
			.status(Status.SOMETHING)
			.build());
	}

	return item;
}
```

This method is failing with the following error :

```
JaversException: ENTITY_INSTANCE_WITH_NULL_ID: Found Entity instance 'package.item.ItemCharacteristics' with null Id-property 'id'
```

The stacktrace mentions "_randomObjectRepository.save" as the line where the exception actually occurs. Removing the line fixes the issue, but I won't have my second entity saved.

I'm failing to see here why this is causing javers to fail, as the SQL queries does occurs before the transaction rollbacks due to javers exception.

Any highlights would be appreciated.

Cheers

**Comment by bartoszwalacik** [comment]
Hi, please provide a failing test case, see https://github.com/javers/javers/tree/master/javers-core/src/test/groovy/org/javers/core/cases

**Comment by Sdwz** [comment]
Failed to produce one, will go the dirty way.
