### ISSUE TITLE
Multitenant globalId collision

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [javers/javers#918]
Hey there! First of all, congratulations on this amazing project. We were considering to use envers, but this is way better and easier to use.

In our project we are using `@JaversSpringDataAuditable` on multitenant RDBMS repositories. The multitenancy strategy is database isolation, which means that a "Tenant A" will have it's own database, "Tenant B" it's own, and so on. This also means that they will have their own identity key starting from 1, so if I insert data on "Tenant A", the data will start from ID 1. If I insert data on "Tenant B", the data will also start from ID 1.

To store the snapshots we are using `javers-spring-boot-starter-mongo` with, of course, MongoDB. In our project we do not configure MongoDB to multitenancy, but instead we add keys that identify which tenant that data belongs to. In Javers we add the multitenant key through `CommitPropertiesProvider`, and I thought that would be enough to Javers to differentiate the snapshots, but it was not, which resulted in this:

![image](https://user-images.githubusercontent.com/12160864/69728253-eb174900-1102-11ea-881a-10b16d0ae9db.png)

As you can see, both records have ID 1, but they are from different tenants. The tenant was perfectly set on the properties, but Javers identified the second insert as an update since they are the same ID.

In order to solve that I tried to find how to customize the `globalId` to add the tenant before the ID, something like `io.fesc.forms.form.Form/1-1`, and that would be enough to Javers to differentiate those records. After some research I found the ID being generated through `LiveCdoFactory` -> `GlobalIdFactory` -> `EntityType` -> `InstanceIdFactory`. If `InstanceIdFactory` were a bean I could create and bean my own `InstanceIdFactory`, but it was not the case.

So the `globalId` customization was a no go. Second thought was to configure MongoDB as multitenant the same way we did for RDBMS, letting something like Spring's `AbstractRoutingDataSource` determine which MongoDB database to use for each request. But, after reading `JaversMongoAutoConfiguration`, I think that would not be possible since Javers takes 1 configured MongoDB database and that is it, I will not be able to set the desired MongoDB database for each request.

The question is, is there a nice and "Spring Boot" way to solve this issue? I could bean my own Javers configuration and CustomComparators, but that way I would loose all the advantages from Javers autoconfigurations.

Best regards,
Rafael Pacheco.

**Comment by bartoszwalacik** [comment]
Hi Rafael, thanks for nice words :) As far as I understand multitenancy, it's the case when you have one app shared by many clients (tenants). Tenants' data should be independent, meaning that, in some cases you can have ID collisions, for example:

`Person#Bob` from tenant A
`Person#Bob` from tenant B

Javers doesn't support multitenancy for now. `GlobalId` must me unique, so you need to put tenant ID into `GlobalId` (for example `Person#Bob-tenatA`) or setup dedicated javers instance per each tenant.

**Comment by rafaelrenanpacheco** [comment]
> so you need to put tenant ID into GlobalId (for example Person#Bob-tenatA)

I thought the same, but I didn't find a clean way to achieve that. Our entities have a simple `@Id Integer` on them:

```java
@Entity
public class Form {

    @Id
    private Integer id;
```

I found that `InstanceIdFactory` was responsible for getting this ID and generating the `GlobalId`, but I didn't find a way to add the tenant information on it. If I add the tenant on `GlobalId`, then everything should work just fine.

**Comment by bartoszwalacik** [comment]
It should be coded explicitly in your domain objects:

```
@Entity
public class Form {

    private Integer id;
    private String tenant;

    ... getters
    
    @Id
    String getJaversId() {
        return id + "-" + tenant;
    }
```

**Comment by rafaelrenanpacheco** [comment]
Unfortunately we can't change the way we code ou entities with Javers specific code, or even with the tenant value, because we try to "not care" about any tenant information at all on our codebase, since each request will connect to the specific tenant database.

I'll try to figure out an way to set that `globalId` with the authenticated tenant ID. Maybe aspect could be used to achieve this.

Thanks!

**Comment by aaronalphonso** [comment]
Hi @rafaelrenanpacheco, did you manage to find an elegant solution to this problem? I am currently faced with a similar problem.

**Comment by rafaelrenanpacheco** [comment]
Hello! No, we created our own lib using hibernate events along with Spring Boot. Sadly it is not opensource because it is integrated with our other libs and own annotations.

**Comment by aaronalphonso** [comment]
No worries. Thank you for sharing that. We are looking at a custom implementation as well.

**Comment by IzzatMadaminov** [comment]
HI @aaronalphonso, can you share your findings on multitenancy? thanks in advance

**Comment by aaronalphonso** [comment]
Hey @IzzatMadaminov, I don't recall a lot of the specifics right now, but we went ahead with developing our own custom solution to tackle multitenancy.

**Comment by IzzatMadaminov** [comment]
@aaronalphonso thank you for answer, We are implementing auditing microservice for managing data changes in other microservices, do you recommend Javers, thanks
