### ISSUE TITLE
Allow JaversAuditableDelete work with id(s), e.g. deleteById(id)

### ISSUE THREAD

**Issue by IlyaNerd** [javers/javers#921]
Currently we need to provide the entire entity to mark it as deleted in javers when using JaversAuditableDelete, would be nice to be able provide only id(s) for that. Probably same way as its done in JaversSpringDataAuditableRepositoryAspect

`
@JaversAuditableDelete
void deleteById(id)
`

**Comment by bartoszwalacik** [comment]
we are open for contributions

**Comment by IlyaNerd** [comment]
i know, just wanted the approve :)

**Comment by bartoszwalacik** [comment]
Released in 5.8.7, thanks for your contribution
