### ISSUE TITLE
Value changed to Value object/Entity. NPE in GlobalIdTypeAdapter

### ISSUE THREAD

**Issue by victor6567758** [javers/javers#929]
Javers DB format is not updated when we are changing the type of some tracked class, therefore it results in NPE in GlobalIdTypeAdapter

**Comment by bartoszwalacik** [comment]
please push a failing test case with the issue reproduction

**Comment by victor6567758** [comment]
ok, will do soon

**Comment by bartoszwalacik** [comment]
you can reopen when you come up with a test case
