### ISSUE TITLE
Handling circular references 

### ISSUE THREAD

**Issue by mantithetical** [javers/javers#93]
In a bidirectional JPA OneToMany/ManyToOne association, entities have a circular reference. For example,

```
@Entity
public class Customer implements Serializable {
    @OneToMany(cascade=ALL, mappedBy="customer")
    private Set<Order> orders; 
    ...
}
@Entity
public class Order implements Serializable {
    @ManyToOne
    @JoinColumn(name="CUST_ID", nullable=false)
    private Customer customer; 
    ...
}
```
This throws off Gson and causes a stackoverflow.

**Comment by bartoszwalacik** [comment]
Normally, Javers supports circular references out of the box. This issue could be related to lazy loading proxies issue. Are those objects clean or proxied?

**Comment by mantithetical** [comment]
You are right, this is not a javers issue. Closing this.
