### ISSUE TITLE
JaversException ENTITY_INSTANCE_WITH_NULL_ID for Joined Inheritance strategy

### ISSUE THREAD

**Issue by ayushkamadji** [javers/javers#931]
Hi,

I encountered an error thrown by Javers when it attempts to check `cdoId` on an entity with a joined inheritance strategy. 
The quirk here is that the child entity class redeclares the `id` member variable. This causes variable hiding. So when the `id` is checked on an entity object declared as the parent class the reflection technique employed during the `cdoId` checking will get the `id` with value `null`, thus causing this error.
I made a repo to reproduce the issue [here](https://github.com/ayushkamadji/JaversScenario).
I will attempt a fix/PR within the coming week or so.

**Comment by bartoszwalacik** [comment]
Ok, go on, please remember about writing a test case for this issue.

**Comment by bartoszwalacik** [comment]
Reopen if you want to contribute a PR or if you come up with a failing test case
