### ISSUE TITLE
Registering Type Adapters with Spring Boot Starter

### ISSUE THREAD

**Issue by danesp2012** [javers/javers#939]
Is there a recommended way to register TypeAdapters or custom comparators when using the Spring Boot starter?

**Comment by bartoszwalacik** [comment]
There is no an easy way. Possible solution would allow user to construct `JaversBuilder` bean (with all custom configuration). 

Looks like an easy task to implement using `@ConditionalOnMissingBean`, take a look at starter class - `JaversSpringMongoApplicationConfig`. We will accept your PR if you want to contibute

**Comment by bartoszwalacik** [comment]
released in 5.15
see https://javers.org/release-notes
