### ISSUE TITLE
Requesting diff without previous snapshot throws IllegalArgumentException

### ISSUE THREAD

**Issue by gpor0** [javers/javers#943]
Javers throws IllegalArgumentException "argument should not be null" when calling findChanges on initial commits.

I believe Javers should return initial diff or just a status marking object as created instead of throwing exception.

**Comment by bartoszwalacik** [comment]
please push a test case (see https://github.com/javers/javers/tree/master/javers-core/src/test/groovy/org/javers/core/cases)

**Comment by bartoszwalacik** [comment]
Reopen if you want to contribute a PR or if you come up with a failing test case
