### ISSUE TITLE
Can Javers dynamically switch schema provided a tenant identifier resolver?

### ISSUE THREAD

**Issue by kushagra-mahajan** [javers/javers#944]
Currently, we are working on multi tenant applications using multi-schema approach. But Javers currently use public schema, is it possible to switch to a different schema at runtime assuming tenant identifier resolver implementation is there?

**Comment by bartoszwalacik** [comment]
Javers schema is configurable but you can not change it in runtime. Still you can create one javers instance per one your tenant and commit changes to the multiple javers instances (depending on tenant)

**Comment by edbras** [comment]
What work needs to be done to make this work?
