### ISSUE TITLE
Javers - Can't track mongo updates inside a document

### ISSUE THREAD

**Issue by mehtakaran9** [javers/javers#945]
I am trying to keep a track of changes made on specific fields inside a document. This is my user class. I want to keep a track of any change made in count using Javers.

```
@Document
public class User {

    @Id
    private String userId;
    private String name;
    private int count;
    private Date creationDate = new Date();
    private Map<String, String> userSettings = new HashMap<>();
}

```

I have added the following code to keep a track of whenever a new Object of User is created.

```
         @Override 
         public User addNewUser(User user) {
             mongoTemplate.save(user);
             javers.commit("Added", user);
             return user;}

```

This is the updateCount method using MongoTemplate:

        @Override public boolean updateCount(String name) {
        Query query = new Query();
        query.addCriteria(Criteria.where("name").is(name));
        query.addCriteria(Criteria.where("count").gt(0));
        Update update = new Update();
        update.inc("count", -1);
        return Objects
            .requireNonNull(reactiveMongoTemplate.updateFirst(query, update, User.class).block())
            .getModifiedCount() == 1; }

Now what I want to track is to commit some kind of change at the end of updateCount method call. But these changes can't be committed unless I have an entity object. How do I go about this?

**Comment by bartoszwalacik** [comment]
this is cross-posted

**Comment by yihtserns** [comment]
> this is cross-posted

What does this mean?

**Comment by bartoszwalacik** [comment]
https://stackoverflow.com/questions/60573776/javers-cant-track-mongo-updates-inside-a-document
