### ISSUE TITLE
wrong db type for state column in jv_snapshot

### ISSUE THREAD

**Issue by dmushkov** [javers/javers#946]
in order to support national language (ex. Cyrillic) db type for state column should be nvarchar(max)
currently it's set to varchar(max)

**Comment by bartoszwalacik** [comment]
1. Follow the https://github.com/javers/javers/blob/master/CONTRIBUTING.md#guidelines-for-bug-reporting
2. Which database are you talking about?

**Comment by dmushkov** [comment]
1) sorry for non aligned bug report
2) MSSQL

**Comment by bartoszwalacik** [comment]
push your test case to `MSSqlDockerIntegrationTest.groovy`

**Comment by dmushkov** [comment]
Sorry I looked at this file but did not catch what is expected 
i guess change is needed here 
https://github.com/javers/javers/blob/master/javers-persistence-sql/src/main/java/org/javers/repository/sql/schema/JaversSchemaManager.java

```
/**
     * JaVers 3.3.0 to 3.3.1 MsSql schema migration
     *
     * This method is needed for upgrading TEXT columns to VARCHAR(MAX) since TEXT is deprecated.
     */
    private void alterMssqlTextColumns() {
        ColumnType stateColType = getTypeOf(getSnapshotTableNameWithSchema(), "state");
        ColumnType changedPropertiesColType = getTypeOf(getSnapshotTableNameWithSchema(), "state");

        if(stateColType.typeName.equals("text")) {
           executeSQL("ALTER TABLE " + getSnapshotTableNameWithSchema() + " ALTER COLUMN state VARCHAR(MAX)"); 

**should be** 

executeSQL("ALTER TABLE " + getSnapshotTableNameWithSchema() + " ALTER COLUMN state NVARCHAR(MAX)");         }

        if(changedPropertiesColType.typeName.equals("text")) {
            executeSQL("ALTER TABLE " + getSnapshotTableNameWithSchema() + " ALTER COLUMN changed_properties VARCHAR(MAX)");
        }
    }
```

**Comment by bartoszwalacik** [comment]
@dmushkov please don't write code in comments, push your failing test case to your fork of this repository, in the place which I have shown you

**Comment by bartoszwalacik** [comment]
Reopen if you want to contribute a PR or if you come up with a failing test case
