### ISSUE TITLE
joda-time replacement

### ISSUE THREAD

**Issue by deedarb** [javers/javers#949]
Is there any limitations with java.time (introduced in JDK 8)? 

Is joda is required for correct diff for dates?

**Comment by deedarb** [comment]
removed here: if issue is accepted, i can send pull request.
https://github.com/deedarb/javers/commit/112e6d68879f999efbde8471dd23a52a1c723a74

 ./gradlew :javers-core:test  

all tests passed with little modifications 😄

**Comment by bartoszwalacik** [comment]
joda is considered legacy, use java.time everywere

**Comment by deedarb** [comment]
javers-core has joda-time dependency, so when i include javers to my project then joda-time also comes with javers, is it ok?

**Comment by bartoszwalacik** [comment]
javers-core has no dependency on joda-time
