### ISSUE TITLE
Javers annotations as separate artifact

### ISSUE THREAD

**Issue by deedarb** [javers/javers#950]
I have shared POJO classes module with javers annotations.
If another module depends on shared POJO module then it includes javers-core with all functionalities which might be not used.
For example we have project structure as:
only **service3** needs to compute diff for models

    service1 with dependency on model
    service2 with dependency on model
    service3 with dependency on model
    model with dependency on javers-core

if we had separate javers-annotations artifact then it could be

    service1 with dependency on model
    service2 with dependency on model
    service3 with dependency on model and javers-core
    model with dependency on javers-annotations

**Comment by bartoszwalacik** [comment]
javers modules are fine, we are not going to split javers-core, it's a litgthweight module

```
    compile "org.slf4j:slf4j-api:$slf4jApiVersion"
    compile "com.google.code.gson:gson:$gsonVersion"
    compile 'org.picocontainer:picocontainer:2.15'
    compile "io.github.classgraph:classgraph:$classgraphVersion"
```
