### ISSUE TITLE
Add support to @PropertyValue

### ISSUE THREAD

**Issue by emreyh** [javers/javers#956]
Hi, 
First of all thank you for this excellent plugin. I would be glad if the following features come. What do you think about these features?

1- if the value of change is null, pass a default value to it.
	@PropertyValue(defaultValue = "defaultValue")
	
	
2- If the property's type is marked as an enum, replace with the return value in the toString method. 
3- If the member is a date, format the date and return formatted date.

Without these features, a type check will be made for each member and will have to be prepared for presentation. If it is also customized as @PropertyName ("xyz") it will be more difficult to do this.

```java
class Foo{
	@PropertyValue(type = Enum.class, enumClass = Gender.class, defaultValue = "Empty")
	String baz = "M"; 
        @PropertyValue(type= Enum.class, enumClass = YesNoEnum.class, defaultValue ="No")
        Boolean bar = Boolean.False;
        @PropertyValue(type= Date.class, formatDate= "yyyyMMdd")
        Date date;

}
enum Gender {
	M("Male"),
	F("Female");

	String desc;

	private Gender(String desc) {
		this.desc = desc;
	}

	@Override
	public String toString() {
		return this.desc;
	}
}

enum YesNoEnum {
	TRUE("Yes"),
	FALSE("No");
	String desc;

	private YesNoEnum(String desc) {
		this.desc = desc;
	}

	@Override
	public String toString() {
		return this.desc;
	}

}
```

**Comment by bartoszwalacik** [comment]
Hi, 
1 - it's out of scope of Javers. Default values should be managed in your domain model, not in Javers.
2, 3 - I'm not sure if I understand You. You suggests that Javers should your data types to Strings?
