### ISSUE TITLE
Find changes does not include changes made in inner entity linked by @DBRef

### ISSUE THREAD

**Issue by patpro1** [javers/javers#959]
When running `javers.findChanges(...)` result set does not contain changes that appeared in object linked as @DBRef in current entity.

**Comment by patpro1** [comment]
I'll prepare test case for it.

**Comment by patpro1** [comment]
@bartoszwalacik I've added test case to my fork: 

https://github.com/patpro1/javers/commit/57be872f2200af0fee73987c96a55ae6749ae200

**Comment by bartoszwalacik** [comment]
@patpro1 your second test case - "should return changes for parent object containing changes in @DBRef objects" -  is invalid. findChanges never loads referenced Entities it could load only child Value Objects

**Comment by bartoszwalacik** [comment]
check `findShadows` for eager loading of referenced entities

**Comment by patpro1** [comment]
I've thought that it might be idea for improvement/feature? In our scenario we want to use Javers to show view of changes in given entity (with information about when changes occurred and what fields were changed). Before using `@DBRef` we've used  `findChanges` to provide all data for this view, but if we want to show also referenced object changes, we need to use `findShadows` and then iterate over this shadows and make `diff` between pairs (to changed fields between versions). So I've thought that this is more. common case and it might be provided by Javers.

**Comment by bartoszwalacik** [comment]
It's easy to add source `CdoSnapshot` to each `Shadow`, little bit more work too add (optionally) also list of Changes - diff between current  shadow.snapshot and a previous one. Let me know if you are eager to contribute
