### ISSUE TITLE
if a child table is created then parent entity is updated but when we click on parents entity its not showing the difference.

### ISSUE THREAD

**Issue by FarhanKhalid7** [javers/javers#963]
if a child table is created then parent entity is updated but when we click on parents entity its not showing the difference.but when we update child again then it shows difference in parent ?

**Comment by bartoszwalacik** [comment]
I have no idea what you are talking about

**Comment by FarhanKhalid7** [comment]
Ok first of all apologies .this is my first ever question to github so i am not aware of proper guidelines of posting a issue i am trying my best to explain this so bear with me if you found any issue

Ok we are using Javers for entity audit .we included it as sub generator in our jhipster project.
the issue we are facing that take an example of two models from my project DOFGlobalRule And
DOFGlobalCondition. the DOFGlobalRule have one to may relationship with DOFGlobalCondition

so when i save in DOFGlobalRule .its snapshot is saving fine with initial state  as you can see form the screenshot
<img width="1440" alt="Screen Shot 2020-04-23 at 4 04 11 PM" src="https://user-images.githubusercontent.com/64140598/80093487-08e7bd80-857e-11ea-858d-bd4bbd0b6733.png">

 when i save in DOFGlobalCondition for dof global rule just i saved earlier, child table snap shot is saving fine with initial state with also showing reference of its parent table
<img width="1440" alt="Screen Shot 2020-04-23 at 4 08 39 PM" src="https://user-images.githubusercontent.com/64140598/80093816-9d522000-857e-11ea-9389-9cafecd88705.png">

but the issue is that the when parent table(DOFGlobalRule) snapshot is update with update state it is not showing reference of child table (DOFGlobalCondition) like you can see from the screenshot
<img width="1440" alt="Screen Shot 2020-04-23 at 4 08 51 PM" src="https://user-images.githubusercontent.com/64140598/80094058-0afe4c00-857f-11ea-8f13-7f5869e3650c.png">

this happened only for first time if i again change that child table the parent table snapshot is showing  the child correct information
