### ISSUE TITLE
Querying snapshots 'toCommitId' generates incorrect results when using RANDOM CommitIdGenerator

### ISSUE THREAD

**Issue by M0rfic** [javers/javers#966]
Hi,

I'm using `javers` with spring boot, and it's configured as below
```
javers:
    new-object-snapshot: true
    commit-id-generator: RANDOM
```
For one of the features, I'm trying to retrieve the list of snapshots up to a specified commit id:
```
javers.findSnapshots(QueryBuilder.byClass(...)
      .withNewObjectChanges()
      .withCommitProperty(...)
      .toCommitId(CommitId.valueOf("4900110407498891977.00"))
      .build())
```

Given the commits below, the result will contain only the data for `4900110407498891977.00`, although it was done after `7685062511355815669.00`:

| commit\_pk | author | commit\_date | commit\_date\_instant | commit\_id |
| :--- | :--- | :--- | :--- | :--- |
| 100 | me | 2020-04-27 11:25:06.904000 | 2020-04-27T08:25:06.904263900Z | 7685062511355815669.00 |
| 101 | me | 2020-04-27 11:28:43.604000 | 2020-04-27T08:28:43.604394800Z | 4900110407498891977.00 |

Looking at line [75 in `SnapshotQuery`](https://github.com/javers/javers/blob/a3e6559ac083449fb2a48541105bd0fa7a453c66/javers-persistence-sql/src/main/java/org/javers/repository/sql/finders/SnapshotQuery.java#L75), I noticed: 
```
queryParams.toCommitId().ifPresent(commitId -> {
    selectBuilder.and(COMMIT_COMMIT_ID, "<=", bigDecimalParam(commitId.valueAsNumber()));
});
```
which would explain the odd result, since the id I had specified is smaller the the other one.

Shouldn't the bellow statement regarding Shadow queries be applicable to snapshots as well?
>      * <b>Warning!</b> When RANDOM generator is set,
>      * Shadow query runner sorts commits by commitDateInstant.
>      * It means, that Shadow queries would be correct only
>      * if all application servers have synchronized clocks.

Kind regards

**Comment by bartoszwalacik** [comment]
Hi, you are right, `QueryBuilder.toCommitId()` doesn't make sense with RANDOM commitId is used. IllegalArgumentException should be thrown in this case.

**Comment by M0rfic** [comment]
Hi,

Not questioning the design or anything, just asking for the sake of clarity. Would it not be possible to sort by `commitDateInstant` instead?

Kind regards

**Comment by bartoszwalacik** [comment]
looks like `QueryBuilder.to(LocalDate toDate)` does it. `CommitId` holds only a number

**Comment by M0rfic** [comment]
That's true, we have this as an alternative/workaround but usually people work with IDs.

I guess what I'm trying to say is that, although I did not dig that deep in the sources, I was hoping there was the possibility of having it work similar to shadow queries, but that may not be doable due to architectural or other types of limitations.

Thank you nonetheless!
