### ISSUE TITLE
Class name contains verb which is not a coding standard

### ISSUE THREAD

**Issue by aravindhrs** [javers/javers#967]
Class name contains **verb** which is not a coding standard. Class name should always be **noun**.

https://www.oracle.com/technetwork/java/codeconventions-135099.html

package **org.javers.common.validation** has a class name has "**Validate**"

```
package org.javers.common.validation;

public class Validate {
    //implementation
}
```

_If it's good to change, then let me know I'll take the pull request to fix this._

**Comment by bartoszwalacik** [comment]
no thanks, I'm good with this name. If you'd like to contribute, there are real issues here
