### ISSUE TITLE
support for Spring boot 2.3.0.RELEASE

### ISSUE THREAD

**Issue by dacopan** [javers/javers#973]
build gradle failed when migrate to spring boot 2.3.0.RELEASE
error: Index 9730 out of bounds for length 8192

**Comment by bartoszwalacik** [comment]
build of what?

**Comment by dacopan** [comment]
> build of what?

1. create spring boot project 
2. ./gradlew bootRun

> Execution failed for task ':compileJava'.
> Index 9730 out of bounds for length 8192

Demo project https://gitlab.com/JedAI/community/javers-error

**Comment by bartoszwalacik** [comment]
looks like an issue with Gragle 6

**Comment by dacopan** [comment]
> looks like an issue with Gradle 6

only fails with javers `5.9.0` 
Gradle 6.3+ with any old versions of Javers works well

**Comment by bartoszwalacik** [comment]
I have not idea what to with this error, gradle 6.3 just fails and gives ridiculous error message: `Index 9730 out of bounds for length 8192`

**Comment by bongboy** [comment]
Same error in maven also. Javers `5.8.12` works fine.

**Comment by dacopan** [comment]
> I have not idea what to with this error, gradle 6.3 just fails and gives ridiculous error message: `Index 9730 out of bounds for length 8192`

I run gradle with debug and apparently fails because pom.xml of javers-core has line breaks.
I'm investigating similar issue and occurs when publish to maven using windows

@bartoszwalacik do you have this issue if yo install to local maven and use it instead of maven central version?

**Comment by bartoszwalacik** [comment]
well, I see it for the first time, javers is built on travis CI (linux). what has changed recently in javers is gradle bump from 5.x to 6.3

**Comment by bartoszwalacik** [comment]
looks like `classgraph` is the culprit

**Comment by bartoszwalacik** [comment]
Fixed in 5.9.1, @dacopan thanks for the good runnable test case
