### ISSUE TITLE
Fix link for 'Repository configuration' doc page

### ISSUE THREAD

**Issue by cybuch** [javers/javers#977]
Dear friends,
on [doc page](https://javers.org/documentation/repository-configuration/) there's link, which is dead (link to https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/TypeAdapter.html). 
Maybe you've meant this: https://www.javadoc.io/doc/com.google.code.gson/gson/2.8.2/com/google/gson/TypeAdapter.html
Anyways, please fix, possibly there're other places where you might link to https://google-gson.googlecode.com
Best regards

**Comment by bartoszwalacik** [comment]
hi, thanks for reporting, feel free to contribute a PR, we will merge it
