### ISSUE TITLE
javers-spring-boot-starter-mongo autoconfiguration fails on Spring Boot 2.3.0

### ISSUE THREAD

**Issue by santam85** [javers/javers#982]
Due to the upgrade of mongo driver in the latest Spring Boot Data Mongo present in Spring Boot 2.3.0, the autoconfiguration of Javers fails due to a missing `org.mongodb.MongoClient` bean.

This was moved to `org.mongodb.client.MongoClient`.

**Comment by bartoszwalacik** [comment]
fixed in 5.9.2
