### ISSUE TITLE
List of Value Objects LEVENSHTEIN_DISTANCE implementation

### ISSUE THREAD

**Issue by avinashr91** [javers/javers#993]
Is LEVENSHTEIN_DISTANCE implemented for value objects inside a list. While comparing, there are value changes for shifts whereas I need only the newly added object / removed object from the diff. I am using diff.compare(obj1,obj2). All, I'm doing is removing a value object from middle of the list. But I'm getting a lot of value changes for all the properties inside the value object and an ObjectRemoved change. The ObjectRemoved change is always the last value object of the list.

**Comment by bartoszwalacik** [comment]
Please follow the guidelines-for-bug-reporting  https://github.com/javers/javers/blob/master/CONTRIBUTING.md#guidelines-for-bug-reporting
